// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_MovieSceneNiagaraFloatParameterTrack.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_MovieSceneNiagaraFloatParameterTrack = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"MovieSceneNiagaraFloatParameterTrack", /* tp_name */
	sizeof(FNePyObject_MovieSceneNiagaraFloatParameterTrack), /* tp_basicsize */
};

static PyObject* FNePyObject_MovieSceneNiagaraFloatParameterTrack_Class(PyObject* InSelf) {
	UClass* Class = UMovieSceneNiagaraFloatParameterTrack::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_MovieSceneNiagaraFloatParameterTrack_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_MovieSceneNiagaraFloatParameterTrack_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_MovieSceneNiagaraFloatParameterTrack* NePyObjectNew_MovieSceneNiagaraFloatParameterTrack(UMovieSceneNiagaraFloatParameterTrack* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_MovieSceneNiagaraFloatParameterTrack));
	FNePyObject_MovieSceneNiagaraFloatParameterTrack* RetValue = (FNePyObject_MovieSceneNiagaraFloatParameterTrack*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_MovieSceneNiagaraFloatParameterTrack* NePyObjectCheck_MovieSceneNiagaraFloatParameterTrack(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_MovieSceneNiagaraFloatParameterTrack))
	{
		return (FNePyObject_MovieSceneNiagaraFloatParameterTrack*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_MovieSceneNiagaraFloatParameterTrack()
{
	return &FNePyObjectType_MovieSceneNiagaraFloatParameterTrack;
}

PyTypeObject* NePyNePyWrappedClassInit_MovieSceneNiagaraFloatParameterTrack(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_MovieSceneNiagaraFloatParameterTrack;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_MovieSceneNiagaraFloatParameterTrack_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_MovieSceneNiagaraFloatParameterTrack,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_MovieSceneNiagaraFloatParameterTrack(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UMovieSceneNiagaraFloatParameterTrack::StaticClass(), NePyNePyWrappedClassInit_MovieSceneNiagaraFloatParameterTrack);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UMovieSceneNiagaraFloatParameterTrack*& OutVal)
	{
		if (FNePyObject_MovieSceneNiagaraFloatParameterTrack* PyObj = NePyObjectCheck_MovieSceneNiagaraFloatParameterTrack(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif