#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "MovieScene/Parameters/MovieSceneNiagaraColorParameterTrack.h"
// region include end

class FNePyObject_MovieSceneNiagaraColorParameterTrack : public FNePyObjectBase
{
public:
	inline UMovieSceneNiagaraColorParameterTrack* GetValue()
	{
		return (UMovieSceneNiagaraColorParameterTrack*)Value;
	}
};

void NePyInitObject_MovieSceneNiagaraColorParameterTrack(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_MovieSceneNiagaraColorParameterTrack* NePyObjectCheck_MovieSceneNiagaraColorParameterTrack(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_MovieSceneNiagaraColorParameterTrack();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UMovieSceneNiagaraColorParameterTrack*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif