// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_NiagaraDataInterfaceArrayUInt8.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePyArrayWrapper.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_NiagaraDataInterfaceArrayUInt8 = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"NiagaraDataInterfaceArrayUInt8", /* tp_name */
	sizeof(FNePyObject_NiagaraDataInterfaceArrayUInt8), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_NiagaraDataInterfaceArrayUInt8_Prop_GetInternalIntData(FNePyObject_NiagaraDataInterfaceArrayUInt8* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'InternalIntData'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->InternalIntData, "InternalIntData");
	return RetValue;
}

int FNePyObject_NiagaraDataInterfaceArrayUInt8_Prop_SetInternalIntData(FNePyObject_NiagaraDataInterfaceArrayUInt8* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'InternalIntData'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->InternalIntData, "InternalIntData"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bytes'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_NiagaraDataInterfaceArrayUInt8_getset[] = {
	{ (char*)"InternalIntData", (getter)FNePyObject_NiagaraDataInterfaceArrayUInt8_Prop_GetInternalIntData, (setter)FNePyObject_NiagaraDataInterfaceArrayUInt8_Prop_SetInternalIntData, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

static PyObject* FNePyObject_NiagaraDataInterfaceArrayUInt8_Class(PyObject* InSelf) {
	UClass* Class = UNiagaraDataInterfaceArrayUInt8::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_NiagaraDataInterfaceArrayUInt8_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_NiagaraDataInterfaceArrayUInt8_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_NiagaraDataInterfaceArrayUInt8* NePyObjectNew_NiagaraDataInterfaceArrayUInt8(UNiagaraDataInterfaceArrayUInt8* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_NiagaraDataInterfaceArrayUInt8));
	FNePyObject_NiagaraDataInterfaceArrayUInt8* RetValue = (FNePyObject_NiagaraDataInterfaceArrayUInt8*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_NiagaraDataInterfaceArrayUInt8* NePyObjectCheck_NiagaraDataInterfaceArrayUInt8(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_NiagaraDataInterfaceArrayUInt8))
	{
		return (FNePyObject_NiagaraDataInterfaceArrayUInt8*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_NiagaraDataInterfaceArrayUInt8()
{
	return &FNePyObjectType_NiagaraDataInterfaceArrayUInt8;
}

PyTypeObject* NePyNePyWrappedClassInit_NiagaraDataInterfaceArrayUInt8(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_NiagaraDataInterfaceArrayUInt8;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_NiagaraDataInterfaceArrayUInt8_getset;
	NePyObjectType->tp_methods = FNePyObjectType_NiagaraDataInterfaceArrayUInt8_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_NiagaraDataInterfaceArrayUInt8,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_NiagaraDataInterfaceArrayUInt8(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UNiagaraDataInterfaceArrayUInt8::StaticClass(), NePyNePyWrappedClassInit_NiagaraDataInterfaceArrayUInt8);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UNiagaraDataInterfaceArrayUInt8*& OutVal)
	{
		if (FNePyObject_NiagaraDataInterfaceArrayUInt8* PyObj = NePyObjectCheck_NiagaraDataInterfaceArrayUInt8(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif