#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "NiagaraDataChannel_Islands.h"
// region include end

class FNePyObject_NiagaraDataChannelHandler_Islands : public FNePyObjectBase
{
public:
	inline UNiagaraDataChannelHandler_Islands* GetValue()
	{
		return (UNiagaraDataChannelHandler_Islands*)Value;
	}
};

void NePyInitObject_NiagaraDataChannelHandler_Islands(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_NiagaraDataChannelHandler_Islands* NePyObjectCheck_NiagaraDataChannelHandler_Islands(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_NiagaraDataChannelHandler_Islands();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UNiagaraDataChannelHandler_Islands*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif