// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_NiagaraActor.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_NiagaraActor = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"NiagaraActor", /* tp_name */
	sizeof(FNePyObject_NiagaraActor), /* tp_basicsize */
};

// region func body begin
PyObject* FNePyObject_NiagaraActor_GetDestroyOnSystemFinish(FNePyObject_NiagaraActor* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetDestroyOnSystemFinish'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetDestroyOnSystemFinish();

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_NiagaraActor_SetDestroyOnSystemFinish(FNePyObject_NiagaraActor* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetDestroyOnSystemFinish'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	bool bShouldDestroyOnSystemFinish;
	if (!NePyBase::ToCpp(PyArgs[0], bShouldDestroyOnSystemFinish))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'bShouldDestroyOnSystemFinish' must have type 'bool'");
		return nullptr;
	}

	InSelf->GetValue()->SetDestroyOnSystemFinish(bShouldDestroyOnSystemFinish);
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_NiagaraActor_Class(PyObject* InSelf) {
	UClass* Class = ANiagaraActor::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_NiagaraActor_methods[] = {
	{"GetDestroyOnSystemFinish", NePyCFunctionCast(&FNePyObject_NiagaraActor_GetDestroyOnSystemFinish), METH_NOARGS, ""},
	{"SetDestroyOnSystemFinish", NePyCFunctionCast(&FNePyObject_NiagaraActor_SetDestroyOnSystemFinish), METH_O, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_NiagaraActor_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_NiagaraActor* NePyObjectNew_NiagaraActor(ANiagaraActor* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_NiagaraActor));
	FNePyObject_NiagaraActor* RetValue = (FNePyObject_NiagaraActor*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_NiagaraActor* NePyObjectCheck_NiagaraActor(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_NiagaraActor))
	{
		return (FNePyObject_NiagaraActor*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_NiagaraActor()
{
	return &FNePyObjectType_NiagaraActor;
}

PyTypeObject* NePyNePyWrappedClassInit_NiagaraActor(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_NiagaraActor;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_NiagaraActor_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_NiagaraActor,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_NiagaraActor(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		ANiagaraActor::StaticClass(), NePyNePyWrappedClassInit_NiagaraActor);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, ANiagaraActor*& OutVal)
	{
		if (FNePyObject_NiagaraActor* PyObj = NePyObjectCheck_NiagaraActor(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif