// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_NiagaraDataInterfaceIntRenderTarget2D.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/core/NePyStruct_IntPoint.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"NiagaraDataInterfaceIntRenderTarget2D", /* tp_name */
	sizeof(FNePyObject_NiagaraDataInterfaceIntRenderTarget2D), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_NiagaraDataInterfaceIntRenderTarget2D_Prop_GetSize(FNePyObject_NiagaraDataInterfaceIntRenderTarget2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Size'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_IntPoint(InSelf->GetValue()->Size);
	return RetValue;
}

int FNePyObject_NiagaraDataInterfaceIntRenderTarget2D_Prop_SetSize(FNePyObject_NiagaraDataInterfaceIntRenderTarget2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Size'"))
	{
		return -1;
	}

	if (FNePyStruct_IntPoint* PySize = NePyStructCheck_IntPoint(InValue))
	{
		InSelf->GetValue()->Size = *((FIntPoint*)PySize->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'IntPoint'");
		return -1;
	}
	return 0;
}

// unsupported StructProperty RenderTargetUserParameter [type not exported: NiagaraUserParameterBinding]
// region prop getset body end

static PyGetSetDef FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D_getset[] = {
	{ (char*)"Size", (getter)FNePyObject_NiagaraDataInterfaceIntRenderTarget2D_Prop_GetSize, (setter)FNePyObject_NiagaraDataInterfaceIntRenderTarget2D_Prop_SetSize, nullptr, nullptr },
	// unsupported StructProperty RenderTargetUserParameter [type not exported: NiagaraUserParameterBinding],
	{ nullptr } /* Sentinel */
};

static PyObject* FNePyObject_NiagaraDataInterfaceIntRenderTarget2D_Class(PyObject* InSelf) {
	UClass* Class = UNiagaraDataInterfaceIntRenderTarget2D::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_NiagaraDataInterfaceIntRenderTarget2D_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_NiagaraDataInterfaceIntRenderTarget2D* NePyObjectNew_NiagaraDataInterfaceIntRenderTarget2D(UNiagaraDataInterfaceIntRenderTarget2D* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D));
	FNePyObject_NiagaraDataInterfaceIntRenderTarget2D* RetValue = (FNePyObject_NiagaraDataInterfaceIntRenderTarget2D*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_NiagaraDataInterfaceIntRenderTarget2D* NePyObjectCheck_NiagaraDataInterfaceIntRenderTarget2D(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D))
	{
		return (FNePyObject_NiagaraDataInterfaceIntRenderTarget2D*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_NiagaraDataInterfaceIntRenderTarget2D()
{
	return &FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D;
}

PyTypeObject* NePyNePyWrappedClassInit_NiagaraDataInterfaceIntRenderTarget2D(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D_getset;
	NePyObjectType->tp_methods = FNePyObjectType_NiagaraDataInterfaceIntRenderTarget2D_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_NiagaraDataInterfaceIntRenderTarget2D,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_NiagaraDataInterfaceIntRenderTarget2D(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UNiagaraDataInterfaceIntRenderTarget2D::StaticClass(), NePyNePyWrappedClassInit_NiagaraDataInterfaceIntRenderTarget2D);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UNiagaraDataInterfaceIntRenderTarget2D*& OutVal)
	{
		if (FNePyObject_NiagaraDataInterfaceIntRenderTarget2D* PyObj = NePyObjectCheck_NiagaraDataInterfaceIntRenderTarget2D(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif