// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_HorizontalBoxSlot.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/umg/NePyStruct_SlateChildSize.h"
#include "NePy/Auto/slate/NePyStruct_Margin.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_HorizontalBoxSlot = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"HorizontalBoxSlot", /* tp_name */
	sizeof(FNePyObject_HorizontalBoxSlot), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_HorizontalBoxSlot_Prop_GetSize(FNePyObject_HorizontalBoxSlot* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Size'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_SlateChildSize(InSelf->GetValue()->Size);
	return RetValue;
}

int FNePyObject_HorizontalBoxSlot_Prop_SetSize(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Size'"))
	{
		return -1;
	}

	FSlateChildSize TempValueForSetter;
	if (FNePyStruct_SlateChildSize* PySize = NePyStructCheck_SlateChildSize(InValue))
	{
		TempValueForSetter = *((FSlateChildSize*)PySize->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'SlateChildSize'");
		return -1;
	}
	InSelf->GetValue()->SetSize(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_HorizontalBoxSlot_Prop_GetPadding(FNePyObject_HorizontalBoxSlot* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Padding'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Margin(InSelf->GetValue()->Padding);
	return RetValue;
}

int FNePyObject_HorizontalBoxSlot_Prop_SetPadding(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Padding'"))
	{
		return -1;
	}

	FMargin TempValueForSetter;
	if (FNePyStruct_Margin* PyPadding = NePyStructCheck_Margin(InValue))
	{
		TempValueForSetter = *((FMargin*)PyPadding->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Margin'");
		return -1;
	}
	InSelf->GetValue()->SetPadding(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_HorizontalBoxSlot_Prop_GetHorizontalAlignment(FNePyObject_HorizontalBoxSlot* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HorizontalAlignment'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->HorizontalAlignment);
	return RetValue;
}

int FNePyObject_HorizontalBoxSlot_Prop_SetHorizontalAlignment(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HorizontalAlignment'"))
	{
		return -1;
	}

	TEnumAsByte<EHorizontalAlignment> TempValueForSetter;
	uint8 HorizontalAlignmentTemp;
	if (!NePyBase::ToCpp(InValue, HorizontalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EHorizontalAlignment)");
		return -1;
	}
	TempValueForSetter = (EHorizontalAlignment)HorizontalAlignmentTemp;
	InSelf->GetValue()->SetHorizontalAlignment(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_HorizontalBoxSlot_Prop_GetVerticalAlignment(FNePyObject_HorizontalBoxSlot* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VerticalAlignment'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->VerticalAlignment);
	return RetValue;
}

int FNePyObject_HorizontalBoxSlot_Prop_SetVerticalAlignment(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VerticalAlignment'"))
	{
		return -1;
	}

	TEnumAsByte<EVerticalAlignment> TempValueForSetter;
	uint8 VerticalAlignmentTemp;
	if (!NePyBase::ToCpp(InValue, VerticalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EVerticalAlignment)");
		return -1;
	}
	TempValueForSetter = (EVerticalAlignment)VerticalAlignmentTemp;
	InSelf->GetValue()->SetVerticalAlignment(TempValueForSetter);
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_HorizontalBoxSlot_getset[] = {
	{ (char*)"Size", (getter)FNePyObject_HorizontalBoxSlot_Prop_GetSize, (setter)FNePyObject_HorizontalBoxSlot_Prop_SetSize, nullptr, nullptr },
	{ (char*)"Padding", (getter)FNePyObject_HorizontalBoxSlot_Prop_GetPadding, (setter)FNePyObject_HorizontalBoxSlot_Prop_SetPadding, nullptr, nullptr },
	{ (char*)"HorizontalAlignment", (getter)FNePyObject_HorizontalBoxSlot_Prop_GetHorizontalAlignment, (setter)FNePyObject_HorizontalBoxSlot_Prop_SetHorizontalAlignment, nullptr, nullptr },
	{ (char*)"VerticalAlignment", (getter)FNePyObject_HorizontalBoxSlot_Prop_GetVerticalAlignment, (setter)FNePyObject_HorizontalBoxSlot_Prop_SetVerticalAlignment, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_HorizontalBoxSlot_SetVerticalAlignment(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetVerticalAlignment'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 InVerticalAlignmentTemp;
	if (!NePyBase::ToCpp(PyArgs[0], InVerticalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InVerticalAlignment' must have type 'int'(EVerticalAlignment)");
		return nullptr;
	}
	EVerticalAlignment InVerticalAlignment = (EVerticalAlignment)InVerticalAlignmentTemp;

	InSelf->GetValue()->SetVerticalAlignment(InVerticalAlignment);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_HorizontalBoxSlot_SetHorizontalAlignment(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetHorizontalAlignment'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 InHorizontalAlignmentTemp;
	if (!NePyBase::ToCpp(PyArgs[0], InHorizontalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InHorizontalAlignment' must have type 'int'(EHorizontalAlignment)");
		return nullptr;
	}
	EHorizontalAlignment InHorizontalAlignment = (EHorizontalAlignment)InHorizontalAlignmentTemp;

	InSelf->GetValue()->SetHorizontalAlignment(InHorizontalAlignment);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_HorizontalBoxSlot_SetSize(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetSize'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FSlateChildSize* InSize;
	if (FNePyStruct_SlateChildSize* PyInSize = NePyStructCheck_SlateChildSize(PyArgs[0]))
	{
		InSize = (FSlateChildSize*)PyInSize->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InSize' must have type 'SlateChildSize'");
		return nullptr;
	}

	InSelf->GetValue()->SetSize(*InSize);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_HorizontalBoxSlot_SetPadding(FNePyObject_HorizontalBoxSlot* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetPadding'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FMargin* InPadding;
	if (FNePyStruct_Margin* PyInPadding = NePyStructCheck_Margin(PyArgs[0]))
	{
		InPadding = (FMargin*)PyInPadding->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InPadding' must have type 'Margin'");
		return nullptr;
	}

	InSelf->GetValue()->SetPadding(*InPadding);
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_HorizontalBoxSlot_Class(PyObject* InSelf) {
	UClass* Class = UHorizontalBoxSlot::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_HorizontalBoxSlot_methods[] = {
	{"SetVerticalAlignment", NePyCFunctionCast(&FNePyObject_HorizontalBoxSlot_SetVerticalAlignment), METH_O, ""},
	{"SetHorizontalAlignment", NePyCFunctionCast(&FNePyObject_HorizontalBoxSlot_SetHorizontalAlignment), METH_O, ""},
	{"SetSize", NePyCFunctionCast(&FNePyObject_HorizontalBoxSlot_SetSize), METH_O, ""},
	{"SetPadding", NePyCFunctionCast(&FNePyObject_HorizontalBoxSlot_SetPadding), METH_O, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_HorizontalBoxSlot_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_HorizontalBoxSlot* NePyObjectNew_HorizontalBoxSlot(UHorizontalBoxSlot* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_HorizontalBoxSlot));
	FNePyObject_HorizontalBoxSlot* RetValue = (FNePyObject_HorizontalBoxSlot*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_HorizontalBoxSlot* NePyObjectCheck_HorizontalBoxSlot(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_HorizontalBoxSlot))
	{
		return (FNePyObject_HorizontalBoxSlot*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_HorizontalBoxSlot()
{
	return &FNePyObjectType_HorizontalBoxSlot;
}

PyTypeObject* NePyNePyWrappedClassInit_HorizontalBoxSlot(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_HorizontalBoxSlot;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_HorizontalBoxSlot_getset;
	NePyObjectType->tp_methods = FNePyObjectType_HorizontalBoxSlot_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_HorizontalBoxSlot,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_HorizontalBoxSlot(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UHorizontalBoxSlot::StaticClass(), NePyNePyWrappedClassInit_HorizontalBoxSlot);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UHorizontalBoxSlot*& OutVal)
	{
		if (FNePyObject_HorizontalBoxSlot* PyObj = NePyObjectCheck_HorizontalBoxSlot(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif