// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_RichTextBlockDecorator.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_RichTextBlockDecorator = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"RichTextBlockDecorator", /* tp_name */
	sizeof(FNePyObject_RichTextBlockDecorator), /* tp_basicsize */
};

static PyObject* FNePyObject_RichTextBlockDecorator_Class(PyObject* InSelf) {
	UClass* Class = URichTextBlockDecorator::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_RichTextBlockDecorator_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_RichTextBlockDecorator_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_RichTextBlockDecorator* NePyObjectNew_RichTextBlockDecorator(URichTextBlockDecorator* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_RichTextBlockDecorator));
	FNePyObject_RichTextBlockDecorator* RetValue = (FNePyObject_RichTextBlockDecorator*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_RichTextBlockDecorator* NePyObjectCheck_RichTextBlockDecorator(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_RichTextBlockDecorator))
	{
		return (FNePyObject_RichTextBlockDecorator*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_RichTextBlockDecorator()
{
	return &FNePyObjectType_RichTextBlockDecorator;
}

PyTypeObject* NePyNePyWrappedClassInit_RichTextBlockDecorator(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_RichTextBlockDecorator;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_RichTextBlockDecorator_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_RichTextBlockDecorator,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_RichTextBlockDecorator(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		URichTextBlockDecorator::StaticClass(), NePyNePyWrappedClassInit_RichTextBlockDecorator);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, URichTextBlockDecorator*& OutVal)
	{
		if (FNePyObject_RichTextBlockDecorator* PyObj = NePyObjectCheck_RichTextBlockDecorator(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif