// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_RichTextBlockImageDecorator.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_RichTextBlockImageDecorator = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"RichTextBlockImageDecorator", /* tp_name */
	sizeof(FNePyObject_RichTextBlockImageDecorator), /* tp_basicsize */
};

static PyObject* FNePyObject_RichTextBlockImageDecorator_Class(PyObject* InSelf) {
	UClass* Class = URichTextBlockImageDecorator::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_RichTextBlockImageDecorator_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_RichTextBlockImageDecorator_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_RichTextBlockImageDecorator* NePyObjectNew_RichTextBlockImageDecorator(URichTextBlockImageDecorator* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_RichTextBlockImageDecorator));
	FNePyObject_RichTextBlockImageDecorator* RetValue = (FNePyObject_RichTextBlockImageDecorator*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_RichTextBlockImageDecorator* NePyObjectCheck_RichTextBlockImageDecorator(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_RichTextBlockImageDecorator))
	{
		return (FNePyObject_RichTextBlockImageDecorator*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_RichTextBlockImageDecorator()
{
	return &FNePyObjectType_RichTextBlockImageDecorator;
}

PyTypeObject* NePyNePyWrappedClassInit_RichTextBlockImageDecorator(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_RichTextBlockImageDecorator;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_RichTextBlockImageDecorator_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_RichTextBlockImageDecorator,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_RichTextBlockImageDecorator(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		URichTextBlockImageDecorator::StaticClass(), NePyNePyWrappedClassInit_RichTextBlockImageDecorator);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, URichTextBlockImageDecorator*& OutVal)
	{
		if (FNePyObject_RichTextBlockImageDecorator* PyObj = NePyObjectCheck_RichTextBlockImageDecorator(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif