#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "Components/VerticalBox.h"
// region include end

class FNePyObject_VerticalBox : public FNePyObjectBase
{
public:
	inline UVerticalBox* GetValue()
	{
		return (UVerticalBox*)Value;
	}
};

void NePyInitObject_VerticalBox(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_VerticalBox* NePyObjectCheck_VerticalBox(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_VerticalBox();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UVerticalBox*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif