// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_Border.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/core/NePyStruct_LinearColor.h"
#include "NePyDynamicDelegateWrapper.h"
#include "NePy/Auto/slate/NePyStruct_Margin.h"
#include "NePy/Auto/slate/NePyStruct_SlateBrush.h"
#include "NePy/Auto/core/NePyStruct_Vector2D.h"
#include "NePy/Auto/engine/NePyObject_MaterialInstanceDynamic.h"
#include "NePy/Auto/engine/NePyObject_MaterialInterface.h"
#include "NePy/Auto/engine/NePyObject_Texture2D.h"
#include "NePy/Auto/engine/NePyObject_SlateBrushAsset.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_Border = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"Border", /* tp_name */
	sizeof(FNePyObject_Border), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_Border_Prop_GetHorizontalAlignment(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HorizontalAlignment'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->HorizontalAlignment);
	return RetValue;
}

int FNePyObject_Border_Prop_SetHorizontalAlignment(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HorizontalAlignment'"))
	{
		return -1;
	}

	TEnumAsByte<EHorizontalAlignment> TempValueForSetter;
	uint8 HorizontalAlignmentTemp;
	if (!NePyBase::ToCpp(InValue, HorizontalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EHorizontalAlignment)");
		return -1;
	}
	TempValueForSetter = (EHorizontalAlignment)HorizontalAlignmentTemp;
	InSelf->GetValue()->SetHorizontalAlignment(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetVerticalAlignment(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VerticalAlignment'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->VerticalAlignment);
	return RetValue;
}

int FNePyObject_Border_Prop_SetVerticalAlignment(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VerticalAlignment'"))
	{
		return -1;
	}

	TEnumAsByte<EVerticalAlignment> TempValueForSetter;
	uint8 VerticalAlignmentTemp;
	if (!NePyBase::ToCpp(InValue, VerticalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EVerticalAlignment)");
		return -1;
	}
	TempValueForSetter = (EVerticalAlignment)VerticalAlignmentTemp;
	InSelf->GetValue()->SetVerticalAlignment(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetbShowEffectWhenDisabled(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bShowEffectWhenDisabled'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bShowEffectWhenDisabled);
	return RetValue;
}

int FNePyObject_Border_Prop_SetbShowEffectWhenDisabled(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bShowEffectWhenDisabled'"))
	{
		return -1;
	}

	bool TempValueForSetter;
	bool bShowEffectWhenDisabledTemp;
	if (!NePyBase::ToCpp(InValue, bShowEffectWhenDisabledTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	TempValueForSetter = bShowEffectWhenDisabledTemp;
	InSelf->GetValue()->SetShowEffectWhenDisabled(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetContentColorAndOpacity(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ContentColorAndOpacity'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_LinearColor(InSelf->GetValue()->ContentColorAndOpacity);
	return RetValue;
}

int FNePyObject_Border_Prop_SetContentColorAndOpacity(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ContentColorAndOpacity'"))
	{
		return -1;
	}

	FLinearColor TempValueForSetter;
	if (FNePyStruct_LinearColor* PyContentColorAndOpacity = NePyStructCheck_LinearColor(InValue))
	{
		TempValueForSetter = *((FLinearColor*)PyContentColorAndOpacity->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'LinearColor'");
		return -1;
	}
	InSelf->GetValue()->SetContentColorAndOpacity(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetContentColorAndOpacityDelegate(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ContentColorAndOpacityDelegate'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->ContentColorAndOpacityDelegate, "ContentColorAndOpacityDelegate");
	return RetValue;
}

PyObject* FNePyObject_Border_Prop_GetPadding(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Padding'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Margin(InSelf->GetValue()->Padding);
	return RetValue;
}

int FNePyObject_Border_Prop_SetPadding(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Padding'"))
	{
		return -1;
	}

	FMargin TempValueForSetter;
	if (FNePyStruct_Margin* PyPadding = NePyStructCheck_Margin(InValue))
	{
		TempValueForSetter = *((FMargin*)PyPadding->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Margin'");
		return -1;
	}
	InSelf->GetValue()->SetPadding(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetBackground(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Background'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_SlateBrush(InSelf->GetValue()->Background);
	return RetValue;
}

int FNePyObject_Border_Prop_SetBackground(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Background'"))
	{
		return -1;
	}

	if (FNePyStruct_SlateBrush* PyBackground = NePyStructCheck_SlateBrush(InValue))
	{
		InSelf->GetValue()->Background = *((FSlateBrush*)PyBackground->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'SlateBrush'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetBackgroundDelegate(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'BackgroundDelegate'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->BackgroundDelegate, "BackgroundDelegate");
	return RetValue;
}

PyObject* FNePyObject_Border_Prop_GetBrushColor(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'BrushColor'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_LinearColor(InSelf->GetValue()->BrushColor);
	return RetValue;
}

int FNePyObject_Border_Prop_SetBrushColor(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'BrushColor'"))
	{
		return -1;
	}

	FLinearColor TempValueForSetter;
	if (FNePyStruct_LinearColor* PyBrushColor = NePyStructCheck_LinearColor(InValue))
	{
		TempValueForSetter = *((FLinearColor*)PyBrushColor->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'LinearColor'");
		return -1;
	}
	InSelf->GetValue()->SetBrushColor(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetBrushColorDelegate(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'BrushColorDelegate'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->BrushColorDelegate, "BrushColorDelegate");
	return RetValue;
}

PyObject* FNePyObject_Border_Prop_GetDesiredSizeScale(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DesiredSizeScale'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Vector2D(InSelf->GetValue()->DesiredSizeScale);
	return RetValue;
}

int FNePyObject_Border_Prop_SetDesiredSizeScale(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DesiredSizeScale'"))
	{
		return -1;
	}

	FVector2D TempValueForSetter;
	if (FNePyStruct_Vector2D* PyDesiredSizeScale = NePyStructCheck_Vector2D(InValue))
	{
		TempValueForSetter = *((FVector2D*)PyDesiredSizeScale->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector2D'");
		return -1;
	}
	InSelf->GetValue()->SetDesiredSizeScale(TempValueForSetter);
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetbFlipForRightToLeftFlowDirection(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bFlipForRightToLeftFlowDirection'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bFlipForRightToLeftFlowDirection);
	return RetValue;
}

int FNePyObject_Border_Prop_SetbFlipForRightToLeftFlowDirection(FNePyObject_Border* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bFlipForRightToLeftFlowDirection'"))
	{
		return -1;
	}

	bool bFlipForRightToLeftFlowDirectionTemp;
	if (!NePyBase::ToCpp(InValue, bFlipForRightToLeftFlowDirectionTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bFlipForRightToLeftFlowDirection = bFlipForRightToLeftFlowDirectionTemp;
	return 0;
}

PyObject* FNePyObject_Border_Prop_GetOnMouseButtonDownEvent(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'OnMouseButtonDownEvent'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->OnMouseButtonDownEvent, "OnMouseButtonDownEvent");
	return RetValue;
}

PyObject* FNePyObject_Border_Prop_GetOnMouseButtonUpEvent(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'OnMouseButtonUpEvent'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->OnMouseButtonUpEvent, "OnMouseButtonUpEvent");
	return RetValue;
}

PyObject* FNePyObject_Border_Prop_GetOnMouseMoveEvent(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'OnMouseMoveEvent'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->OnMouseMoveEvent, "OnMouseMoveEvent");
	return RetValue;
}

PyObject* FNePyObject_Border_Prop_GetOnMouseDoubleClickEvent(FNePyObject_Border* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'OnMouseDoubleClickEvent'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyDynamicDelegateWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->OnMouseDoubleClickEvent, "OnMouseDoubleClickEvent");
	return RetValue;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_Border_getset[] = {
	{ (char*)"HorizontalAlignment", (getter)FNePyObject_Border_Prop_GetHorizontalAlignment, (setter)FNePyObject_Border_Prop_SetHorizontalAlignment, nullptr, nullptr },
	{ (char*)"VerticalAlignment", (getter)FNePyObject_Border_Prop_GetVerticalAlignment, (setter)FNePyObject_Border_Prop_SetVerticalAlignment, nullptr, nullptr },
	{ (char*)"bShowEffectWhenDisabled", (getter)FNePyObject_Border_Prop_GetbShowEffectWhenDisabled, (setter)FNePyObject_Border_Prop_SetbShowEffectWhenDisabled, nullptr, nullptr },
	{ (char*)"ContentColorAndOpacity", (getter)FNePyObject_Border_Prop_GetContentColorAndOpacity, (setter)FNePyObject_Border_Prop_SetContentColorAndOpacity, nullptr, nullptr },
	{ (char*)"ContentColorAndOpacityDelegate", (getter)FNePyObject_Border_Prop_GetContentColorAndOpacityDelegate, nullptr, nullptr, nullptr },
	{ (char*)"Padding", (getter)FNePyObject_Border_Prop_GetPadding, (setter)FNePyObject_Border_Prop_SetPadding, nullptr, nullptr },
	{ (char*)"Background", (getter)FNePyObject_Border_Prop_GetBackground, (setter)FNePyObject_Border_Prop_SetBackground, nullptr, nullptr },
	{ (char*)"BackgroundDelegate", (getter)FNePyObject_Border_Prop_GetBackgroundDelegate, nullptr, nullptr, nullptr },
	{ (char*)"BrushColor", (getter)FNePyObject_Border_Prop_GetBrushColor, (setter)FNePyObject_Border_Prop_SetBrushColor, nullptr, nullptr },
	{ (char*)"BrushColorDelegate", (getter)FNePyObject_Border_Prop_GetBrushColorDelegate, nullptr, nullptr, nullptr },
	{ (char*)"DesiredSizeScale", (getter)FNePyObject_Border_Prop_GetDesiredSizeScale, (setter)FNePyObject_Border_Prop_SetDesiredSizeScale, nullptr, nullptr },
	{ (char*)"bFlipForRightToLeftFlowDirection", (getter)FNePyObject_Border_Prop_GetbFlipForRightToLeftFlowDirection, (setter)FNePyObject_Border_Prop_SetbFlipForRightToLeftFlowDirection, nullptr, nullptr },
	{ (char*)"OnMouseButtonDownEvent", (getter)FNePyObject_Border_Prop_GetOnMouseButtonDownEvent, nullptr, nullptr, nullptr },
	{ (char*)"OnMouseButtonUpEvent", (getter)FNePyObject_Border_Prop_GetOnMouseButtonUpEvent, nullptr, nullptr, nullptr },
	{ (char*)"OnMouseMoveEvent", (getter)FNePyObject_Border_Prop_GetOnMouseMoveEvent, nullptr, nullptr, nullptr },
	{ (char*)"OnMouseDoubleClickEvent", (getter)FNePyObject_Border_Prop_GetOnMouseDoubleClickEvent, nullptr, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_Border_SetDesiredSizeScale(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetDesiredSizeScale'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FVector2D* InScale;
	if (FNePyStruct_Vector2D* PyInScale = NePyStructCheck_Vector2D(PyArgs[0]))
	{
		InScale = (FVector2D*)PyInScale->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InScale' must have type 'Vector2D'");
		return nullptr;
	}

	InSelf->GetValue()->SetDesiredSizeScale(*InScale);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_GetDynamicMaterial(FNePyObject_Border* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetDynamicMaterial'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetDynamicMaterial();

	PyObject* PyRetVal0 = NePyBase::ToPy(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_Border_SetShowEffectWhenDisabled(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetShowEffectWhenDisabled'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	bool bInShowEffectWhenDisabled;
	if (!NePyBase::ToCpp(PyArgs[0], bInShowEffectWhenDisabled))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'bInShowEffectWhenDisabled' must have type 'bool'");
		return nullptr;
	}

	InSelf->GetValue()->SetShowEffectWhenDisabled(bInShowEffectWhenDisabled);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetBrushFromMaterial(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetBrushFromMaterial'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	UMaterialInterface* Material;
	if (PyArgs[0] == Py_None)
	{
		Material = nullptr;
	}
	else if (FNePyObject_MaterialInterface* PyMaterial = NePyObjectCheck_MaterialInterface(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyMaterial))
		{
			Material = PyMaterial->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Material' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Material' must have type 'MaterialInterface'");
		return nullptr;
	}

	InSelf->GetValue()->SetBrushFromMaterial(Material);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetBrushFromTexture(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetBrushFromTexture'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	UTexture2D* Texture;
	if (PyArgs[0] == Py_None)
	{
		Texture = nullptr;
	}
	else if (FNePyObject_Texture2D* PyTexture = NePyObjectCheck_Texture2D(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTexture))
		{
			Texture = PyTexture->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Texture' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Texture' must have type 'Texture2D'");
		return nullptr;
	}

	InSelf->GetValue()->SetBrushFromTexture(Texture);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetBrushFromAsset(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetBrushFromAsset'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	USlateBrushAsset* Asset;
	if (PyArgs[0] == Py_None)
	{
		Asset = nullptr;
	}
	else if (FNePyObject_SlateBrushAsset* PyAsset = NePyObjectCheck_SlateBrushAsset(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyAsset))
		{
			Asset = PyAsset->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Asset' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Asset' must have type 'SlateBrushAsset'");
		return nullptr;
	}

	InSelf->GetValue()->SetBrushFromAsset(Asset);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetBrush(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetBrush'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FSlateBrush* InBrush;
	if (FNePyStruct_SlateBrush* PyInBrush = NePyStructCheck_SlateBrush(PyArgs[0]))
	{
		InBrush = (FSlateBrush*)PyInBrush->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InBrush' must have type 'SlateBrush'");
		return nullptr;
	}

	InSelf->GetValue()->SetBrush(*InBrush);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetBrushColor(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetBrushColor'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FLinearColor* InBrushColor;
	if (FNePyStruct_LinearColor* PyInBrushColor = NePyStructCheck_LinearColor(PyArgs[0]))
	{
		InBrushColor = (FLinearColor*)PyInBrushColor->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InBrushColor' must have type 'LinearColor'");
		return nullptr;
	}

	InSelf->GetValue()->SetBrushColor(*InBrushColor);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetVerticalAlignment(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetVerticalAlignment'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 InVerticalAlignmentTemp;
	if (!NePyBase::ToCpp(PyArgs[0], InVerticalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InVerticalAlignment' must have type 'int'(EVerticalAlignment)");
		return nullptr;
	}
	EVerticalAlignment InVerticalAlignment = (EVerticalAlignment)InVerticalAlignmentTemp;

	InSelf->GetValue()->SetVerticalAlignment(InVerticalAlignment);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetHorizontalAlignment(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetHorizontalAlignment'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 InHorizontalAlignmentTemp;
	if (!NePyBase::ToCpp(PyArgs[0], InHorizontalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InHorizontalAlignment' must have type 'int'(EHorizontalAlignment)");
		return nullptr;
	}
	EHorizontalAlignment InHorizontalAlignment = (EHorizontalAlignment)InHorizontalAlignmentTemp;

	InSelf->GetValue()->SetHorizontalAlignment(InHorizontalAlignment);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetPadding(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetPadding'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FMargin* InPadding;
	if (FNePyStruct_Margin* PyInPadding = NePyStructCheck_Margin(PyArgs[0]))
	{
		InPadding = (FMargin*)PyInPadding->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InPadding' must have type 'Margin'");
		return nullptr;
	}

	InSelf->GetValue()->SetPadding(*InPadding);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_Border_SetContentColorAndOpacity(FNePyObject_Border* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetContentColorAndOpacity'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FLinearColor* InContentColorAndOpacity;
	if (FNePyStruct_LinearColor* PyInContentColorAndOpacity = NePyStructCheck_LinearColor(PyArgs[0]))
	{
		InContentColorAndOpacity = (FLinearColor*)PyInContentColorAndOpacity->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InContentColorAndOpacity' must have type 'LinearColor'");
		return nullptr;
	}

	InSelf->GetValue()->SetContentColorAndOpacity(*InContentColorAndOpacity);
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_Border_Class(PyObject* InSelf) {
	UClass* Class = UBorder::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_Border_methods[] = {
	{"SetDesiredSizeScale", NePyCFunctionCast(&FNePyObject_Border_SetDesiredSizeScale), METH_O, ""},
	{"GetDynamicMaterial", NePyCFunctionCast(&FNePyObject_Border_GetDynamicMaterial), METH_NOARGS, ""},
	{"SetShowEffectWhenDisabled", NePyCFunctionCast(&FNePyObject_Border_SetShowEffectWhenDisabled), METH_O, ""},
	{"SetBrushFromMaterial", NePyCFunctionCast(&FNePyObject_Border_SetBrushFromMaterial), METH_O, ""},
	{"SetBrushFromTexture", NePyCFunctionCast(&FNePyObject_Border_SetBrushFromTexture), METH_O, ""},
	{"SetBrushFromAsset", NePyCFunctionCast(&FNePyObject_Border_SetBrushFromAsset), METH_O, ""},
	{"SetBrush", NePyCFunctionCast(&FNePyObject_Border_SetBrush), METH_O, ""},
	{"SetBrushColor", NePyCFunctionCast(&FNePyObject_Border_SetBrushColor), METH_O, ""},
	{"SetVerticalAlignment", NePyCFunctionCast(&FNePyObject_Border_SetVerticalAlignment), METH_O, ""},
	{"SetHorizontalAlignment", NePyCFunctionCast(&FNePyObject_Border_SetHorizontalAlignment), METH_O, ""},
	{"SetPadding", NePyCFunctionCast(&FNePyObject_Border_SetPadding), METH_O, ""},
	{"SetContentColorAndOpacity", NePyCFunctionCast(&FNePyObject_Border_SetContentColorAndOpacity), METH_O, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_Border_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_Border* NePyObjectNew_Border(UBorder* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_Border));
	FNePyObject_Border* RetValue = (FNePyObject_Border*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_Border* NePyObjectCheck_Border(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_Border))
	{
		return (FNePyObject_Border*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_Border()
{
	return &FNePyObjectType_Border;
}

PyTypeObject* NePyNePyWrappedClassInit_Border(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_Border;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_Border_getset;
	NePyObjectType->tp_methods = FNePyObjectType_Border_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_Border,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_Border(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UBorder::StaticClass(), NePyNePyWrappedClassInit_Border);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UBorder*& OutVal)
	{
		if (FNePyObject_Border* PyObj = NePyObjectCheck_Border(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif