// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_ScaleBoxSlot.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_ScaleBoxSlot = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"ScaleBoxSlot", /* tp_name */
	sizeof(FNePyObject_ScaleBoxSlot), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_ScaleBoxSlot_Prop_GetHorizontalAlignment(FNePyObject_ScaleBoxSlot* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HorizontalAlignment'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->HorizontalAlignment);
	return RetValue;
}

int FNePyObject_ScaleBoxSlot_Prop_SetHorizontalAlignment(FNePyObject_ScaleBoxSlot* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HorizontalAlignment'"))
	{
		return -1;
	}

	uint8 HorizontalAlignmentTemp;
	if (!NePyBase::ToCpp(InValue, HorizontalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EHorizontalAlignment)");
		return -1;
	}
	InSelf->GetValue()->HorizontalAlignment = (EHorizontalAlignment)HorizontalAlignmentTemp;
	return 0;
}

PyObject* FNePyObject_ScaleBoxSlot_Prop_GetVerticalAlignment(FNePyObject_ScaleBoxSlot* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VerticalAlignment'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->VerticalAlignment);
	return RetValue;
}

int FNePyObject_ScaleBoxSlot_Prop_SetVerticalAlignment(FNePyObject_ScaleBoxSlot* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VerticalAlignment'"))
	{
		return -1;
	}

	uint8 VerticalAlignmentTemp;
	if (!NePyBase::ToCpp(InValue, VerticalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EVerticalAlignment)");
		return -1;
	}
	InSelf->GetValue()->VerticalAlignment = (EVerticalAlignment)VerticalAlignmentTemp;
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_ScaleBoxSlot_getset[] = {
	{ (char*)"HorizontalAlignment", (getter)FNePyObject_ScaleBoxSlot_Prop_GetHorizontalAlignment, (setter)FNePyObject_ScaleBoxSlot_Prop_SetHorizontalAlignment, nullptr, nullptr },
	{ (char*)"VerticalAlignment", (getter)FNePyObject_ScaleBoxSlot_Prop_GetVerticalAlignment, (setter)FNePyObject_ScaleBoxSlot_Prop_SetVerticalAlignment, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_ScaleBoxSlot_SetVerticalAlignment(FNePyObject_ScaleBoxSlot* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetVerticalAlignment'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 InVerticalAlignmentTemp;
	if (!NePyBase::ToCpp(PyArgs[0], InVerticalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InVerticalAlignment' must have type 'int'(EVerticalAlignment)");
		return nullptr;
	}
	EVerticalAlignment InVerticalAlignment = (EVerticalAlignment)InVerticalAlignmentTemp;

	InSelf->GetValue()->SetVerticalAlignment(InVerticalAlignment);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_ScaleBoxSlot_SetHorizontalAlignment(FNePyObject_ScaleBoxSlot* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetHorizontalAlignment'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 InHorizontalAlignmentTemp;
	if (!NePyBase::ToCpp(PyArgs[0], InHorizontalAlignmentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InHorizontalAlignment' must have type 'int'(EHorizontalAlignment)");
		return nullptr;
	}
	EHorizontalAlignment InHorizontalAlignment = (EHorizontalAlignment)InHorizontalAlignmentTemp;

	InSelf->GetValue()->SetHorizontalAlignment(InHorizontalAlignment);
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_ScaleBoxSlot_Class(PyObject* InSelf) {
	UClass* Class = UScaleBoxSlot::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_ScaleBoxSlot_methods[] = {
	{"SetVerticalAlignment", NePyCFunctionCast(&FNePyObject_ScaleBoxSlot_SetVerticalAlignment), METH_O, ""},
	{"SetHorizontalAlignment", NePyCFunctionCast(&FNePyObject_ScaleBoxSlot_SetHorizontalAlignment), METH_O, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_ScaleBoxSlot_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_ScaleBoxSlot* NePyObjectNew_ScaleBoxSlot(UScaleBoxSlot* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_ScaleBoxSlot));
	FNePyObject_ScaleBoxSlot* RetValue = (FNePyObject_ScaleBoxSlot*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_ScaleBoxSlot* NePyObjectCheck_ScaleBoxSlot(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_ScaleBoxSlot))
	{
		return (FNePyObject_ScaleBoxSlot*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_ScaleBoxSlot()
{
	return &FNePyObjectType_ScaleBoxSlot;
}

PyTypeObject* NePyNePyWrappedClassInit_ScaleBoxSlot(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_ScaleBoxSlot;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_ScaleBoxSlot_getset;
	NePyObjectType->tp_methods = FNePyObjectType_ScaleBoxSlot_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_ScaleBoxSlot,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_ScaleBoxSlot(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UScaleBoxSlot::StaticClass(), NePyNePyWrappedClassInit_ScaleBoxSlot);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UScaleBoxSlot*& OutVal)
	{
		if (FNePyObject_ScaleBoxSlot* PyObj = NePyObjectCheck_ScaleBoxSlot(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif