// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_GameplayModMagnitudeCalculation.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/gas/NePyStruct_GameplayEffectSpec.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_GameplayModMagnitudeCalculation = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"GameplayModMagnitudeCalculation", /* tp_name */
	sizeof(FNePyObject_GameplayModMagnitudeCalculation), /* tp_basicsize */
};

// region func body begin
PyObject* FNePyObject_GameplayModMagnitudeCalculation_CalculateBaseMagnitude(FNePyObject_GameplayModMagnitudeCalculation* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'CalculateBaseMagnitude'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FGameplayEffectSpec* Spec;
	if (FNePyStruct_GameplayEffectSpec* PySpec = NePyStructCheck_GameplayEffectSpec(PyArgs[0]))
	{
		Spec = (FGameplayEffectSpec*)PySpec->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Spec' must have type 'GameplayEffectSpec'");
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->CalculateBaseMagnitude_Implementation(*Spec);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}
// region func body end

static PyObject* FNePyObject_GameplayModMagnitudeCalculation_Class(PyObject* InSelf) {
	UClass* Class = UGameplayModMagnitudeCalculation::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_GameplayModMagnitudeCalculation_methods[] = {
	{"CalculateBaseMagnitude", NePyCFunctionCast(&FNePyObject_GameplayModMagnitudeCalculation_CalculateBaseMagnitude), METH_O, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_GameplayModMagnitudeCalculation_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_GameplayModMagnitudeCalculation* NePyObjectNew_GameplayModMagnitudeCalculation(UGameplayModMagnitudeCalculation* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_GameplayModMagnitudeCalculation));
	FNePyObject_GameplayModMagnitudeCalculation* RetValue = (FNePyObject_GameplayModMagnitudeCalculation*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_GameplayModMagnitudeCalculation* NePyObjectCheck_GameplayModMagnitudeCalculation(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_GameplayModMagnitudeCalculation))
	{
		return (FNePyObject_GameplayModMagnitudeCalculation*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_GameplayModMagnitudeCalculation()
{
	return &FNePyObjectType_GameplayModMagnitudeCalculation;
}

PyTypeObject* NePyNePyWrappedClassInit_GameplayModMagnitudeCalculation(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_GameplayModMagnitudeCalculation;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_GameplayModMagnitudeCalculation_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_GameplayModMagnitudeCalculation,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_GameplayModMagnitudeCalculation(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UGameplayModMagnitudeCalculation::StaticClass(), NePyNePyWrappedClassInit_GameplayModMagnitudeCalculation);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UGameplayModMagnitudeCalculation*& OutVal)
	{
		if (FNePyObject_GameplayModMagnitudeCalculation* PyObj = NePyObjectCheck_GameplayModMagnitudeCalculation(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif