#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "GameplayEffectTypes.h"
// region include end

struct FNePyStruct_GameplayCueParameters : public TNePyStructBase<FGameplayCueParameters>
{
};

void NePyInitStruct_GameplayCueParameters(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_GameplayCueParameters* NePyStructNew_GameplayCueParameters(const FGameplayCueParameters& InValue);

NEPYTHONBINDING_API FNePyStruct_GameplayCueParameters* NePyStructCheck_GameplayCueParameters(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_GameplayCueParameters();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FGameplayCueParameters& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FGameplayCueParameters& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif