// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "${header_name}"
${child_include_list_cpp}

void ${init_func_name}(PyObject* PyOuterModule)
{
${with_editor_begin}
	PyObject* PyModule = PyOuterModule;

	// region child init begin
	${child_init_list}
	// region child init end
${with_editor_end}
}
