// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_SoundModulationDestinationSettings.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePySetWrapper.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_SoundModulationDestinationSettings = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"SoundModulationDestinationSettings", /* tp_name */
	sizeof(FNePyStruct_SoundModulationDestinationSettings), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_SoundModulationDestinationSettings_GetValue(FNePyStruct_SoundModulationDestinationSettings* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FSoundModulationDestinationSettings*)InSelf->Value)->Value);
	return RetValue;
}

int FNePyStruct_SoundModulationDestinationSettings_SetValue(FNePyStruct_SoundModulationDestinationSettings* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FSoundModulationDestinationSettings*)InSelf->Value)->Value))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_SoundModulationDestinationSettings_GetModulators(FNePyStruct_SoundModulationDestinationSettings* InSelf, void* InClosure)
{
	PyObject* RetValue = FNePyStructSetWrapper::New(InSelf, TBaseStructure<FSoundModulationDestinationSettings>::Get(), InSelf->Value, &((FSoundModulationDestinationSettings*)InSelf->Value)->Modulators, "Modulators");
	return RetValue;
}

int FNePyStruct_SoundModulationDestinationSettings_SetModulators(FNePyStruct_SoundModulationDestinationSettings* InSelf, PyObject* InValue, void* InClosure)
{
	if (!FNePySetWrapper::Assign(InValue, TBaseStructure<FSoundModulationDestinationSettings>::Get(), InSelf->Value, &((FSoundModulationDestinationSettings*)InSelf->Value)->Modulators, "Modulators"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'set(SoundModulatorBase)'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_SoundModulationDestinationSettings_getset[] = {
	{ (char*)"Value", (getter)FNePyStruct_SoundModulationDestinationSettings_GetValue, (setter)FNePyStruct_SoundModulationDestinationSettings_SetValue, nullptr, nullptr },
	{ (char*)"Modulators", (getter)FNePyStruct_SoundModulationDestinationSettings_GetModulators, (setter)FNePyStruct_SoundModulationDestinationSettings_SetModulators, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_SoundModulationDestinationSettings(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_SoundModulationDestinationSettings* PyObj = NePyStructCheck_SoundModulationDestinationSettings(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_SoundModulationDestinationSettings(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_SoundModulationDestinationSettings;
	FNePyStruct_SoundModulationDestinationSettings* PyObj = (FNePyStruct_SoundModulationDestinationSettings*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FSoundModulationDestinationSettings*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FSoundModulationDestinationSettings*)FMemory::Malloc(sizeof(FSoundModulationDestinationSettings), alignof(FSoundModulationDestinationSettings));
	NePyBase::EnsureCopyToStructSafely<FSoundModulationDestinationSettings>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_SoundModulationDestinationSettings(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_SoundModulationDestinationSettings;
	TNePyStructBase<FSoundModulationDestinationSettings>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_SoundModulationDestinationSettings_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_SoundModulationDestinationSettings,
			(NePyStructPropGet)NePyStructPropGet_SoundModulationDestinationSettings,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_SoundModulationDestinationSettings(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FSoundModulationDestinationSettings>::Get(), NePyNePyWrappedStructInit_SoundModulationDestinationSettings);
}

FNePyStruct_SoundModulationDestinationSettings* NePyStructNew_SoundModulationDestinationSettings(const FSoundModulationDestinationSettings& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_SoundModulationDestinationSettings;
	FNePyStruct_SoundModulationDestinationSettings* RetValue = (FNePyStruct_SoundModulationDestinationSettings*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_SoundModulationDestinationSettings::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FSoundModulationDestinationSettings(InValue);
	return RetValue;
}

FNePyStruct_SoundModulationDestinationSettings* NePyStructCheck_SoundModulationDestinationSettings(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_SoundModulationDestinationSettings))
	{
		return (FNePyStruct_SoundModulationDestinationSettings*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_SoundModulationDestinationSettings()
{
	return &FNePyStructType_SoundModulationDestinationSettings;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FSoundModulationDestinationSettings& OutVal)
	{
		if (FNePyStruct_SoundModulationDestinationSettings* PyObj = NePyStructCheck_SoundModulationDestinationSettings(InPyObj))
		{
			OutVal = *(FSoundModulationDestinationSettings*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FSoundModulationDestinationSettings& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_SoundModulationDestinationSettings(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif