#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Animation/AnimData/AnimDataNotifications.h"
// region include end

struct FNePyStruct_BracketPayload : public TNePyStructBase<FBracketPayload>
{
};

void NePyInitStruct_BracketPayload(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_BracketPayload* NePyStructNew_BracketPayload(const FBracketPayload& InValue);

NEPYTHONBINDING_API FNePyStruct_BracketPayload* NePyStructCheck_BracketPayload(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_BracketPayload();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FBracketPayload& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FBracketPayload& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif