// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_AmbientSound.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_AmbientSound = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"AmbientSound", /* tp_name */
	sizeof(FNePyObject_AmbientSound), /* tp_basicsize */
};

static PyObject* FNePyObject_AmbientSound_Class(PyObject* InSelf) {
	UClass* Class = AAmbientSound::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_AmbientSound_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_AmbientSound_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_AmbientSound* NePyObjectNew_AmbientSound(AAmbientSound* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_AmbientSound));
	FNePyObject_AmbientSound* RetValue = (FNePyObject_AmbientSound*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_AmbientSound* NePyObjectCheck_AmbientSound(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_AmbientSound))
	{
		return (FNePyObject_AmbientSound*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_AmbientSound()
{
	return &FNePyObjectType_AmbientSound;
}

PyTypeObject* NePyNePyWrappedClassInit_AmbientSound(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_AmbientSound;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_AmbientSound_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_AmbientSound,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_AmbientSound(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		AAmbientSound::StaticClass(), NePyNePyWrappedClassInit_AmbientSound);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, AAmbientSound*& OutVal)
	{
		if (FNePyObject_AmbientSound* PyObj = NePyObjectCheck_AmbientSound(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif