// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_SceneCaptureComponent2D.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_TextureRenderTarget2D.h"
#include "NePy/Auto/engine/NePyStruct_PostProcessSettings.h"
#include "NePy/Auto/core/NePyStruct_Matrix.h"
#include "NePy/Auto/core/NePyStruct_Vector.h"
#include "NePy/Auto/core/NePyStruct_IntPoint.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_SceneCaptureComponent2D = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"SceneCaptureComponent2D", /* tp_name */
	sizeof(FNePyObject_SceneCaptureComponent2D), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetProjectionType(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ProjectionType'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->ProjectionType);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetProjectionType(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ProjectionType'"))
	{
		return -1;
	}

	uint8 ProjectionTypeTemp;
	if (!NePyBase::ToCpp(InValue, ProjectionTypeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(ECameraProjectionMode)");
		return -1;
	}
	InSelf->GetValue()->ProjectionType = (ECameraProjectionMode::Type)ProjectionTypeTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetFOVAngle(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FOVAngle'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->FOVAngle);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetFOVAngle(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FOVAngle'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->FOVAngle))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetFirstPersonFieldOfView(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FirstPersonFieldOfView'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->FirstPersonFieldOfView);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetFirstPersonFieldOfView(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FirstPersonFieldOfView'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->FirstPersonFieldOfView))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetFirstPersonScale(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FirstPersonScale'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->FirstPersonScale);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetFirstPersonScale(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FirstPersonScale'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->FirstPersonScale))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetOrthoWidth(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'OrthoWidth'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->OrthoWidth);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetOrthoWidth(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'OrthoWidth'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->OrthoWidth))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbAutoCalculateOrthoPlanes(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bAutoCalculateOrthoPlanes'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bAutoCalculateOrthoPlanes);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbAutoCalculateOrthoPlanes(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bAutoCalculateOrthoPlanes'"))
	{
		return -1;
	}

	bool bAutoCalculateOrthoPlanesTemp;
	if (!NePyBase::ToCpp(InValue, bAutoCalculateOrthoPlanesTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bAutoCalculateOrthoPlanes = bAutoCalculateOrthoPlanesTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetAutoPlaneShift(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'AutoPlaneShift'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->AutoPlaneShift);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetAutoPlaneShift(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'AutoPlaneShift'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->AutoPlaneShift))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbUpdateOrthoPlanes(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bUpdateOrthoPlanes'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bUpdateOrthoPlanes);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbUpdateOrthoPlanes(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bUpdateOrthoPlanes'"))
	{
		return -1;
	}

	bool bUpdateOrthoPlanesTemp;
	if (!NePyBase::ToCpp(InValue, bUpdateOrthoPlanesTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bUpdateOrthoPlanes = bUpdateOrthoPlanesTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbUseCameraHeightAsViewTarget(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bUseCameraHeightAsViewTarget'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bUseCameraHeightAsViewTarget);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbUseCameraHeightAsViewTarget(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bUseCameraHeightAsViewTarget'"))
	{
		return -1;
	}

	bool bUseCameraHeightAsViewTargetTemp;
	if (!NePyBase::ToCpp(InValue, bUseCameraHeightAsViewTargetTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bUseCameraHeightAsViewTarget = bUseCameraHeightAsViewTargetTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetOverscan(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Overscan'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->Overscan);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetOverscan(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Overscan'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->Overscan))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetTextureTarget(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'TextureTarget'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyBase::ToPy(InSelf->GetValue()->TextureTarget);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetTextureTarget(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'TextureTarget'"))
	{
		return -1;
	}

	if (InValue == Py_None)
	{
		InSelf->GetValue()->TextureTarget = nullptr;
	}
	else if (FNePyObject_TextureRenderTarget2D* PyTextureTarget = NePyObjectCheck_TextureRenderTarget2D(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTextureTarget))
		{
			InSelf->GetValue()->TextureTarget = PyTextureTarget->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'TextureRenderTarget2D'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetCompositeMode(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'CompositeMode'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->CompositeMode);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetCompositeMode(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'CompositeMode'"))
	{
		return -1;
	}

	uint8 CompositeModeTemp;
	if (!NePyBase::ToCpp(InValue, CompositeModeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(ESceneCaptureCompositeMode)");
		return -1;
	}
	InSelf->GetValue()->CompositeMode = (ESceneCaptureCompositeMode)CompositeModeTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetPostProcessSettings(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'PostProcessSettings'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_PostProcessSettings(InSelf->GetValue()->PostProcessSettings);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetPostProcessSettings(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'PostProcessSettings'"))
	{
		return -1;
	}

	if (FNePyStruct_PostProcessSettings* PyPostProcessSettings = NePyStructCheck_PostProcessSettings(InValue))
	{
		InSelf->GetValue()->PostProcessSettings = *((FPostProcessSettings*)PyPostProcessSettings->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'PostProcessSettings'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetPostProcessBlendWeight(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'PostProcessBlendWeight'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->PostProcessBlendWeight);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetPostProcessBlendWeight(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'PostProcessBlendWeight'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->PostProcessBlendWeight))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbOverride_CustomNearClippingPlane(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bOverride_CustomNearClippingPlane'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bOverride_CustomNearClippingPlane);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbOverride_CustomNearClippingPlane(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bOverride_CustomNearClippingPlane'"))
	{
		return -1;
	}

	bool bOverride_CustomNearClippingPlaneTemp;
	if (!NePyBase::ToCpp(InValue, bOverride_CustomNearClippingPlaneTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bOverride_CustomNearClippingPlane = bOverride_CustomNearClippingPlaneTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetCustomNearClippingPlane(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'CustomNearClippingPlane'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->CustomNearClippingPlane);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetCustomNearClippingPlane(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'CustomNearClippingPlane'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->CustomNearClippingPlane))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbUseCustomProjectionMatrix(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bUseCustomProjectionMatrix'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bUseCustomProjectionMatrix);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbUseCustomProjectionMatrix(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bUseCustomProjectionMatrix'"))
	{
		return -1;
	}

	bool bUseCustomProjectionMatrixTemp;
	if (!NePyBase::ToCpp(InValue, bUseCustomProjectionMatrixTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bUseCustomProjectionMatrix = bUseCustomProjectionMatrixTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetCustomProjectionMatrix(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'CustomProjectionMatrix'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Matrix(InSelf->GetValue()->CustomProjectionMatrix);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetCustomProjectionMatrix(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'CustomProjectionMatrix'"))
	{
		return -1;
	}

	if (FNePyStruct_Matrix* PyCustomProjectionMatrix = NePyStructCheck_Matrix(InValue))
	{
		InSelf->GetValue()->CustomProjectionMatrix = *((FMatrix*)PyCustomProjectionMatrix->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Matrix'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableOrthographicTiling(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableOrthographicTiling'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bEnableOrthographicTiling);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableOrthographicTiling(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableOrthographicTiling'"))
	{
		return -1;
	}

	bool bEnableOrthographicTilingTemp;
	if (!NePyBase::ToCpp(InValue, bEnableOrthographicTilingTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bEnableOrthographicTiling = bEnableOrthographicTilingTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetNumXTiles(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'NumXTiles'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromLong(InSelf->GetValue()->NumXTiles);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetNumXTiles(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'NumXTiles'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->NumXTiles))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetNumYTiles(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'NumYTiles'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromLong(InSelf->GetValue()->NumYTiles);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetNumYTiles(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'NumYTiles'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->NumYTiles))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableClipPlane(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableClipPlane'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bEnableClipPlane);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableClipPlane(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableClipPlane'"))
	{
		return -1;
	}

	bool bEnableClipPlaneTemp;
	if (!NePyBase::ToCpp(InValue, bEnableClipPlaneTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bEnableClipPlane = bEnableClipPlaneTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetClipPlaneBase(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ClipPlaneBase'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Vector(InSelf->GetValue()->ClipPlaneBase);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetClipPlaneBase(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ClipPlaneBase'"))
	{
		return -1;
	}

	if (FNePyStruct_Vector* PyClipPlaneBase = NePyStructCheck_Vector(InValue))
	{
		InSelf->GetValue()->ClipPlaneBase = *((FVector*)PyClipPlaneBase->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetClipPlaneNormal(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ClipPlaneNormal'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Vector(InSelf->GetValue()->ClipPlaneNormal);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetClipPlaneNormal(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ClipPlaneNormal'"))
	{
		return -1;
	}

	if (FNePyStruct_Vector* PyClipPlaneNormal = NePyStructCheck_Vector(InValue))
	{
		InSelf->GetValue()->ClipPlaneNormal = *((FVector*)PyClipPlaneNormal->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbRenderInMainRenderer(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bRenderInMainRenderer'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bRenderInMainRenderer);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbRenderInMainRenderer(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bRenderInMainRenderer'"))
	{
		return -1;
	}

	bool bRenderInMainRendererTemp;
	if (!NePyBase::ToCpp(InValue, bRenderInMainRendererTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bRenderInMainRenderer = bRenderInMainRendererTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetUnlitViewmode(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UnlitViewmode'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->UnlitViewmode);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetUnlitViewmode(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UnlitViewmode'"))
	{
		return -1;
	}

	uint8 UnlitViewmodeTemp;
	if (!NePyBase::ToCpp(InValue, UnlitViewmodeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(ESceneCaptureUnlitViewmode)");
		return -1;
	}
	InSelf->GetValue()->UnlitViewmode = (ESceneCaptureUnlitViewmode)UnlitViewmodeTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbCameraCutThisFrame(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bCameraCutThisFrame'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bCameraCutThisFrame);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbCameraCutThisFrame(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bCameraCutThisFrame'"))
	{
		return -1;
	}

	bool bCameraCutThisFrameTemp;
	if (!NePyBase::ToCpp(InValue, bCameraCutThisFrameTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bCameraCutThisFrame = bCameraCutThisFrameTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableFirstPersonFieldOfView(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableFirstPersonFieldOfView'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bEnableFirstPersonFieldOfView);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableFirstPersonFieldOfView(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableFirstPersonFieldOfView'"))
	{
		return -1;
	}

	bool bEnableFirstPersonFieldOfViewTemp;
	if (!NePyBase::ToCpp(InValue, bEnableFirstPersonFieldOfViewTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bEnableFirstPersonFieldOfView = bEnableFirstPersonFieldOfViewTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableFirstPersonScale(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableFirstPersonScale'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bEnableFirstPersonScale);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableFirstPersonScale(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bEnableFirstPersonScale'"))
	{
		return -1;
	}

	bool bEnableFirstPersonScaleTemp;
	if (!NePyBase::ToCpp(InValue, bEnableFirstPersonScaleTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bEnableFirstPersonScale = bEnableFirstPersonScaleTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbConsiderUnrenderedOpaquePixelAsFullyTranslucent(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bConsiderUnrenderedOpaquePixelAsFullyTranslucent'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bConsiderUnrenderedOpaquePixelAsFullyTranslucent);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbConsiderUnrenderedOpaquePixelAsFullyTranslucent(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bConsiderUnrenderedOpaquePixelAsFullyTranslucent'"))
	{
		return -1;
	}

	bool bConsiderUnrenderedOpaquePixelAsFullyTranslucentTemp;
	if (!NePyBase::ToCpp(InValue, bConsiderUnrenderedOpaquePixelAsFullyTranslucentTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bConsiderUnrenderedOpaquePixelAsFullyTranslucent = bConsiderUnrenderedOpaquePixelAsFullyTranslucentTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbMainViewFamily(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bMainViewFamily'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bMainViewFamily);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbMainViewFamily(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bMainViewFamily'"))
	{
		return -1;
	}

	bool bMainViewFamilyTemp;
	if (!NePyBase::ToCpp(InValue, bMainViewFamilyTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bMainViewFamily = bMainViewFamilyTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbMainViewResolution(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bMainViewResolution'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bMainViewResolution);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbMainViewResolution(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bMainViewResolution'"))
	{
		return -1;
	}

	bool bMainViewResolutionTemp;
	if (!NePyBase::ToCpp(InValue, bMainViewResolutionTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bMainViewResolution = bMainViewResolutionTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbMainViewCamera(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bMainViewCamera'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bMainViewCamera);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbMainViewCamera(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bMainViewCamera'"))
	{
		return -1;
	}

	bool bMainViewCameraTemp;
	if (!NePyBase::ToCpp(InValue, bMainViewCameraTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bMainViewCamera = bMainViewCameraTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbInheritMainViewCameraPostProcessSettings(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bInheritMainViewCameraPostProcessSettings'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bInheritMainViewCameraPostProcessSettings);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbInheritMainViewCameraPostProcessSettings(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bInheritMainViewCameraPostProcessSettings'"))
	{
		return -1;
	}

	bool bInheritMainViewCameraPostProcessSettingsTemp;
	if (!NePyBase::ToCpp(InValue, bInheritMainViewCameraPostProcessSettingsTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bInheritMainViewCameraPostProcessSettings = bInheritMainViewCameraPostProcessSettingsTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetbIgnoreScreenPercentage(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bIgnoreScreenPercentage'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bIgnoreScreenPercentage);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetbIgnoreScreenPercentage(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bIgnoreScreenPercentage'"))
	{
		return -1;
	}

	bool bIgnoreScreenPercentageTemp;
	if (!NePyBase::ToCpp(InValue, bIgnoreScreenPercentageTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bIgnoreScreenPercentage = bIgnoreScreenPercentageTemp;
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetMainViewResolutionDivisor(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'MainViewResolutionDivisor'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_IntPoint(InSelf->GetValue()->MainViewResolutionDivisor);
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetMainViewResolutionDivisor(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'MainViewResolutionDivisor'"))
	{
		return -1;
	}

	if (FNePyStruct_IntPoint* PyMainViewResolutionDivisor = NePyStructCheck_IntPoint(InValue))
	{
		InSelf->GetValue()->MainViewResolutionDivisor = *((FIntPoint*)PyMainViewResolutionDivisor->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'IntPoint'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetUserSceneTextureBaseColor(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UserSceneTextureBaseColor'"))
	{
		return nullptr;
	}

	PyObject* RetValue;
	if (!NePyBase::ToPy(InSelf->GetValue()->UserSceneTextureBaseColor, RetValue))
	{
		PyErr_SetString(PyExc_TypeError, "convert to str failed, src type is 'Name'");
		return nullptr;
	}
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetUserSceneTextureBaseColor(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UserSceneTextureBaseColor'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->UserSceneTextureBaseColor))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Name'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetUserSceneTextureNormal(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UserSceneTextureNormal'"))
	{
		return nullptr;
	}

	PyObject* RetValue;
	if (!NePyBase::ToPy(InSelf->GetValue()->UserSceneTextureNormal, RetValue))
	{
		PyErr_SetString(PyExc_TypeError, "convert to str failed, src type is 'Name'");
		return nullptr;
	}
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetUserSceneTextureNormal(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UserSceneTextureNormal'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->UserSceneTextureNormal))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Name'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_SceneCaptureComponent2D_Prop_GetUserSceneTextureSceneColor(FNePyObject_SceneCaptureComponent2D* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UserSceneTextureSceneColor'"))
	{
		return nullptr;
	}

	PyObject* RetValue;
	if (!NePyBase::ToPy(InSelf->GetValue()->UserSceneTextureSceneColor, RetValue))
	{
		PyErr_SetString(PyExc_TypeError, "convert to str failed, src type is 'Name'");
		return nullptr;
	}
	return RetValue;
}

int FNePyObject_SceneCaptureComponent2D_Prop_SetUserSceneTextureSceneColor(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'UserSceneTextureSceneColor'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->UserSceneTextureSceneColor))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Name'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_SceneCaptureComponent2D_getset[] = {
	{ (char*)"ProjectionType", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetProjectionType, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetProjectionType, nullptr, nullptr },
	{ (char*)"FOVAngle", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetFOVAngle, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetFOVAngle, nullptr, nullptr },
	{ (char*)"FirstPersonFieldOfView", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetFirstPersonFieldOfView, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetFirstPersonFieldOfView, nullptr, nullptr },
	{ (char*)"FirstPersonScale", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetFirstPersonScale, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetFirstPersonScale, nullptr, nullptr },
	{ (char*)"OrthoWidth", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetOrthoWidth, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetOrthoWidth, nullptr, nullptr },
	{ (char*)"bAutoCalculateOrthoPlanes", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbAutoCalculateOrthoPlanes, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbAutoCalculateOrthoPlanes, nullptr, nullptr },
	{ (char*)"AutoPlaneShift", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetAutoPlaneShift, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetAutoPlaneShift, nullptr, nullptr },
	{ (char*)"bUpdateOrthoPlanes", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbUpdateOrthoPlanes, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbUpdateOrthoPlanes, nullptr, nullptr },
	{ (char*)"bUseCameraHeightAsViewTarget", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbUseCameraHeightAsViewTarget, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbUseCameraHeightAsViewTarget, nullptr, nullptr },
	{ (char*)"Overscan", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetOverscan, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetOverscan, nullptr, nullptr },
	{ (char*)"TextureTarget", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetTextureTarget, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetTextureTarget, nullptr, nullptr },
	{ (char*)"CompositeMode", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetCompositeMode, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetCompositeMode, nullptr, nullptr },
	{ (char*)"PostProcessSettings", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetPostProcessSettings, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetPostProcessSettings, nullptr, nullptr },
	{ (char*)"PostProcessBlendWeight", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetPostProcessBlendWeight, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetPostProcessBlendWeight, nullptr, nullptr },
	{ (char*)"bOverride_CustomNearClippingPlane", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbOverride_CustomNearClippingPlane, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbOverride_CustomNearClippingPlane, nullptr, nullptr },
	{ (char*)"CustomNearClippingPlane", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetCustomNearClippingPlane, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetCustomNearClippingPlane, nullptr, nullptr },
	{ (char*)"bUseCustomProjectionMatrix", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbUseCustomProjectionMatrix, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbUseCustomProjectionMatrix, nullptr, nullptr },
	{ (char*)"CustomProjectionMatrix", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetCustomProjectionMatrix, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetCustomProjectionMatrix, nullptr, nullptr },
	{ (char*)"bEnableOrthographicTiling", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableOrthographicTiling, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableOrthographicTiling, nullptr, nullptr },
	{ (char*)"NumXTiles", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetNumXTiles, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetNumXTiles, nullptr, nullptr },
	{ (char*)"NumYTiles", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetNumYTiles, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetNumYTiles, nullptr, nullptr },
	{ (char*)"bEnableClipPlane", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableClipPlane, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableClipPlane, nullptr, nullptr },
	{ (char*)"ClipPlaneBase", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetClipPlaneBase, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetClipPlaneBase, nullptr, nullptr },
	{ (char*)"ClipPlaneNormal", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetClipPlaneNormal, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetClipPlaneNormal, nullptr, nullptr },
	{ (char*)"bRenderInMainRenderer", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbRenderInMainRenderer, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbRenderInMainRenderer, nullptr, nullptr },
	{ (char*)"UnlitViewmode", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetUnlitViewmode, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetUnlitViewmode, nullptr, nullptr },
	{ (char*)"bCameraCutThisFrame", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbCameraCutThisFrame, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbCameraCutThisFrame, nullptr, nullptr },
	{ (char*)"bEnableFirstPersonFieldOfView", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableFirstPersonFieldOfView, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableFirstPersonFieldOfView, nullptr, nullptr },
	{ (char*)"bEnableFirstPersonScale", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbEnableFirstPersonScale, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbEnableFirstPersonScale, nullptr, nullptr },
	{ (char*)"bConsiderUnrenderedOpaquePixelAsFullyTranslucent", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbConsiderUnrenderedOpaquePixelAsFullyTranslucent, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbConsiderUnrenderedOpaquePixelAsFullyTranslucent, nullptr, nullptr },
	{ (char*)"bMainViewFamily", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbMainViewFamily, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbMainViewFamily, nullptr, nullptr },
	{ (char*)"bMainViewResolution", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbMainViewResolution, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbMainViewResolution, nullptr, nullptr },
	{ (char*)"bMainViewCamera", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbMainViewCamera, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbMainViewCamera, nullptr, nullptr },
	{ (char*)"bInheritMainViewCameraPostProcessSettings", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbInheritMainViewCameraPostProcessSettings, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbInheritMainViewCameraPostProcessSettings, nullptr, nullptr },
	{ (char*)"bIgnoreScreenPercentage", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetbIgnoreScreenPercentage, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetbIgnoreScreenPercentage, nullptr, nullptr },
	{ (char*)"MainViewResolutionDivisor", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetMainViewResolutionDivisor, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetMainViewResolutionDivisor, nullptr, nullptr },
	{ (char*)"UserSceneTextureBaseColor", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetUserSceneTextureBaseColor, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetUserSceneTextureBaseColor, nullptr, nullptr },
	{ (char*)"UserSceneTextureNormal", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetUserSceneTextureNormal, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetUserSceneTextureNormal, nullptr, nullptr },
	{ (char*)"UserSceneTextureSceneColor", (getter)FNePyObject_SceneCaptureComponent2D_Prop_GetUserSceneTextureSceneColor, (setter)FNePyObject_SceneCaptureComponent2D_Prop_SetUserSceneTextureSceneColor, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_SceneCaptureComponent2D_CaptureScene(FNePyObject_SceneCaptureComponent2D* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'CaptureScene'"))
	{
		return nullptr;
	}

	InSelf->GetValue()->CaptureScene();
	Py_RETURN_NONE;
}

// PyObject* FNePyObject_SceneCaptureComponent2D_RemoveBlendable(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InArg)
// {
// 	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'RemoveBlendable'"))
// 	{
// 		return nullptr;
// 	}
// 
// 	PyObject* PyArgs[1] = {InArg};
// 
// 	// unsupported PyArgs[0] InterfaceProperty InBlendableObject [param "InBlendableObject": interface type "BlendableInterface" not exported];
// 
// 	InSelf->GetValue()->RemoveBlendable(InBlendableObject);
// 	Py_RETURN_NONE;
// }

// PyObject* FNePyObject_SceneCaptureComponent2D_AddOrUpdateBlendable(FNePyObject_SceneCaptureComponent2D* InSelf, PyObject* InArgs)
// {
// 	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'AddOrUpdateBlendable'"))
// 	{
// 		return nullptr;
// 	}
// 
// 	PyObject* PyArgs[2] = {nullptr, nullptr};
// 	if (!PyArg_ParseTuple(InArgs, "O|O:AddOrUpdateBlendable", &PyArgs[0], &PyArgs[1]))
// 	{
// 		return nullptr;
// 	}
// 
// 	// unsupported PyArgs[0] InterfaceProperty InBlendableObject [param "InBlendableObject": interface type "BlendableInterface" not exported];
// 
// 	float InWeight = 1.000000f;
// 	if (PyArgs[1])
// 	{
// 		if (!NePyBase::ToCpp(PyArgs[1], InWeight))
// 		{
// 			PyErr_SetString(PyExc_TypeError, "arg2 'InWeight' must have type 'float'");
// 			return nullptr;
// 		}
// 	}
// 
// 	InSelf->GetValue()->AddOrUpdateBlendable(InBlendableObject, InWeight);
// 	Py_RETURN_NONE;
// }
// region func body end

static PyObject* FNePyObject_SceneCaptureComponent2D_Class(PyObject* InSelf) {
	UClass* Class = USceneCaptureComponent2D::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_SceneCaptureComponent2D_methods[] = {
	{"CaptureScene", NePyCFunctionCast(&FNePyObject_SceneCaptureComponent2D_CaptureScene), METH_NOARGS, ""},
	// unsupported {"RemoveBlendable", NePyCFunctionCast(&FNePyObject_SceneCaptureComponent2D_RemoveBlendable), METH_O, ""}, [PyArgs[0] InterfaceProperty InBlendableObject [param "InBlendableObject": interface type "BlendableInterface" not exported]]
	// unsupported {"AddOrUpdateBlendable", NePyCFunctionCast(&FNePyObject_SceneCaptureComponent2D_AddOrUpdateBlendable), METH_VARARGS, ""}, [PyArgs[0] InterfaceProperty InBlendableObject [param "InBlendableObject": interface type "BlendableInterface" not exported]]
	{"Class", NePyCFunctionCast(&FNePyObject_SceneCaptureComponent2D_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_SceneCaptureComponent2D* NePyObjectNew_SceneCaptureComponent2D(USceneCaptureComponent2D* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_SceneCaptureComponent2D));
	FNePyObject_SceneCaptureComponent2D* RetValue = (FNePyObject_SceneCaptureComponent2D*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_SceneCaptureComponent2D* NePyObjectCheck_SceneCaptureComponent2D(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_SceneCaptureComponent2D))
	{
		return (FNePyObject_SceneCaptureComponent2D*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_SceneCaptureComponent2D()
{
	return &FNePyObjectType_SceneCaptureComponent2D;
}

PyTypeObject* NePyNePyWrappedClassInit_SceneCaptureComponent2D(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_SceneCaptureComponent2D;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_SceneCaptureComponent2D_getset;
	NePyObjectType->tp_methods = FNePyObjectType_SceneCaptureComponent2D_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_SceneCaptureComponent2D,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_SceneCaptureComponent2D(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		USceneCaptureComponent2D::StaticClass(), NePyNePyWrappedClassInit_SceneCaptureComponent2D);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, USceneCaptureComponent2D*& OutVal)
	{
		if (FNePyObject_SceneCaptureComponent2D* PyObj = NePyObjectCheck_SceneCaptureComponent2D(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif