// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_CompositeDataTable.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_CompositeDataTable = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"CompositeDataTable", /* tp_name */
	sizeof(FNePyObject_CompositeDataTable), /* tp_basicsize */
};

static PyObject* FNePyObject_CompositeDataTable_Class(PyObject* InSelf) {
	UClass* Class = UCompositeDataTable::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_CompositeDataTable_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_CompositeDataTable_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_CompositeDataTable* NePyObjectNew_CompositeDataTable(UCompositeDataTable* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_CompositeDataTable));
	FNePyObject_CompositeDataTable* RetValue = (FNePyObject_CompositeDataTable*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_CompositeDataTable* NePyObjectCheck_CompositeDataTable(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_CompositeDataTable))
	{
		return (FNePyObject_CompositeDataTable*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_CompositeDataTable()
{
	return &FNePyObjectType_CompositeDataTable;
}

PyTypeObject* NePyNePyWrappedClassInit_CompositeDataTable(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_CompositeDataTable;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_CompositeDataTable_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_CompositeDataTable,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_CompositeDataTable(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UCompositeDataTable::StaticClass(), NePyNePyWrappedClassInit_CompositeDataTable);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UCompositeDataTable*& OutVal)
	{
		if (FNePyObject_CompositeDataTable* PyObj = NePyObjectCheck_CompositeDataTable(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif