// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_RuntimeVirtualTexture.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_RuntimeVirtualTexture = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"RuntimeVirtualTexture", /* tp_name */
	sizeof(FNePyObject_RuntimeVirtualTexture), /* tp_basicsize */
};

// region func body begin
PyObject* FNePyObject_RuntimeVirtualTexture_GetPageTableSize(FNePyObject_RuntimeVirtualTexture* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetPageTableSize'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetPageTableSize();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_RuntimeVirtualTexture_GetSize(FNePyObject_RuntimeVirtualTexture* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetSize'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetSize();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_RuntimeVirtualTexture_GetTileBorderSize(FNePyObject_RuntimeVirtualTexture* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetTileBorderSize'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetTileBorderSize();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_RuntimeVirtualTexture_GetTileSize(FNePyObject_RuntimeVirtualTexture* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetTileSize'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetTileSize();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_RuntimeVirtualTexture_GetTileCount(FNePyObject_RuntimeVirtualTexture* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetTileCount'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetTileCount();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}
// region func body end

static PyObject* FNePyObject_RuntimeVirtualTexture_Class(PyObject* InSelf) {
	UClass* Class = URuntimeVirtualTexture::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_RuntimeVirtualTexture_methods[] = {
	{"GetPageTableSize", NePyCFunctionCast(&FNePyObject_RuntimeVirtualTexture_GetPageTableSize), METH_NOARGS, ""},
	{"GetSize", NePyCFunctionCast(&FNePyObject_RuntimeVirtualTexture_GetSize), METH_NOARGS, ""},
	{"GetTileBorderSize", NePyCFunctionCast(&FNePyObject_RuntimeVirtualTexture_GetTileBorderSize), METH_NOARGS, ""},
	{"GetTileSize", NePyCFunctionCast(&FNePyObject_RuntimeVirtualTexture_GetTileSize), METH_NOARGS, ""},
	{"GetTileCount", NePyCFunctionCast(&FNePyObject_RuntimeVirtualTexture_GetTileCount), METH_NOARGS, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_RuntimeVirtualTexture_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_RuntimeVirtualTexture* NePyObjectNew_RuntimeVirtualTexture(URuntimeVirtualTexture* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_RuntimeVirtualTexture));
	FNePyObject_RuntimeVirtualTexture* RetValue = (FNePyObject_RuntimeVirtualTexture*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_RuntimeVirtualTexture* NePyObjectCheck_RuntimeVirtualTexture(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_RuntimeVirtualTexture))
	{
		return (FNePyObject_RuntimeVirtualTexture*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_RuntimeVirtualTexture()
{
	return &FNePyObjectType_RuntimeVirtualTexture;
}

PyTypeObject* NePyNePyWrappedClassInit_RuntimeVirtualTexture(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_RuntimeVirtualTexture;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_RuntimeVirtualTexture_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_RuntimeVirtualTexture,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_RuntimeVirtualTexture(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		URuntimeVirtualTexture::StaticClass(), NePyNePyWrappedClassInit_RuntimeVirtualTexture);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, URuntimeVirtualTexture*& OutVal)
	{
		if (FNePyObject_RuntimeVirtualTexture* PyObj = NePyObjectCheck_RuntimeVirtualTexture(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif