#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "AI/Navigation/NavLinkDefinition.h"
// region include end

class FNePyObject_NavLinkDefinition : public FNePyObjectBase
{
public:
	inline UNavLinkDefinition* GetValue()
	{
		return (UNavLinkDefinition*)Value;
	}
};

void NePyInitObject_NavLinkDefinition(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_NavLinkDefinition* NePyObjectCheck_NavLinkDefinition(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_NavLinkDefinition();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UNavLinkDefinition*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif