#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Animation/AnimNodeSpaceConversions.h"
// region include end

struct FNePyStruct_AnimNode_ConvertLocalToComponentSpace : public TNePyStructBase<FAnimNode_ConvertLocalToComponentSpace>
{
};

void NePyInitStruct_AnimNode_ConvertLocalToComponentSpace(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_AnimNode_ConvertLocalToComponentSpace* NePyStructNew_AnimNode_ConvertLocalToComponentSpace(const FAnimNode_ConvertLocalToComponentSpace& InValue);

NEPYTHONBINDING_API FNePyStruct_AnimNode_ConvertLocalToComponentSpace* NePyStructCheck_AnimNode_ConvertLocalToComponentSpace(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_AnimNode_ConvertLocalToComponentSpace();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FAnimNode_ConvertLocalToComponentSpace& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FAnimNode_ConvertLocalToComponentSpace& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif