// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_LevelInstanceEditorInstanceActor.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_LevelInstanceEditorInstanceActor = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"LevelInstanceEditorInstanceActor", /* tp_name */
	sizeof(FNePyObject_LevelInstanceEditorInstanceActor), /* tp_basicsize */
};

static PyObject* FNePyObject_LevelInstanceEditorInstanceActor_Class(PyObject* InSelf) {
	UClass* Class = ALevelInstanceEditorInstanceActor::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_LevelInstanceEditorInstanceActor_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_LevelInstanceEditorInstanceActor_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_LevelInstanceEditorInstanceActor* NePyObjectNew_LevelInstanceEditorInstanceActor(ALevelInstanceEditorInstanceActor* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_LevelInstanceEditorInstanceActor));
	FNePyObject_LevelInstanceEditorInstanceActor* RetValue = (FNePyObject_LevelInstanceEditorInstanceActor*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_LevelInstanceEditorInstanceActor* NePyObjectCheck_LevelInstanceEditorInstanceActor(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_LevelInstanceEditorInstanceActor))
	{
		return (FNePyObject_LevelInstanceEditorInstanceActor*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_LevelInstanceEditorInstanceActor()
{
	return &FNePyObjectType_LevelInstanceEditorInstanceActor;
}

PyTypeObject* NePyNePyWrappedClassInit_LevelInstanceEditorInstanceActor(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_LevelInstanceEditorInstanceActor;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_LevelInstanceEditorInstanceActor_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_LevelInstanceEditorInstanceActor,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_LevelInstanceEditorInstanceActor(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		ALevelInstanceEditorInstanceActor::StaticClass(), NePyNePyWrappedClassInit_LevelInstanceEditorInstanceActor);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, ALevelInstanceEditorInstanceActor*& OutVal)
	{
		if (FNePyObject_LevelInstanceEditorInstanceActor* PyObj = NePyObjectCheck_LevelInstanceEditorInstanceActor(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif