#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "Engine/CanvasRenderTarget2D.h"
// region include end

class FNePyObject_CanvasRenderTarget2D : public FNePyObjectBase
{
public:
	inline UCanvasRenderTarget2D* GetValue()
	{
		return (UCanvasRenderTarget2D*)Value;
	}
};

void NePyInitObject_CanvasRenderTarget2D(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_CanvasRenderTarget2D* NePyObjectCheck_CanvasRenderTarget2D(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_CanvasRenderTarget2D();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UCanvasRenderTarget2D*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif