#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "Components/SkinnedMeshComponent.h"
// region include end

class FNePyObject_SkinnedMeshComponent : public FNePyObjectBase
{
public:
	inline USkinnedMeshComponent* GetValue()
	{
		return (USkinnedMeshComponent*)Value;
	}
};

void NePyInitObject_SkinnedMeshComponent(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_SkinnedMeshComponent* NePyObjectCheck_SkinnedMeshComponent(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_SkinnedMeshComponent();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, USkinnedMeshComponent*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif