// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_TextureCubeArray.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_TextureCubeArray = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"TextureCubeArray", /* tp_name */
	sizeof(FNePyObject_TextureCubeArray), /* tp_basicsize */
};

static PyObject* FNePyObject_TextureCubeArray_Class(PyObject* InSelf) {
	UClass* Class = UTextureCubeArray::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_TextureCubeArray_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_TextureCubeArray_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_TextureCubeArray* NePyObjectNew_TextureCubeArray(UTextureCubeArray* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_TextureCubeArray));
	FNePyObject_TextureCubeArray* RetValue = (FNePyObject_TextureCubeArray*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_TextureCubeArray* NePyObjectCheck_TextureCubeArray(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_TextureCubeArray))
	{
		return (FNePyObject_TextureCubeArray*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_TextureCubeArray()
{
	return &FNePyObjectType_TextureCubeArray;
}

PyTypeObject* NePyNePyWrappedClassInit_TextureCubeArray(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_TextureCubeArray;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_TextureCubeArray_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_TextureCubeArray,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_TextureCubeArray(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UTextureCubeArray::StaticClass(), NePyNePyWrappedClassInit_TextureCubeArray);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UTextureCubeArray*& OutVal)
	{
		if (FNePyObject_TextureCubeArray* PyObj = NePyObjectCheck_TextureCubeArray(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif