#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "Engine/TriggerVolume.h"
// region include end

class FNePyObject_TriggerVolume : public FNePyObjectBase
{
public:
	inline ATriggerVolume* GetValue()
	{
		return (ATriggerVolume*)Value;
	}
};

void NePyInitObject_TriggerVolume(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_TriggerVolume* NePyObjectCheck_TriggerVolume(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_TriggerVolume();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, ATriggerVolume*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif