// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_RadialForceComponent.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_RadialForceComponent = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"RadialForceComponent", /* tp_name */
	sizeof(FNePyObject_RadialForceComponent), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_RadialForceComponent_Prop_GetRadius(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Radius'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->Radius);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetRadius(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Radius'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->Radius))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_RadialForceComponent_Prop_GetFalloff(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Falloff'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)InSelf->GetValue()->Falloff);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetFalloff(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Falloff'"))
	{
		return -1;
	}

	uint8 FalloffTemp;
	if (!NePyBase::ToCpp(InValue, FalloffTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(ERadialImpulseFalloff)");
		return -1;
	}
	InSelf->GetValue()->Falloff = (ERadialImpulseFalloff)FalloffTemp;
	return 0;
}

PyObject* FNePyObject_RadialForceComponent_Prop_GetImpulseStrength(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ImpulseStrength'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->ImpulseStrength);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetImpulseStrength(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ImpulseStrength'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->ImpulseStrength))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_RadialForceComponent_Prop_GetbImpulseVelChange(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bImpulseVelChange'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bImpulseVelChange);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetbImpulseVelChange(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bImpulseVelChange'"))
	{
		return -1;
	}

	bool bImpulseVelChangeTemp;
	if (!NePyBase::ToCpp(InValue, bImpulseVelChangeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bImpulseVelChange = bImpulseVelChangeTemp;
	return 0;
}

PyObject* FNePyObject_RadialForceComponent_Prop_GetbIgnoreOwningActor(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bIgnoreOwningActor'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyBool_FromLong(InSelf->GetValue()->bIgnoreOwningActor);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetbIgnoreOwningActor(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'bIgnoreOwningActor'"))
	{
		return -1;
	}

	bool bIgnoreOwningActorTemp;
	if (!NePyBase::ToCpp(InValue, bIgnoreOwningActorTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	InSelf->GetValue()->bIgnoreOwningActor = bIgnoreOwningActorTemp;
	return 0;
}

PyObject* FNePyObject_RadialForceComponent_Prop_GetForceStrength(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ForceStrength'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->ForceStrength);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetForceStrength(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ForceStrength'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->ForceStrength))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_RadialForceComponent_Prop_GetDestructibleDamage(FNePyObject_RadialForceComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DestructibleDamage'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->DestructibleDamage);
	return RetValue;
}

int FNePyObject_RadialForceComponent_Prop_SetDestructibleDamage(FNePyObject_RadialForceComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DestructibleDamage'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->DestructibleDamage))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_RadialForceComponent_getset[] = {
	{ (char*)"Radius", (getter)FNePyObject_RadialForceComponent_Prop_GetRadius, (setter)FNePyObject_RadialForceComponent_Prop_SetRadius, nullptr, nullptr },
	{ (char*)"Falloff", (getter)FNePyObject_RadialForceComponent_Prop_GetFalloff, (setter)FNePyObject_RadialForceComponent_Prop_SetFalloff, nullptr, nullptr },
	{ (char*)"ImpulseStrength", (getter)FNePyObject_RadialForceComponent_Prop_GetImpulseStrength, (setter)FNePyObject_RadialForceComponent_Prop_SetImpulseStrength, nullptr, nullptr },
	{ (char*)"bImpulseVelChange", (getter)FNePyObject_RadialForceComponent_Prop_GetbImpulseVelChange, (setter)FNePyObject_RadialForceComponent_Prop_SetbImpulseVelChange, nullptr, nullptr },
	{ (char*)"bIgnoreOwningActor", (getter)FNePyObject_RadialForceComponent_Prop_GetbIgnoreOwningActor, (setter)FNePyObject_RadialForceComponent_Prop_SetbIgnoreOwningActor, nullptr, nullptr },
	{ (char*)"ForceStrength", (getter)FNePyObject_RadialForceComponent_Prop_GetForceStrength, (setter)FNePyObject_RadialForceComponent_Prop_SetForceStrength, nullptr, nullptr },
	{ (char*)"DestructibleDamage", (getter)FNePyObject_RadialForceComponent_Prop_GetDestructibleDamage, (setter)FNePyObject_RadialForceComponent_Prop_SetDestructibleDamage, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_RadialForceComponent_RemoveObjectTypeToAffect(FNePyObject_RadialForceComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'RemoveObjectTypeToAffect'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 ObjectTypeTemp;
	if (!NePyBase::ToCpp(PyArgs[0], ObjectTypeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'ObjectType' must have type 'int'(EObjectTypeQuery)");
		return nullptr;
	}
	EObjectTypeQuery ObjectType = (EObjectTypeQuery)ObjectTypeTemp;

	InSelf->GetValue()->RemoveObjectTypeToAffect(ObjectType);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_RadialForceComponent_AddObjectTypeToAffect(FNePyObject_RadialForceComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'AddObjectTypeToAffect'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	uint8 ObjectTypeTemp;
	if (!NePyBase::ToCpp(PyArgs[0], ObjectTypeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'ObjectType' must have type 'int'(EObjectTypeQuery)");
		return nullptr;
	}
	EObjectTypeQuery ObjectType = (EObjectTypeQuery)ObjectTypeTemp;

	InSelf->GetValue()->AddObjectTypeToAffect(ObjectType);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_RadialForceComponent_FireImpulse(FNePyObject_RadialForceComponent* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'FireImpulse'"))
	{
		return nullptr;
	}

	InSelf->GetValue()->FireImpulse();
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_RadialForceComponent_Class(PyObject* InSelf) {
	UClass* Class = URadialForceComponent::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_RadialForceComponent_methods[] = {
	{"RemoveObjectTypeToAffect", NePyCFunctionCast(&FNePyObject_RadialForceComponent_RemoveObjectTypeToAffect), METH_O, ""},
	{"AddObjectTypeToAffect", NePyCFunctionCast(&FNePyObject_RadialForceComponent_AddObjectTypeToAffect), METH_O, ""},
	{"FireImpulse", NePyCFunctionCast(&FNePyObject_RadialForceComponent_FireImpulse), METH_NOARGS, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_RadialForceComponent_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_RadialForceComponent* NePyObjectNew_RadialForceComponent(URadialForceComponent* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_RadialForceComponent));
	FNePyObject_RadialForceComponent* RetValue = (FNePyObject_RadialForceComponent*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_RadialForceComponent* NePyObjectCheck_RadialForceComponent(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_RadialForceComponent))
	{
		return (FNePyObject_RadialForceComponent*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_RadialForceComponent()
{
	return &FNePyObjectType_RadialForceComponent;
}

PyTypeObject* NePyNePyWrappedClassInit_RadialForceComponent(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_RadialForceComponent;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_RadialForceComponent_getset;
	NePyObjectType->tp_methods = FNePyObjectType_RadialForceComponent_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_RadialForceComponent,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_RadialForceComponent(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		URadialForceComponent::StaticClass(), NePyNePyWrappedClassInit_RadialForceComponent);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, URadialForceComponent*& OutVal)
	{
		if (FNePyObject_RadialForceComponent* PyObj = NePyObjectCheck_RadialForceComponent(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif