// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_PrimitiveInstanceId.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_PrimitiveInstanceId = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"PrimitiveInstanceId", /* tp_name */
	sizeof(FNePyStruct_PrimitiveInstanceId), /* tp_basicsize */
};

bool NePyStructPropSet_PrimitiveInstanceId(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_PrimitiveInstanceId* PyObj = NePyStructCheck_PrimitiveInstanceId(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_PrimitiveInstanceId(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_PrimitiveInstanceId;
	FNePyStruct_PrimitiveInstanceId* PyObj = (FNePyStruct_PrimitiveInstanceId*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FPrimitiveInstanceId*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FPrimitiveInstanceId*)FMemory::Malloc(sizeof(FPrimitiveInstanceId), alignof(FPrimitiveInstanceId));
	NePyBase::EnsureCopyToStructSafely<FPrimitiveInstanceId>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_PrimitiveInstanceId(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_PrimitiveInstanceId;
	TNePyStructBase<FPrimitiveInstanceId>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_PrimitiveInstanceId,
			(NePyStructPropGet)NePyStructPropGet_PrimitiveInstanceId,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_PrimitiveInstanceId(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FPrimitiveInstanceId>::Get(), NePyNePyWrappedStructInit_PrimitiveInstanceId);
}

FNePyStruct_PrimitiveInstanceId* NePyStructNew_PrimitiveInstanceId(const FPrimitiveInstanceId& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_PrimitiveInstanceId;
	FNePyStruct_PrimitiveInstanceId* RetValue = (FNePyStruct_PrimitiveInstanceId*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_PrimitiveInstanceId::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FPrimitiveInstanceId(InValue);
	return RetValue;
}

FNePyStruct_PrimitiveInstanceId* NePyStructCheck_PrimitiveInstanceId(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_PrimitiveInstanceId))
	{
		return (FNePyStruct_PrimitiveInstanceId*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_PrimitiveInstanceId()
{
	return &FNePyStructType_PrimitiveInstanceId;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FPrimitiveInstanceId& OutVal)
	{
		if (FNePyStruct_PrimitiveInstanceId* PyObj = NePyStructCheck_PrimitiveInstanceId(InPyObj))
		{
			OutVal = *(FPrimitiveInstanceId*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FPrimitiveInstanceId& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_PrimitiveInstanceId(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif