// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_AnimNode_CustomProperty.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_AnimNode_CustomProperty = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"AnimNode_CustomProperty", /* tp_name */
	sizeof(FNePyStruct_AnimNode_CustomProperty), /* tp_basicsize */
};

bool NePyStructPropSet_AnimNode_CustomProperty(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_AnimNode_CustomProperty* PyObj = NePyStructCheck_AnimNode_CustomProperty(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_AnimNode_CustomProperty(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_AnimNode_CustomProperty;
	FNePyStruct_AnimNode_CustomProperty* PyObj = (FNePyStruct_AnimNode_CustomProperty*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FAnimNode_CustomProperty*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FAnimNode_CustomProperty*)FMemory::Malloc(sizeof(FAnimNode_CustomProperty), alignof(FAnimNode_CustomProperty));
	NePyBase::EnsureCopyToStructSafely<FAnimNode_CustomProperty>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_AnimNode_CustomProperty(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_AnimNode_CustomProperty;
	TNePyStructBase<FAnimNode_CustomProperty>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_AnimNode_CustomProperty,
			(NePyStructPropGet)NePyStructPropGet_AnimNode_CustomProperty,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_AnimNode_CustomProperty(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FAnimNode_CustomProperty>::Get(), NePyNePyWrappedStructInit_AnimNode_CustomProperty);
}

FNePyStruct_AnimNode_CustomProperty* NePyStructNew_AnimNode_CustomProperty(const FAnimNode_CustomProperty& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_AnimNode_CustomProperty;
	FNePyStruct_AnimNode_CustomProperty* RetValue = (FNePyStruct_AnimNode_CustomProperty*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_AnimNode_CustomProperty::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FAnimNode_CustomProperty(InValue);
	return RetValue;
}

FNePyStruct_AnimNode_CustomProperty* NePyStructCheck_AnimNode_CustomProperty(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_AnimNode_CustomProperty))
	{
		return (FNePyStruct_AnimNode_CustomProperty*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_AnimNode_CustomProperty()
{
	return &FNePyStructType_AnimNode_CustomProperty;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FAnimNode_CustomProperty& OutVal)
	{
		if (FNePyStruct_AnimNode_CustomProperty* PyObj = NePyStructCheck_AnimNode_CustomProperty(InPyObj))
		{
			OutVal = *(FAnimNode_CustomProperty*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FAnimNode_CustomProperty& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_AnimNode_CustomProperty(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif