// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_ExternalDataLayerAsset.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_ExternalDataLayerAsset = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"ExternalDataLayerAsset", /* tp_name */
	sizeof(FNePyObject_ExternalDataLayerAsset), /* tp_basicsize */
};

static PyObject* FNePyObject_ExternalDataLayerAsset_Class(PyObject* InSelf) {
	UClass* Class = UExternalDataLayerAsset::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_ExternalDataLayerAsset_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_ExternalDataLayerAsset_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_ExternalDataLayerAsset* NePyObjectNew_ExternalDataLayerAsset(UExternalDataLayerAsset* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_ExternalDataLayerAsset));
	FNePyObject_ExternalDataLayerAsset* RetValue = (FNePyObject_ExternalDataLayerAsset*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_ExternalDataLayerAsset* NePyObjectCheck_ExternalDataLayerAsset(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_ExternalDataLayerAsset))
	{
		return (FNePyObject_ExternalDataLayerAsset*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_ExternalDataLayerAsset()
{
	return &FNePyObjectType_ExternalDataLayerAsset;
}

PyTypeObject* NePyNePyWrappedClassInit_ExternalDataLayerAsset(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_ExternalDataLayerAsset;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_ExternalDataLayerAsset_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_ExternalDataLayerAsset,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_ExternalDataLayerAsset(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UExternalDataLayerAsset::StaticClass(), NePyNePyWrappedClassInit_ExternalDataLayerAsset);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UExternalDataLayerAsset*& OutVal)
	{
		if (FNePyObject_ExternalDataLayerAsset* PyObj = NePyObjectCheck_ExternalDataLayerAsset(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif