// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_AvoidanceManager.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_MovementComponent.h"
#include "NePy/Auto/core/NePyStruct_Vector.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_AvoidanceManager = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"AvoidanceManager", /* tp_name */
	sizeof(FNePyObject_AvoidanceManager), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_AvoidanceManager_Prop_GetDefaultTimeToLive(FNePyObject_AvoidanceManager* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DefaultTimeToLive'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->DefaultTimeToLive);
	return RetValue;
}

int FNePyObject_AvoidanceManager_Prop_SetDefaultTimeToLive(FNePyObject_AvoidanceManager* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DefaultTimeToLive'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->DefaultTimeToLive))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_AvoidanceManager_Prop_GetLockTimeAfterAvoid(FNePyObject_AvoidanceManager* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'LockTimeAfterAvoid'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->LockTimeAfterAvoid);
	return RetValue;
}

int FNePyObject_AvoidanceManager_Prop_SetLockTimeAfterAvoid(FNePyObject_AvoidanceManager* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'LockTimeAfterAvoid'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->LockTimeAfterAvoid))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_AvoidanceManager_Prop_GetLockTimeAfterClean(FNePyObject_AvoidanceManager* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'LockTimeAfterClean'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->LockTimeAfterClean);
	return RetValue;
}

int FNePyObject_AvoidanceManager_Prop_SetLockTimeAfterClean(FNePyObject_AvoidanceManager* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'LockTimeAfterClean'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->LockTimeAfterClean))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_AvoidanceManager_Prop_GetDeltaTimeToPredict(FNePyObject_AvoidanceManager* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DeltaTimeToPredict'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->DeltaTimeToPredict);
	return RetValue;
}

int FNePyObject_AvoidanceManager_Prop_SetDeltaTimeToPredict(FNePyObject_AvoidanceManager* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DeltaTimeToPredict'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->DeltaTimeToPredict))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_AvoidanceManager_Prop_GetArtificialRadiusExpansion(FNePyObject_AvoidanceManager* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ArtificialRadiusExpansion'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->ArtificialRadiusExpansion);
	return RetValue;
}

int FNePyObject_AvoidanceManager_Prop_SetArtificialRadiusExpansion(FNePyObject_AvoidanceManager* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ArtificialRadiusExpansion'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->ArtificialRadiusExpansion))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_AvoidanceManager_Prop_GetHeightCheckMargin(FNePyObject_AvoidanceManager* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightCheckMargin'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->HeightCheckMargin);
	return RetValue;
}

int FNePyObject_AvoidanceManager_Prop_SetHeightCheckMargin(FNePyObject_AvoidanceManager* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightCheckMargin'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->HeightCheckMargin))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_AvoidanceManager_getset[] = {
	{ (char*)"DefaultTimeToLive", (getter)FNePyObject_AvoidanceManager_Prop_GetDefaultTimeToLive, (setter)FNePyObject_AvoidanceManager_Prop_SetDefaultTimeToLive, nullptr, nullptr },
	{ (char*)"LockTimeAfterAvoid", (getter)FNePyObject_AvoidanceManager_Prop_GetLockTimeAfterAvoid, (setter)FNePyObject_AvoidanceManager_Prop_SetLockTimeAfterAvoid, nullptr, nullptr },
	{ (char*)"LockTimeAfterClean", (getter)FNePyObject_AvoidanceManager_Prop_GetLockTimeAfterClean, (setter)FNePyObject_AvoidanceManager_Prop_SetLockTimeAfterClean, nullptr, nullptr },
	{ (char*)"DeltaTimeToPredict", (getter)FNePyObject_AvoidanceManager_Prop_GetDeltaTimeToPredict, (setter)FNePyObject_AvoidanceManager_Prop_SetDeltaTimeToPredict, nullptr, nullptr },
	{ (char*)"ArtificialRadiusExpansion", (getter)FNePyObject_AvoidanceManager_Prop_GetArtificialRadiusExpansion, (setter)FNePyObject_AvoidanceManager_Prop_SetArtificialRadiusExpansion, nullptr, nullptr },
	{ (char*)"HeightCheckMargin", (getter)FNePyObject_AvoidanceManager_Prop_GetHeightCheckMargin, (setter)FNePyObject_AvoidanceManager_Prop_SetHeightCheckMargin, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_AvoidanceManager_GetAvoidanceVelocityForComponent(FNePyObject_AvoidanceManager* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetAvoidanceVelocityForComponent'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	UMovementComponent* MovementComp;
	if (PyArgs[0] == Py_None)
	{
		MovementComp = nullptr;
	}
	else if (FNePyObject_MovementComponent* PyMovementComp = NePyObjectCheck_MovementComponent(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyMovementComp))
		{
			MovementComp = PyMovementComp->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'MovementComp' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'MovementComp' must have type 'MovementComponent'");
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetAvoidanceVelocityForComponent(MovementComp);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_AvoidanceManager_RegisterMovementComponent(FNePyObject_AvoidanceManager* InSelf, PyObject* InArgs)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'RegisterMovementComponent'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "O|O:RegisterMovementComponent", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	UMovementComponent* MovementComp;
	if (PyArgs[0] == Py_None)
	{
		MovementComp = nullptr;
	}
	else if (FNePyObject_MovementComponent* PyMovementComp = NePyObjectCheck_MovementComponent(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyMovementComp))
		{
			MovementComp = PyMovementComp->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'MovementComp' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'MovementComp' must have type 'MovementComponent'");
		return nullptr;
	}

	float AvoidanceWeight = 0.500000f;
	if (PyArgs[1])
	{
		if (!NePyBase::ToCpp(PyArgs[1], AvoidanceWeight))
		{
			PyErr_SetString(PyExc_TypeError, "arg2 'AvoidanceWeight' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = InSelf->GetValue()->RegisterMovementComponent(MovementComp, AvoidanceWeight);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_AvoidanceManager_GetNewAvoidanceUID(FNePyObject_AvoidanceManager* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetNewAvoidanceUID'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetNewAvoidanceUID();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyObject_AvoidanceManager_GetObjectCount(FNePyObject_AvoidanceManager* InSelf)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'GetObjectCount'"))
	{
		return nullptr;
	}

	auto RetVal = InSelf->GetValue()->GetObjectCount();

	PyObject* PyRetVal0 = PyLong_FromLong(RetVal);
	return PyRetVal0;
}
// region func body end

static PyObject* FNePyObject_AvoidanceManager_Class(PyObject* InSelf) {
	UClass* Class = UAvoidanceManager::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_AvoidanceManager_methods[] = {
	{"GetAvoidanceVelocityForComponent", NePyCFunctionCast(&FNePyObject_AvoidanceManager_GetAvoidanceVelocityForComponent), METH_O, ""},
	{"RegisterMovementComponent", NePyCFunctionCast(&FNePyObject_AvoidanceManager_RegisterMovementComponent), METH_VARARGS, ""},
	{"GetNewAvoidanceUID", NePyCFunctionCast(&FNePyObject_AvoidanceManager_GetNewAvoidanceUID), METH_NOARGS, ""},
	{"GetObjectCount", NePyCFunctionCast(&FNePyObject_AvoidanceManager_GetObjectCount), METH_NOARGS, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_AvoidanceManager_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_AvoidanceManager* NePyObjectNew_AvoidanceManager(UAvoidanceManager* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_AvoidanceManager));
	FNePyObject_AvoidanceManager* RetValue = (FNePyObject_AvoidanceManager*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_AvoidanceManager* NePyObjectCheck_AvoidanceManager(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_AvoidanceManager))
	{
		return (FNePyObject_AvoidanceManager*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_AvoidanceManager()
{
	return &FNePyObjectType_AvoidanceManager;
}

PyTypeObject* NePyNePyWrappedClassInit_AvoidanceManager(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_AvoidanceManager;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_AvoidanceManager_getset;
	NePyObjectType->tp_methods = FNePyObjectType_AvoidanceManager_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_AvoidanceManager,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_AvoidanceManager(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UAvoidanceManager::StaticClass(), NePyNePyWrappedClassInit_AvoidanceManager);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UAvoidanceManager*& OutVal)
	{
		if (FNePyObject_AvoidanceManager* PyObj = NePyObjectCheck_AvoidanceManager(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif