// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_WindDirectionalSource.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_WindDirectionalSource = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"WindDirectionalSource", /* tp_name */
	sizeof(FNePyObject_WindDirectionalSource), /* tp_basicsize */
};

static PyObject* FNePyObject_WindDirectionalSource_Class(PyObject* InSelf) {
	UClass* Class = AWindDirectionalSource::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_WindDirectionalSource_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_WindDirectionalSource_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_WindDirectionalSource* NePyObjectNew_WindDirectionalSource(AWindDirectionalSource* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_WindDirectionalSource));
	FNePyObject_WindDirectionalSource* RetValue = (FNePyObject_WindDirectionalSource*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_WindDirectionalSource* NePyObjectCheck_WindDirectionalSource(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_WindDirectionalSource))
	{
		return (FNePyObject_WindDirectionalSource*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_WindDirectionalSource()
{
	return &FNePyObjectType_WindDirectionalSource;
}

PyTypeObject* NePyNePyWrappedClassInit_WindDirectionalSource(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_WindDirectionalSource;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_WindDirectionalSource_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_WindDirectionalSource,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_WindDirectionalSource(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		AWindDirectionalSource::StaticClass(), NePyNePyWrappedClassInit_WindDirectionalSource);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, AWindDirectionalSource*& OutVal)
	{
		if (FNePyObject_WindDirectionalSource* PyObj = NePyObjectCheck_WindDirectionalSource(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif