// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_LensImperfectionSettings.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_Texture.h"
#include "NePy/Auto/core/NePyStruct_LinearColor.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_LensImperfectionSettings = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"LensImperfectionSettings", /* tp_name */
	sizeof(FNePyStruct_LensImperfectionSettings), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_LensImperfectionSettings_GetDirtMask(FNePyStruct_LensImperfectionSettings* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyBase::ToPy(((FLensImperfectionSettings*)InSelf->Value)->DirtMask);
	return RetValue;
}

int FNePyStruct_LensImperfectionSettings_SetDirtMask(FNePyStruct_LensImperfectionSettings* InSelf, PyObject* InValue, void* InClosure)
{
	if (InValue == Py_None)
	{
		((FLensImperfectionSettings*)InSelf->Value)->DirtMask = nullptr;
	}
	else if (FNePyObject_Texture* PyDirtMask = NePyObjectCheck_Texture(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyDirtMask))
		{
			((FLensImperfectionSettings*)InSelf->Value)->DirtMask = PyDirtMask->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Texture'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_LensImperfectionSettings_GetDirtMaskIntensity(FNePyStruct_LensImperfectionSettings* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FLensImperfectionSettings*)InSelf->Value)->DirtMaskIntensity);
	return RetValue;
}

int FNePyStruct_LensImperfectionSettings_SetDirtMaskIntensity(FNePyStruct_LensImperfectionSettings* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FLensImperfectionSettings*)InSelf->Value)->DirtMaskIntensity))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_LensImperfectionSettings_GetDirtMaskTint(FNePyStruct_LensImperfectionSettings* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyStructNew_LinearColor(((FLensImperfectionSettings*)InSelf->Value)->DirtMaskTint);
	return RetValue;
}

int FNePyStruct_LensImperfectionSettings_SetDirtMaskTint(FNePyStruct_LensImperfectionSettings* InSelf, PyObject* InValue, void* InClosure)
{
	if (FNePyStruct_LinearColor* PyDirtMaskTint = NePyStructCheck_LinearColor(InValue))
	{
		((FLensImperfectionSettings*)InSelf->Value)->DirtMaskTint = *((FLinearColor*)PyDirtMaskTint->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'LinearColor'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_LensImperfectionSettings_getset[] = {
	{ (char*)"DirtMask", (getter)FNePyStruct_LensImperfectionSettings_GetDirtMask, (setter)FNePyStruct_LensImperfectionSettings_SetDirtMask, nullptr, nullptr },
	{ (char*)"DirtMaskIntensity", (getter)FNePyStruct_LensImperfectionSettings_GetDirtMaskIntensity, (setter)FNePyStruct_LensImperfectionSettings_SetDirtMaskIntensity, nullptr, nullptr },
	{ (char*)"DirtMaskTint", (getter)FNePyStruct_LensImperfectionSettings_GetDirtMaskTint, (setter)FNePyStruct_LensImperfectionSettings_SetDirtMaskTint, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_LensImperfectionSettings(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_LensImperfectionSettings* PyObj = NePyStructCheck_LensImperfectionSettings(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_LensImperfectionSettings(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_LensImperfectionSettings;
	FNePyStruct_LensImperfectionSettings* PyObj = (FNePyStruct_LensImperfectionSettings*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FLensImperfectionSettings*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FLensImperfectionSettings*)FMemory::Malloc(sizeof(FLensImperfectionSettings), alignof(FLensImperfectionSettings));
	NePyBase::EnsureCopyToStructSafely<FLensImperfectionSettings>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_LensImperfectionSettings(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_LensImperfectionSettings;
	TNePyStructBase<FLensImperfectionSettings>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_LensImperfectionSettings_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_LensImperfectionSettings,
			(NePyStructPropGet)NePyStructPropGet_LensImperfectionSettings,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_LensImperfectionSettings(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FLensImperfectionSettings>::Get(), NePyNePyWrappedStructInit_LensImperfectionSettings);
}

FNePyStruct_LensImperfectionSettings* NePyStructNew_LensImperfectionSettings(const FLensImperfectionSettings& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_LensImperfectionSettings;
	FNePyStruct_LensImperfectionSettings* RetValue = (FNePyStruct_LensImperfectionSettings*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_LensImperfectionSettings::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FLensImperfectionSettings(InValue);
	return RetValue;
}

FNePyStruct_LensImperfectionSettings* NePyStructCheck_LensImperfectionSettings(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_LensImperfectionSettings))
	{
		return (FNePyStruct_LensImperfectionSettings*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_LensImperfectionSettings()
{
	return &FNePyStructType_LensImperfectionSettings;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FLensImperfectionSettings& OutVal)
	{
		if (FNePyStruct_LensImperfectionSettings* PyObj = NePyStructCheck_LensImperfectionSettings(InPyObj))
		{
			OutVal = *(FLensImperfectionSettings*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FLensImperfectionSettings& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_LensImperfectionSettings(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif