// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_ComponentSync.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_ComponentSync = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"ComponentSync", /* tp_name */
	sizeof(FNePyStruct_ComponentSync), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_ComponentSync_GetName(FNePyStruct_ComponentSync* InSelf, void* InClosure)
{
	PyObject* RetValue;
	if (!NePyBase::ToPy(((FComponentSync*)InSelf->Value)->Name, RetValue))
	{
		PyErr_SetString(PyExc_TypeError, "convert to str failed, src type is 'Name'");
		return nullptr;
	}
	return RetValue;
}

int FNePyStruct_ComponentSync_SetName(FNePyStruct_ComponentSync* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FComponentSync*)InSelf->Value)->Name))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Name'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_ComponentSync_GetSyncOption(FNePyStruct_ComponentSync* InSelf, void* InClosure)
{
	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)((FComponentSync*)InSelf->Value)->SyncOption);
	return RetValue;
}

int FNePyStruct_ComponentSync_SetSyncOption(FNePyStruct_ComponentSync* InSelf, PyObject* InValue, void* InClosure)
{
	uint8 SyncOptionTemp;
	if (!NePyBase::ToCpp(InValue, SyncOptionTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(ESyncOption)");
		return -1;
	}
	((FComponentSync*)InSelf->Value)->SyncOption = (ESyncOption)SyncOptionTemp;
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_ComponentSync_getset[] = {
	{ (char*)"Name", (getter)FNePyStruct_ComponentSync_GetName, (setter)FNePyStruct_ComponentSync_SetName, nullptr, nullptr },
	{ (char*)"SyncOption", (getter)FNePyStruct_ComponentSync_GetSyncOption, (setter)FNePyStruct_ComponentSync_SetSyncOption, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_ComponentSync(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_ComponentSync* PyObj = NePyStructCheck_ComponentSync(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_ComponentSync(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_ComponentSync;
	FNePyStruct_ComponentSync* PyObj = (FNePyStruct_ComponentSync*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FComponentSync*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FComponentSync*)FMemory::Malloc(sizeof(FComponentSync), alignof(FComponentSync));
	NePyBase::EnsureCopyToStructSafely<FComponentSync>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_ComponentSync(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_ComponentSync;
	TNePyStructBase<FComponentSync>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_ComponentSync_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_ComponentSync,
			(NePyStructPropGet)NePyStructPropGet_ComponentSync,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_ComponentSync(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FComponentSync>::Get(), NePyNePyWrappedStructInit_ComponentSync);
}

FNePyStruct_ComponentSync* NePyStructNew_ComponentSync(const FComponentSync& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_ComponentSync;
	FNePyStruct_ComponentSync* RetValue = (FNePyStruct_ComponentSync*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_ComponentSync::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FComponentSync(InValue);
	return RetValue;
}

FNePyStruct_ComponentSync* NePyStructCheck_ComponentSync(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_ComponentSync))
	{
		return (FNePyStruct_ComponentSync*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_ComponentSync()
{
	return &FNePyStructType_ComponentSync;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FComponentSync& OutVal)
	{
		if (FNePyStruct_ComponentSync* PyObj = NePyStructCheck_ComponentSync(InPyObj))
		{
			OutVal = *(FComponentSync*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FComponentSync& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_ComponentSync(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif