// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_CachedAnimRelevancyData.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_CachedAnimRelevancyData = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"CachedAnimRelevancyData", /* tp_name */
	sizeof(FNePyStruct_CachedAnimRelevancyData), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_CachedAnimRelevancyData_GetStateMachineName(FNePyStruct_CachedAnimRelevancyData* InSelf, void* InClosure)
{
	PyObject* RetValue;
	if (!NePyBase::ToPy(((FCachedAnimRelevancyData*)InSelf->Value)->StateMachineName, RetValue))
	{
		PyErr_SetString(PyExc_TypeError, "convert to str failed, src type is 'Name'");
		return nullptr;
	}
	return RetValue;
}

int FNePyStruct_CachedAnimRelevancyData_SetStateMachineName(FNePyStruct_CachedAnimRelevancyData* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FCachedAnimRelevancyData*)InSelf->Value)->StateMachineName))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Name'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_CachedAnimRelevancyData_GetStateName(FNePyStruct_CachedAnimRelevancyData* InSelf, void* InClosure)
{
	PyObject* RetValue;
	if (!NePyBase::ToPy(((FCachedAnimRelevancyData*)InSelf->Value)->StateName, RetValue))
	{
		PyErr_SetString(PyExc_TypeError, "convert to str failed, src type is 'Name'");
		return nullptr;
	}
	return RetValue;
}

int FNePyStruct_CachedAnimRelevancyData_SetStateName(FNePyStruct_CachedAnimRelevancyData* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FCachedAnimRelevancyData*)InSelf->Value)->StateName))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Name'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_CachedAnimRelevancyData_getset[] = {
	{ (char*)"StateMachineName", (getter)FNePyStruct_CachedAnimRelevancyData_GetStateMachineName, (setter)FNePyStruct_CachedAnimRelevancyData_SetStateMachineName, nullptr, nullptr },
	{ (char*)"StateName", (getter)FNePyStruct_CachedAnimRelevancyData_GetStateName, (setter)FNePyStruct_CachedAnimRelevancyData_SetStateName, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_CachedAnimRelevancyData(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_CachedAnimRelevancyData* PyObj = NePyStructCheck_CachedAnimRelevancyData(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_CachedAnimRelevancyData(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_CachedAnimRelevancyData;
	FNePyStruct_CachedAnimRelevancyData* PyObj = (FNePyStruct_CachedAnimRelevancyData*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FCachedAnimRelevancyData*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FCachedAnimRelevancyData*)FMemory::Malloc(sizeof(FCachedAnimRelevancyData), alignof(FCachedAnimRelevancyData));
	NePyBase::EnsureCopyToStructSafely<FCachedAnimRelevancyData>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_CachedAnimRelevancyData(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_CachedAnimRelevancyData;
	TNePyStructBase<FCachedAnimRelevancyData>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_CachedAnimRelevancyData_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_CachedAnimRelevancyData,
			(NePyStructPropGet)NePyStructPropGet_CachedAnimRelevancyData,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_CachedAnimRelevancyData(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FCachedAnimRelevancyData>::Get(), NePyNePyWrappedStructInit_CachedAnimRelevancyData);
}

FNePyStruct_CachedAnimRelevancyData* NePyStructNew_CachedAnimRelevancyData(const FCachedAnimRelevancyData& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_CachedAnimRelevancyData;
	FNePyStruct_CachedAnimRelevancyData* RetValue = (FNePyStruct_CachedAnimRelevancyData*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_CachedAnimRelevancyData::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FCachedAnimRelevancyData(InValue);
	return RetValue;
}

FNePyStruct_CachedAnimRelevancyData* NePyStructCheck_CachedAnimRelevancyData(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_CachedAnimRelevancyData))
	{
		return (FNePyStruct_CachedAnimRelevancyData*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_CachedAnimRelevancyData()
{
	return &FNePyStructType_CachedAnimRelevancyData;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FCachedAnimRelevancyData& OutVal)
	{
		if (FNePyStruct_CachedAnimRelevancyData* PyObj = NePyStructCheck_CachedAnimRelevancyData(InPyObj))
		{
			OutVal = *(FCachedAnimRelevancyData*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FCachedAnimRelevancyData& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_CachedAnimRelevancyData(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif