// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_FXSystemAsset.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_FXSystemAsset = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"FXSystemAsset", /* tp_name */
	sizeof(FNePyObject_FXSystemAsset), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_FXSystemAsset_Prop_GetMaxPoolSize(FNePyObject_FXSystemAsset* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'MaxPoolSize'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong(InSelf->GetValue()->MaxPoolSize);
	return RetValue;
}

int FNePyObject_FXSystemAsset_Prop_SetMaxPoolSize(FNePyObject_FXSystemAsset* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'MaxPoolSize'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->MaxPoolSize))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_FXSystemAsset_Prop_GetPoolPrimeSize(FNePyObject_FXSystemAsset* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'PoolPrimeSize'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromUnsignedLong(InSelf->GetValue()->PoolPrimeSize);
	return RetValue;
}

int FNePyObject_FXSystemAsset_Prop_SetPoolPrimeSize(FNePyObject_FXSystemAsset* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'PoolPrimeSize'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->PoolPrimeSize))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_FXSystemAsset_getset[] = {
	{ (char*)"MaxPoolSize", (getter)FNePyObject_FXSystemAsset_Prop_GetMaxPoolSize, (setter)FNePyObject_FXSystemAsset_Prop_SetMaxPoolSize, nullptr, nullptr },
	{ (char*)"PoolPrimeSize", (getter)FNePyObject_FXSystemAsset_Prop_GetPoolPrimeSize, (setter)FNePyObject_FXSystemAsset_Prop_SetPoolPrimeSize, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

static PyObject* FNePyObject_FXSystemAsset_Class(PyObject* InSelf) {
	UClass* Class = UFXSystemAsset::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_FXSystemAsset_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_FXSystemAsset_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_FXSystemAsset* NePyObjectNew_FXSystemAsset(UFXSystemAsset* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_FXSystemAsset));
	FNePyObject_FXSystemAsset* RetValue = (FNePyObject_FXSystemAsset*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_FXSystemAsset* NePyObjectCheck_FXSystemAsset(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_FXSystemAsset))
	{
		return (FNePyObject_FXSystemAsset*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_FXSystemAsset()
{
	return &FNePyObjectType_FXSystemAsset;
}

PyTypeObject* NePyNePyWrappedClassInit_FXSystemAsset(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_FXSystemAsset;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_FXSystemAsset_getset;
	NePyObjectType->tp_methods = FNePyObjectType_FXSystemAsset_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_FXSystemAsset,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_FXSystemAsset(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UFXSystemAsset::StaticClass(), NePyNePyWrappedClassInit_FXSystemAsset);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UFXSystemAsset*& OutVal)
	{
		if (FNePyObject_FXSystemAsset* PyObj = NePyObjectCheck_FXSystemAsset(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif