// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_LocalFogVolumeComponent.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/core/NePyStruct_LinearColor.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_LocalFogVolumeComponent = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"LocalFogVolumeComponent", /* tp_name */
	sizeof(FNePyObject_LocalFogVolumeComponent), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetRadialFogExtinction(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'RadialFogExtinction'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->RadialFogExtinction);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetRadialFogExtinction(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'RadialFogExtinction'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->RadialFogExtinction))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetHeightFogExtinction(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightFogExtinction'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->HeightFogExtinction);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetHeightFogExtinction(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightFogExtinction'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->HeightFogExtinction))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetHeightFogFalloff(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightFogFalloff'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->HeightFogFalloff);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetHeightFogFalloff(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightFogFalloff'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->HeightFogFalloff))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetHeightFogOffset(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightFogOffset'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->HeightFogOffset);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetHeightFogOffset(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'HeightFogOffset'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->HeightFogOffset))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetFogPhaseG(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogPhaseG'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->FogPhaseG);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetFogPhaseG(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogPhaseG'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->FogPhaseG))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetFogAlbedo(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogAlbedo'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_LinearColor(InSelf->GetValue()->FogAlbedo);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetFogAlbedo(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogAlbedo'"))
	{
		return -1;
	}

	if (FNePyStruct_LinearColor* PyFogAlbedo = NePyStructCheck_LinearColor(InValue))
	{
		InSelf->GetValue()->FogAlbedo = *((FLinearColor*)PyFogAlbedo->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'LinearColor'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetFogEmissive(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogEmissive'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_LinearColor(InSelf->GetValue()->FogEmissive);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetFogEmissive(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogEmissive'"))
	{
		return -1;
	}

	if (FNePyStruct_LinearColor* PyFogEmissive = NePyStructCheck_LinearColor(InValue))
	{
		InSelf->GetValue()->FogEmissive = *((FLinearColor*)PyFogEmissive->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'LinearColor'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_LocalFogVolumeComponent_Prop_GetFogSortPriority(FNePyObject_LocalFogVolumeComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogSortPriority'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyLong_FromLong(InSelf->GetValue()->FogSortPriority);
	return RetValue;
}

int FNePyObject_LocalFogVolumeComponent_Prop_SetFogSortPriority(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FogSortPriority'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->FogSortPriority))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_LocalFogVolumeComponent_getset[] = {
	{ (char*)"RadialFogExtinction", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetRadialFogExtinction, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetRadialFogExtinction, nullptr, nullptr },
	{ (char*)"HeightFogExtinction", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetHeightFogExtinction, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetHeightFogExtinction, nullptr, nullptr },
	{ (char*)"HeightFogFalloff", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetHeightFogFalloff, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetHeightFogFalloff, nullptr, nullptr },
	{ (char*)"HeightFogOffset", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetHeightFogOffset, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetHeightFogOffset, nullptr, nullptr },
	{ (char*)"FogPhaseG", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetFogPhaseG, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetFogPhaseG, nullptr, nullptr },
	{ (char*)"FogAlbedo", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetFogAlbedo, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetFogAlbedo, nullptr, nullptr },
	{ (char*)"FogEmissive", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetFogEmissive, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetFogEmissive, nullptr, nullptr },
	{ (char*)"FogSortPriority", (getter)FNePyObject_LocalFogVolumeComponent_Prop_GetFogSortPriority, (setter)FNePyObject_LocalFogVolumeComponent_Prop_SetFogSortPriority, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_LocalFogVolumeComponent_SetFogEmissive(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetFogEmissive'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FLinearColor* NewValue;
	if (FNePyStruct_LinearColor* PyNewValue = NePyStructCheck_LinearColor(PyArgs[0]))
	{
		NewValue = (FLinearColor*)PyNewValue->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'LinearColor'");
		return nullptr;
	}

	InSelf->GetValue()->SetFogEmissive(*NewValue);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_LocalFogVolumeComponent_SetFogAlbedo(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetFogAlbedo'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	FLinearColor* NewValue;
	if (FNePyStruct_LinearColor* PyNewValue = NePyStructCheck_LinearColor(PyArgs[0]))
	{
		NewValue = (FLinearColor*)PyNewValue->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'LinearColor'");
		return nullptr;
	}

	InSelf->GetValue()->SetFogAlbedo(*NewValue);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_LocalFogVolumeComponent_SetFogPhaseG(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetFogPhaseG'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	float NewValue;
	if (!NePyBase::ToCpp(PyArgs[0], NewValue))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'float'");
		return nullptr;
	}

	InSelf->GetValue()->SetFogPhaseG(NewValue);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_LocalFogVolumeComponent_SetHeightFogOffset(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetHeightFogOffset'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	float NewValue;
	if (!NePyBase::ToCpp(PyArgs[0], NewValue))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'float'");
		return nullptr;
	}

	InSelf->GetValue()->SetHeightFogOffset(NewValue);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_LocalFogVolumeComponent_SetHeightFogFalloff(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetHeightFogFalloff'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	float NewValue;
	if (!NePyBase::ToCpp(PyArgs[0], NewValue))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'float'");
		return nullptr;
	}

	InSelf->GetValue()->SetHeightFogFalloff(NewValue);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_LocalFogVolumeComponent_SetHeightFogExtinction(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetHeightFogExtinction'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	float NewValue;
	if (!NePyBase::ToCpp(PyArgs[0], NewValue))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'float'");
		return nullptr;
	}

	InSelf->GetValue()->SetHeightFogExtinction(NewValue);
	Py_RETURN_NONE;
}

PyObject* FNePyObject_LocalFogVolumeComponent_SetRadialFogExtinction(FNePyObject_LocalFogVolumeComponent* InSelf, PyObject* InArg)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'SetRadialFogExtinction'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[1] = {InArg};

	float NewValue;
	if (!NePyBase::ToCpp(PyArgs[0], NewValue))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NewValue' must have type 'float'");
		return nullptr;
	}

	InSelf->GetValue()->SetRadialFogExtinction(NewValue);
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_LocalFogVolumeComponent_Class(PyObject* InSelf) {
	UClass* Class = ULocalFogVolumeComponent::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_LocalFogVolumeComponent_methods[] = {
	{"SetFogEmissive", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetFogEmissive), METH_O, ""},
	{"SetFogAlbedo", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetFogAlbedo), METH_O, ""},
	{"SetFogPhaseG", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetFogPhaseG), METH_O, ""},
	{"SetHeightFogOffset", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetHeightFogOffset), METH_O, ""},
	{"SetHeightFogFalloff", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetHeightFogFalloff), METH_O, ""},
	{"SetHeightFogExtinction", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetHeightFogExtinction), METH_O, ""},
	{"SetRadialFogExtinction", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_SetRadialFogExtinction), METH_O, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_LocalFogVolumeComponent_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_LocalFogVolumeComponent* NePyObjectNew_LocalFogVolumeComponent(ULocalFogVolumeComponent* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_LocalFogVolumeComponent));
	FNePyObject_LocalFogVolumeComponent* RetValue = (FNePyObject_LocalFogVolumeComponent*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_LocalFogVolumeComponent* NePyObjectCheck_LocalFogVolumeComponent(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_LocalFogVolumeComponent))
	{
		return (FNePyObject_LocalFogVolumeComponent*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_LocalFogVolumeComponent()
{
	return &FNePyObjectType_LocalFogVolumeComponent;
}

PyTypeObject* NePyNePyWrappedClassInit_LocalFogVolumeComponent(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_LocalFogVolumeComponent;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_LocalFogVolumeComponent_getset;
	NePyObjectType->tp_methods = FNePyObjectType_LocalFogVolumeComponent_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_LocalFogVolumeComponent,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_LocalFogVolumeComponent(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		ULocalFogVolumeComponent::StaticClass(), NePyNePyWrappedClassInit_LocalFogVolumeComponent);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, ULocalFogVolumeComponent*& OutVal)
	{
		if (FNePyObject_LocalFogVolumeComponent* PyObj = NePyObjectCheck_LocalFogVolumeComponent(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif