// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_AnimationCurveData.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePyArrayWrapper.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_AnimationCurveData = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"AnimationCurveData", /* tp_name */
	sizeof(FNePyStruct_AnimationCurveData), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_AnimationCurveData_GetFloatCurves(FNePyStruct_AnimationCurveData* InSelf, void* InClosure)
{
	PyObject* RetValue = FNePyStructArrayWrapper::New(InSelf, TBaseStructure<FAnimationCurveData>::Get(), InSelf->Value, &((FAnimationCurveData*)InSelf->Value)->FloatCurves, "FloatCurves");
	return RetValue;
}

int FNePyStruct_AnimationCurveData_SetFloatCurves(FNePyStruct_AnimationCurveData* InSelf, PyObject* InValue, void* InClosure)
{
	if (!FNePyArrayWrapper::Assign(InValue, TBaseStructure<FAnimationCurveData>::Get(), InSelf->Value, &((FAnimationCurveData*)InSelf->Value)->FloatCurves, "FloatCurves"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(FloatCurve)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_AnimationCurveData_GetTransformCurves(FNePyStruct_AnimationCurveData* InSelf, void* InClosure)
{
	PyObject* RetValue = FNePyStructArrayWrapper::New(InSelf, TBaseStructure<FAnimationCurveData>::Get(), InSelf->Value, &((FAnimationCurveData*)InSelf->Value)->TransformCurves, "TransformCurves");
	return RetValue;
}

int FNePyStruct_AnimationCurveData_SetTransformCurves(FNePyStruct_AnimationCurveData* InSelf, PyObject* InValue, void* InClosure)
{
	if (!FNePyArrayWrapper::Assign(InValue, TBaseStructure<FAnimationCurveData>::Get(), InSelf->Value, &((FAnimationCurveData*)InSelf->Value)->TransformCurves, "TransformCurves"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(TransformCurve)'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_AnimationCurveData_getset[] = {
	{ (char*)"FloatCurves", (getter)FNePyStruct_AnimationCurveData_GetFloatCurves, (setter)FNePyStruct_AnimationCurveData_SetFloatCurves, nullptr, nullptr },
	{ (char*)"TransformCurves", (getter)FNePyStruct_AnimationCurveData_GetTransformCurves, (setter)FNePyStruct_AnimationCurveData_SetTransformCurves, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_AnimationCurveData(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_AnimationCurveData* PyObj = NePyStructCheck_AnimationCurveData(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_AnimationCurveData(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_AnimationCurveData;
	FNePyStruct_AnimationCurveData* PyObj = (FNePyStruct_AnimationCurveData*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FAnimationCurveData*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FAnimationCurveData*)FMemory::Malloc(sizeof(FAnimationCurveData), alignof(FAnimationCurveData));
	NePyBase::EnsureCopyToStructSafely<FAnimationCurveData>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_AnimationCurveData(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_AnimationCurveData;
	TNePyStructBase<FAnimationCurveData>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_AnimationCurveData_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_AnimationCurveData,
			(NePyStructPropGet)NePyStructPropGet_AnimationCurveData,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_AnimationCurveData(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FAnimationCurveData>::Get(), NePyNePyWrappedStructInit_AnimationCurveData);
}

FNePyStruct_AnimationCurveData* NePyStructNew_AnimationCurveData(const FAnimationCurveData& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_AnimationCurveData;
	FNePyStruct_AnimationCurveData* RetValue = (FNePyStruct_AnimationCurveData*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_AnimationCurveData::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FAnimationCurveData(InValue);
	return RetValue;
}

FNePyStruct_AnimationCurveData* NePyStructCheck_AnimationCurveData(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_AnimationCurveData))
	{
		return (FNePyStruct_AnimationCurveData*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_AnimationCurveData()
{
	return &FNePyStructType_AnimationCurveData;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FAnimationCurveData& OutVal)
	{
		if (FNePyStruct_AnimationCurveData* PyObj = NePyStructCheck_AnimationCurveData(InPyObj))
		{
			OutVal = *(FAnimationCurveData*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FAnimationCurveData& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_AnimationCurveData(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif