// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_MaterialFunctionInstance.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_MaterialFunctionInterface.h"
#include "NePyArrayWrapper.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_MaterialFunctionInstance = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"MaterialFunctionInstance", /* tp_name */
	sizeof(FNePyObject_MaterialFunctionInstance), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetParent(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Parent'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyBase::ToPy(InSelf->GetValue()->Parent);
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetParent(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Parent'"))
	{
		return -1;
	}

	if (InValue == Py_None)
	{
		InSelf->GetValue()->Parent = nullptr;
	}
	else if (FNePyObject_MaterialFunctionInterface* PyParent = NePyObjectCheck_MaterialFunctionInterface(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyParent))
		{
			InSelf->GetValue()->Parent = PyParent->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'MaterialFunctionInterface'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetBase(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Base'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyBase::ToPy(InSelf->GetValue()->Base);
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetBase(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'Base'"))
	{
		return -1;
	}

	if (InValue == Py_None)
	{
		InSelf->GetValue()->Base = nullptr;
	}
	else if (FNePyObject_MaterialFunctionInterface* PyBase = NePyObjectCheck_MaterialFunctionInterface(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyBase))
		{
			InSelf->GetValue()->Base = PyBase->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'MaterialFunctionInterface'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetScalarParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ScalarParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->ScalarParameterValues, "ScalarParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetScalarParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'ScalarParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->ScalarParameterValues, "ScalarParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(ScalarParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetVectorParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VectorParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->VectorParameterValues, "VectorParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetVectorParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'VectorParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->VectorParameterValues, "VectorParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(VectorParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetDoubleVectorParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DoubleVectorParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->DoubleVectorParameterValues, "DoubleVectorParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetDoubleVectorParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'DoubleVectorParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->DoubleVectorParameterValues, "DoubleVectorParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(DoubleVectorParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetTextureParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'TextureParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->TextureParameterValues, "TextureParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetTextureParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'TextureParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->TextureParameterValues, "TextureParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(TextureParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetTextureCollectionParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'TextureCollectionParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->TextureCollectionParameterValues, "TextureCollectionParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetTextureCollectionParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'TextureCollectionParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->TextureCollectionParameterValues, "TextureCollectionParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(TextureCollectionParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetFontParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FontParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->FontParameterValues, "FontParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetFontParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'FontParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->FontParameterValues, "FontParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(FontParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetStaticSwitchParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'StaticSwitchParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->StaticSwitchParameterValues, "StaticSwitchParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetStaticSwitchParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'StaticSwitchParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->StaticSwitchParameterValues, "StaticSwitchParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(StaticSwitchParameter)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetStaticComponentMaskParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'StaticComponentMaskParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->StaticComponentMaskParameterValues, "StaticComponentMaskParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetStaticComponentMaskParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'StaticComponentMaskParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->StaticComponentMaskParameterValues, "StaticComponentMaskParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(StaticComponentMaskParameter)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetRuntimeVirtualTextureParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'RuntimeVirtualTextureParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->RuntimeVirtualTextureParameterValues, "RuntimeVirtualTextureParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetRuntimeVirtualTextureParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'RuntimeVirtualTextureParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->RuntimeVirtualTextureParameterValues, "RuntimeVirtualTextureParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(RuntimeVirtualTextureParameterValue)'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_MaterialFunctionInstance_Prop_GetSparseVolumeTextureParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'SparseVolumeTextureParameterValues'"))
	{
		return nullptr;
	}

	PyObject* RetValue = FNePyArrayWrapper::New(InSelf->GetValue(), &InSelf->GetValue()->SparseVolumeTextureParameterValues, "SparseVolumeTextureParameterValues");
	return RetValue;
}

int FNePyObject_MaterialFunctionInstance_Prop_SetSparseVolumeTextureParameterValues(FNePyObject_MaterialFunctionInstance* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'SparseVolumeTextureParameterValues'"))
	{
		return -1;
	}

	if (!FNePyArrayWrapper::Assign(InValue, InSelf->GetValue()->GetClass(), InSelf->GetValue(), &InSelf->GetValue()->SparseVolumeTextureParameterValues, "SparseVolumeTextureParameterValues"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'list(SparseVolumeTextureParameterValue)'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_MaterialFunctionInstance_getset[] = {
	{ (char*)"Parent", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetParent, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetParent, nullptr, nullptr },
	{ (char*)"Base", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetBase, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetBase, nullptr, nullptr },
	{ (char*)"ScalarParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetScalarParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetScalarParameterValues, nullptr, nullptr },
	{ (char*)"VectorParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetVectorParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetVectorParameterValues, nullptr, nullptr },
	{ (char*)"DoubleVectorParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetDoubleVectorParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetDoubleVectorParameterValues, nullptr, nullptr },
	{ (char*)"TextureParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetTextureParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetTextureParameterValues, nullptr, nullptr },
	{ (char*)"TextureCollectionParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetTextureCollectionParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetTextureCollectionParameterValues, nullptr, nullptr },
	{ (char*)"FontParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetFontParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetFontParameterValues, nullptr, nullptr },
	{ (char*)"StaticSwitchParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetStaticSwitchParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetStaticSwitchParameterValues, nullptr, nullptr },
	{ (char*)"StaticComponentMaskParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetStaticComponentMaskParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetStaticComponentMaskParameterValues, nullptr, nullptr },
	{ (char*)"RuntimeVirtualTextureParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetRuntimeVirtualTextureParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetRuntimeVirtualTextureParameterValues, nullptr, nullptr },
	{ (char*)"SparseVolumeTextureParameterValues", (getter)FNePyObject_MaterialFunctionInstance_Prop_GetSparseVolumeTextureParameterValues, (setter)FNePyObject_MaterialFunctionInstance_Prop_SetSparseVolumeTextureParameterValues, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

static PyObject* FNePyObject_MaterialFunctionInstance_Class(PyObject* InSelf) {
	UClass* Class = UMaterialFunctionInstance::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_MaterialFunctionInstance_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_MaterialFunctionInstance_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_MaterialFunctionInstance* NePyObjectNew_MaterialFunctionInstance(UMaterialFunctionInstance* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_MaterialFunctionInstance));
	FNePyObject_MaterialFunctionInstance* RetValue = (FNePyObject_MaterialFunctionInstance*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_MaterialFunctionInstance* NePyObjectCheck_MaterialFunctionInstance(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_MaterialFunctionInstance))
	{
		return (FNePyObject_MaterialFunctionInstance*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_MaterialFunctionInstance()
{
	return &FNePyObjectType_MaterialFunctionInstance;
}

PyTypeObject* NePyNePyWrappedClassInit_MaterialFunctionInstance(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_MaterialFunctionInstance;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_MaterialFunctionInstance_getset;
	NePyObjectType->tp_methods = FNePyObjectType_MaterialFunctionInstance_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_MaterialFunctionInstance,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_MaterialFunctionInstance(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UMaterialFunctionInstance::StaticClass(), NePyNePyWrappedClassInit_MaterialFunctionInstance);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UMaterialFunctionInstance*& OutVal)
	{
		if (FNePyObject_MaterialFunctionInstance* PyObj = NePyObjectCheck_MaterialFunctionInstance(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif