#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "Audio/AudioPanelWidgetInterface.h"
// region include end

class FNePyObject_AudioPanelWidgetInterface : public FNePyObjectBase
{
public:
	inline UAudioPanelWidgetInterface* GetValue()
	{
		return (UAudioPanelWidgetInterface*)Value;
	}
};

void NePyInitObject_AudioPanelWidgetInterface(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_AudioPanelWidgetInterface* NePyObjectCheck_AudioPanelWidgetInterface(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_AudioPanelWidgetInterface();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UAudioPanelWidgetInterface*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif