// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_SoundWaveEnvelopeDataPerSound.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_SoundWave.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_SoundWaveEnvelopeDataPerSound = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"SoundWaveEnvelopeDataPerSound", /* tp_name */
	sizeof(FNePyStruct_SoundWaveEnvelopeDataPerSound), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_SoundWaveEnvelopeDataPerSound_GetEnvelope(FNePyStruct_SoundWaveEnvelopeDataPerSound* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->Envelope);
	return RetValue;
}

int FNePyStruct_SoundWaveEnvelopeDataPerSound_SetEnvelope(FNePyStruct_SoundWaveEnvelopeDataPerSound* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->Envelope))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_SoundWaveEnvelopeDataPerSound_GetPlaybackTime(FNePyStruct_SoundWaveEnvelopeDataPerSound* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->PlaybackTime);
	return RetValue;
}

int FNePyStruct_SoundWaveEnvelopeDataPerSound_SetPlaybackTime(FNePyStruct_SoundWaveEnvelopeDataPerSound* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->PlaybackTime))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_SoundWaveEnvelopeDataPerSound_GetSoundWave(FNePyStruct_SoundWaveEnvelopeDataPerSound* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyBase::ToPy(((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->SoundWave);
	return RetValue;
}

int FNePyStruct_SoundWaveEnvelopeDataPerSound_SetSoundWave(FNePyStruct_SoundWaveEnvelopeDataPerSound* InSelf, PyObject* InValue, void* InClosure)
{
	if (InValue == Py_None)
	{
		((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->SoundWave = nullptr;
	}
	else if (FNePyObject_SoundWave* PySoundWave = NePyObjectCheck_SoundWave(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PySoundWave))
		{
			((FSoundWaveEnvelopeDataPerSound*)InSelf->Value)->SoundWave = PySoundWave->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'SoundWave'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_SoundWaveEnvelopeDataPerSound_getset[] = {
	{ (char*)"Envelope", (getter)FNePyStruct_SoundWaveEnvelopeDataPerSound_GetEnvelope, (setter)FNePyStruct_SoundWaveEnvelopeDataPerSound_SetEnvelope, nullptr, nullptr },
	{ (char*)"PlaybackTime", (getter)FNePyStruct_SoundWaveEnvelopeDataPerSound_GetPlaybackTime, (setter)FNePyStruct_SoundWaveEnvelopeDataPerSound_SetPlaybackTime, nullptr, nullptr },
	{ (char*)"SoundWave", (getter)FNePyStruct_SoundWaveEnvelopeDataPerSound_GetSoundWave, (setter)FNePyStruct_SoundWaveEnvelopeDataPerSound_SetSoundWave, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_SoundWaveEnvelopeDataPerSound(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_SoundWaveEnvelopeDataPerSound* PyObj = NePyStructCheck_SoundWaveEnvelopeDataPerSound(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_SoundWaveEnvelopeDataPerSound(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_SoundWaveEnvelopeDataPerSound;
	FNePyStruct_SoundWaveEnvelopeDataPerSound* PyObj = (FNePyStruct_SoundWaveEnvelopeDataPerSound*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FSoundWaveEnvelopeDataPerSound*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FSoundWaveEnvelopeDataPerSound*)FMemory::Malloc(sizeof(FSoundWaveEnvelopeDataPerSound), alignof(FSoundWaveEnvelopeDataPerSound));
	NePyBase::EnsureCopyToStructSafely<FSoundWaveEnvelopeDataPerSound>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_SoundWaveEnvelopeDataPerSound(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_SoundWaveEnvelopeDataPerSound;
	TNePyStructBase<FSoundWaveEnvelopeDataPerSound>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_SoundWaveEnvelopeDataPerSound_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_SoundWaveEnvelopeDataPerSound,
			(NePyStructPropGet)NePyStructPropGet_SoundWaveEnvelopeDataPerSound,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_SoundWaveEnvelopeDataPerSound(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FSoundWaveEnvelopeDataPerSound>::Get(), NePyNePyWrappedStructInit_SoundWaveEnvelopeDataPerSound);
}

FNePyStruct_SoundWaveEnvelopeDataPerSound* NePyStructNew_SoundWaveEnvelopeDataPerSound(const FSoundWaveEnvelopeDataPerSound& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_SoundWaveEnvelopeDataPerSound;
	FNePyStruct_SoundWaveEnvelopeDataPerSound* RetValue = (FNePyStruct_SoundWaveEnvelopeDataPerSound*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_SoundWaveEnvelopeDataPerSound::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FSoundWaveEnvelopeDataPerSound(InValue);
	return RetValue;
}

FNePyStruct_SoundWaveEnvelopeDataPerSound* NePyStructCheck_SoundWaveEnvelopeDataPerSound(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_SoundWaveEnvelopeDataPerSound))
	{
		return (FNePyStruct_SoundWaveEnvelopeDataPerSound*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_SoundWaveEnvelopeDataPerSound()
{
	return &FNePyStructType_SoundWaveEnvelopeDataPerSound;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FSoundWaveEnvelopeDataPerSound& OutVal)
	{
		if (FNePyStruct_SoundWaveEnvelopeDataPerSound* PyObj = NePyStructCheck_SoundWaveEnvelopeDataPerSound(InPyObj))
		{
			OutVal = *(FSoundWaveEnvelopeDataPerSound*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FSoundWaveEnvelopeDataPerSound& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_SoundWaveEnvelopeDataPerSound(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif