// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_InputAlphaBoolBlend.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_CurveFloat.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_InputAlphaBoolBlend = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"InputAlphaBoolBlend", /* tp_name */
	sizeof(FNePyStruct_InputAlphaBoolBlend), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_InputAlphaBoolBlend_GetBlendInTime(FNePyStruct_InputAlphaBoolBlend* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FInputAlphaBoolBlend*)InSelf->Value)->BlendInTime);
	return RetValue;
}

int FNePyStruct_InputAlphaBoolBlend_SetBlendInTime(FNePyStruct_InputAlphaBoolBlend* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FInputAlphaBoolBlend*)InSelf->Value)->BlendInTime))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_InputAlphaBoolBlend_GetBlendOutTime(FNePyStruct_InputAlphaBoolBlend* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FInputAlphaBoolBlend*)InSelf->Value)->BlendOutTime);
	return RetValue;
}

int FNePyStruct_InputAlphaBoolBlend_SetBlendOutTime(FNePyStruct_InputAlphaBoolBlend* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FInputAlphaBoolBlend*)InSelf->Value)->BlendOutTime))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_InputAlphaBoolBlend_GetBlendOption(FNePyStruct_InputAlphaBoolBlend* InSelf, void* InClosure)
{
	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)((FInputAlphaBoolBlend*)InSelf->Value)->BlendOption);
	return RetValue;
}

int FNePyStruct_InputAlphaBoolBlend_SetBlendOption(FNePyStruct_InputAlphaBoolBlend* InSelf, PyObject* InValue, void* InClosure)
{
	uint8 BlendOptionTemp;
	if (!NePyBase::ToCpp(InValue, BlendOptionTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EAlphaBlendOption)");
		return -1;
	}
	((FInputAlphaBoolBlend*)InSelf->Value)->BlendOption = (EAlphaBlendOption)BlendOptionTemp;
	return 0;
}

PyObject* FNePyStruct_InputAlphaBoolBlend_GetbInitialized(FNePyStruct_InputAlphaBoolBlend* InSelf, void* InClosure)
{
	PyObject* RetValue = PyBool_FromLong(((FInputAlphaBoolBlend*)InSelf->Value)->bInitialized);
	return RetValue;
}

int FNePyStruct_InputAlphaBoolBlend_SetbInitialized(FNePyStruct_InputAlphaBoolBlend* InSelf, PyObject* InValue, void* InClosure)
{
	bool bInitializedTemp;
	if (!NePyBase::ToCpp(InValue, bInitializedTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'bool'");
		return -1;
	}
	((FInputAlphaBoolBlend*)InSelf->Value)->bInitialized = bInitializedTemp;
	return 0;
}

PyObject* FNePyStruct_InputAlphaBoolBlend_GetCustomCurve(FNePyStruct_InputAlphaBoolBlend* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyBase::ToPy(((FInputAlphaBoolBlend*)InSelf->Value)->CustomCurve);
	return RetValue;
}

int FNePyStruct_InputAlphaBoolBlend_SetCustomCurve(FNePyStruct_InputAlphaBoolBlend* InSelf, PyObject* InValue, void* InClosure)
{
	if (InValue == Py_None)
	{
		((FInputAlphaBoolBlend*)InSelf->Value)->CustomCurve = nullptr;
	}
	else if (FNePyObject_CurveFloat* PyCustomCurve = NePyObjectCheck_CurveFloat(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyCustomCurve))
		{
			((FInputAlphaBoolBlend*)InSelf->Value)->CustomCurve = PyCustomCurve->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'CurveFloat'");
		return -1;
	}
	return 0;
}

// unsupported StructProperty AlphaBlend [type not exported: AlphaBlend]
// region prop getset body end

static PyGetSetDef FNePyStructType_InputAlphaBoolBlend_getset[] = {
	{ (char*)"BlendInTime", (getter)FNePyStruct_InputAlphaBoolBlend_GetBlendInTime, (setter)FNePyStruct_InputAlphaBoolBlend_SetBlendInTime, nullptr, nullptr },
	{ (char*)"BlendOutTime", (getter)FNePyStruct_InputAlphaBoolBlend_GetBlendOutTime, (setter)FNePyStruct_InputAlphaBoolBlend_SetBlendOutTime, nullptr, nullptr },
	{ (char*)"BlendOption", (getter)FNePyStruct_InputAlphaBoolBlend_GetBlendOption, (setter)FNePyStruct_InputAlphaBoolBlend_SetBlendOption, nullptr, nullptr },
	{ (char*)"bInitialized", (getter)FNePyStruct_InputAlphaBoolBlend_GetbInitialized, (setter)FNePyStruct_InputAlphaBoolBlend_SetbInitialized, nullptr, nullptr },
	{ (char*)"CustomCurve", (getter)FNePyStruct_InputAlphaBoolBlend_GetCustomCurve, (setter)FNePyStruct_InputAlphaBoolBlend_SetCustomCurve, nullptr, nullptr },
	// unsupported StructProperty AlphaBlend [type not exported: AlphaBlend],
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_InputAlphaBoolBlend(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_InputAlphaBoolBlend* PyObj = NePyStructCheck_InputAlphaBoolBlend(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_InputAlphaBoolBlend(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_InputAlphaBoolBlend;
	FNePyStruct_InputAlphaBoolBlend* PyObj = (FNePyStruct_InputAlphaBoolBlend*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FInputAlphaBoolBlend*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FInputAlphaBoolBlend*)FMemory::Malloc(sizeof(FInputAlphaBoolBlend), alignof(FInputAlphaBoolBlend));
	NePyBase::EnsureCopyToStructSafely<FInputAlphaBoolBlend>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_InputAlphaBoolBlend(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_InputAlphaBoolBlend;
	TNePyStructBase<FInputAlphaBoolBlend>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_InputAlphaBoolBlend_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_InputAlphaBoolBlend,
			(NePyStructPropGet)NePyStructPropGet_InputAlphaBoolBlend,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_InputAlphaBoolBlend(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FInputAlphaBoolBlend>::Get(), NePyNePyWrappedStructInit_InputAlphaBoolBlend);
}

FNePyStruct_InputAlphaBoolBlend* NePyStructNew_InputAlphaBoolBlend(const FInputAlphaBoolBlend& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_InputAlphaBoolBlend;
	FNePyStruct_InputAlphaBoolBlend* RetValue = (FNePyStruct_InputAlphaBoolBlend*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_InputAlphaBoolBlend::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FInputAlphaBoolBlend(InValue);
	return RetValue;
}

FNePyStruct_InputAlphaBoolBlend* NePyStructCheck_InputAlphaBoolBlend(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_InputAlphaBoolBlend))
	{
		return (FNePyStruct_InputAlphaBoolBlend*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_InputAlphaBoolBlend()
{
	return &FNePyStructType_InputAlphaBoolBlend;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FInputAlphaBoolBlend& OutVal)
	{
		if (FNePyStruct_InputAlphaBoolBlend* PyObj = NePyStructCheck_InputAlphaBoolBlend(InPyObj))
		{
			OutVal = *(FInputAlphaBoolBlend*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FInputAlphaBoolBlend& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_InputAlphaBoolBlend(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif