// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_DataTableFunctionLibrary.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/engine/NePyObject_DataTable.h"
#include "NePy/Auto/engine/NePyObject_CurveTable.h"
#include "NePy/Manual/NePyObject_DataTableFunctionLibrary.inl"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_DataTableFunctionLibrary = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"DataTableFunctionLibrary", /* tp_name */
	sizeof(FNePyObject_DataTableFunctionLibrary), /* tp_basicsize */
};

// region func body begin
PyObject* FNePyObject_DataTableFunctionLibrary_GetDataTableColumnAsString(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:GetDataTableColumnAsString", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	UDataTable* DataTable;
	if (PyArgs[0] == Py_None)
	{
		DataTable = nullptr;
	}
	else if (FNePyObject_DataTable* PyDataTable = NePyObjectCheck_DataTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyDataTable))
		{
			DataTable = PyDataTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'DataTable' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'DataTable' must have type 'DataTable'");
		return nullptr;
	}

	FName PropertyName;
	if (!NePyBase::ToCpp(PyArgs[1], PropertyName))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'PropertyName' must have type 'Name'");
		return nullptr;
	}

	auto RetVal = UDataTableFunctionLibrary::GetDataTableColumnAsString(DataTable, PropertyName);

	int32 RetValNum = (int32)RetVal.Num();
	PyObject* PyRetVal0 = PyList_New(RetValNum);
	for (int32 Index = 0; Index < RetValNum; ++Index)
	{
		const FString& RetValInner = RetVal[Index];
		PyObject* PyRetVal0Inner;
		if (!NePyBase::ToPy(RetValInner, PyRetVal0Inner))
		{
			PyErr_SetString(PyExc_TypeError, "PyRetVal0 'RetVal' with type 'list(str)' convert to PyObject failed!");
			return nullptr;
		}
		PyList_SetItem(PyRetVal0, Index, PyRetVal0Inner);
	}
	return PyRetVal0;
}

PyObject* FNePyObject_DataTableFunctionLibrary_GetDataTableColumnNameFromExportName(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:GetDataTableColumnNameFromExportName", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	UDataTable* Table;
	if (PyArgs[0] == Py_None)
	{
		Table = nullptr;
	}
	else if (FNePyObject_DataTable* PyTable = NePyObjectCheck_DataTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTable))
		{
			Table = PyTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Table' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Table' must have type 'DataTable'");
		return nullptr;
	}

	FString ColumnExportName;
	if (!NePyBase::ToCpp(PyArgs[1], ColumnExportName))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'ColumnExportName' must have type 'str'");
		return nullptr;
	}

	FName OutColumnName;

	auto RetVal = UDataTableFunctionLibrary::GetDataTableColumnNameFromExportName(Table, ColumnExportName, OutColumnName);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	PyObject* PyRetVal1;
	if (!NePyBase::ToPy(OutColumnName, PyRetVal1))
	{
		PyErr_SetString(PyExc_TypeError, "PyRetVal1 'OutColumnName' with type 'Name' convert to PyObject failed!");
		return nullptr;
	}

	PyObject* PyRetVals = PyTuple_New(2);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	return PyRetVals;
}

PyObject* FNePyObject_DataTableFunctionLibrary_GetDataTableColumnExportNames(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	UDataTable* Table;
	if (PyArgs[0] == Py_None)
	{
		Table = nullptr;
	}
	else if (FNePyObject_DataTable* PyTable = NePyObjectCheck_DataTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTable))
		{
			Table = PyTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Table' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Table' must have type 'DataTable'");
		return nullptr;
	}

	TArray<FString> OutExportColumnNames;

	UDataTableFunctionLibrary::GetDataTableColumnExportNames(Table, OutExportColumnNames);

	int32 OutExportColumnNamesNum = (int32)OutExportColumnNames.Num();
	PyObject* PyRetVal0 = PyList_New(OutExportColumnNamesNum);
	for (int32 Index = 0; Index < OutExportColumnNamesNum; ++Index)
	{
		const FString& OutExportColumnNamesInner = OutExportColumnNames[Index];
		PyObject* PyRetVal0Inner;
		if (!NePyBase::ToPy(OutExportColumnNamesInner, PyRetVal0Inner))
		{
			PyErr_SetString(PyExc_TypeError, "PyRetVal0 'OutExportColumnNames' with type 'list(str)' convert to PyObject failed!");
			return nullptr;
		}
		PyList_SetItem(PyRetVal0, Index, PyRetVal0Inner);
	}
	return PyRetVal0;
}

PyObject* FNePyObject_DataTableFunctionLibrary_GetDataTableColumnNames(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	UDataTable* Table;
	if (PyArgs[0] == Py_None)
	{
		Table = nullptr;
	}
	else if (FNePyObject_DataTable* PyTable = NePyObjectCheck_DataTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTable))
		{
			Table = PyTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Table' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Table' must have type 'DataTable'");
		return nullptr;
	}

	TArray<FName> OutColumnNames;

	UDataTableFunctionLibrary::GetDataTableColumnNames(Table, OutColumnNames);

	int32 OutColumnNamesNum = (int32)OutColumnNames.Num();
	PyObject* PyRetVal0 = PyList_New(OutColumnNamesNum);
	for (int32 Index = 0; Index < OutColumnNamesNum; ++Index)
	{
		const FName& OutColumnNamesInner = OutColumnNames[Index];
		PyObject* PyRetVal0Inner;
		if (!NePyBase::ToPy(OutColumnNamesInner, PyRetVal0Inner))
		{
			PyErr_SetString(PyExc_TypeError, "PyRetVal0 'OutColumnNames' with type 'list(Name)' convert to PyObject failed!");
			return nullptr;
		}
		PyList_SetItem(PyRetVal0, Index, PyRetVal0Inner);
	}
	return PyRetVal0;
}

PyObject* FNePyObject_DataTableFunctionLibrary_GetDataTableRowNames(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	UDataTable* Table;
	if (PyArgs[0] == Py_None)
	{
		Table = nullptr;
	}
	else if (FNePyObject_DataTable* PyTable = NePyObjectCheck_DataTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTable))
		{
			Table = PyTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Table' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Table' must have type 'DataTable'");
		return nullptr;
	}

	TArray<FName> OutRowNames;

	UDataTableFunctionLibrary::GetDataTableRowNames(Table, OutRowNames);

	int32 OutRowNamesNum = (int32)OutRowNames.Num();
	PyObject* PyRetVal0 = PyList_New(OutRowNamesNum);
	for (int32 Index = 0; Index < OutRowNamesNum; ++Index)
	{
		const FName& OutRowNamesInner = OutRowNames[Index];
		PyObject* PyRetVal0Inner;
		if (!NePyBase::ToPy(OutRowNamesInner, PyRetVal0Inner))
		{
			PyErr_SetString(PyExc_TypeError, "PyRetVal0 'OutRowNames' with type 'list(Name)' convert to PyObject failed!");
			return nullptr;
		}
		PyList_SetItem(PyRetVal0, Index, PyRetVal0Inner);
	}
	return PyRetVal0;
}

PyObject* FNePyObject_DataTableFunctionLibrary_DoesDataTableRowExist(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:DoesDataTableRowExist", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	UDataTable* Table;
	if (PyArgs[0] == Py_None)
	{
		Table = nullptr;
	}
	else if (FNePyObject_DataTable* PyTable = NePyObjectCheck_DataTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyTable))
		{
			Table = PyTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Table' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Table' must have type 'DataTable'");
		return nullptr;
	}

	FName RowName;
	if (!NePyBase::ToCpp(PyArgs[1], RowName))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'RowName' must have type 'Name'");
		return nullptr;
	}

	auto RetVal = UDataTableFunctionLibrary::DoesDataTableRowExist(Table, RowName);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

// PyObject* FNePyObject_DataTableFunctionLibrary_GetDataTableRowStruct(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArg)
// {
// 	PyObject* PyArgs[1] = {InArg};
// 
// 	UDataTable* Table;
// 	if (PyArgs[0] == Py_None)
// 	{
// 		Table = nullptr;
// 	}
// 	else if (FNePyObject_DataTable* PyTable = NePyObjectCheck_DataTable(PyArgs[0]))
// 	{
// 		if (FNePyHouseKeeper::Get().IsValid(PyTable))
// 		{
// 			Table = PyTable->GetValue();
// 		}
// 		else
// 		{
// 			PyErr_SetString(PyExc_TypeError, "arg1 'Table' underlying UObject is invalid");
// 			return nullptr;
// 		}
// 	}
// 	else
// 	{
// 		PyErr_SetString(PyExc_TypeError, "arg1 'Table' must have type 'DataTable'");
// 		return nullptr;
// 	}
// 
// 	auto RetVal = UDataTableFunctionLibrary::GetDataTableRowStruct(Table);
// 
// 	// unsupported PyRetVal0 ObjectProperty RetVal [return value: class type "ScriptStruct" not exported];
// 
// 	return PyRetVal0;
// }

PyObject* FNePyObject_DataTableFunctionLibrary_EvaluateCurveTableRow(FNePyObject_DataTableFunctionLibrary* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[4] = {nullptr, nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOOO:EvaluateCurveTableRow", &PyArgs[0], &PyArgs[1], &PyArgs[2], &PyArgs[3]))
	{
		return nullptr;
	}

	UCurveTable* CurveTable;
	if (PyArgs[0] == Py_None)
	{
		CurveTable = nullptr;
	}
	else if (FNePyObject_CurveTable* PyCurveTable = NePyObjectCheck_CurveTable(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyCurveTable))
		{
			CurveTable = PyCurveTable->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'CurveTable' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'CurveTable' must have type 'CurveTable'");
		return nullptr;
	}

	FName RowName;
	if (!NePyBase::ToCpp(PyArgs[1], RowName))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'RowName' must have type 'Name'");
		return nullptr;
	}

	float InXY;
	if (!NePyBase::ToCpp(PyArgs[2], InXY))
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'InXY' must have type 'float'");
		return nullptr;
	}

	TEnumAsByte<EEvaluateCurveTableResult::Type> OutResult;

	float OutXY;

	FString ContextString;
	if (!NePyBase::ToCpp(PyArgs[3], ContextString))
	{
		PyErr_SetString(PyExc_TypeError, "arg4 'ContextString' must have type 'str'");
		return nullptr;
	}

	UDataTableFunctionLibrary::EvaluateCurveTableRow(CurveTable, RowName, InXY, OutResult, OutXY, ContextString);

	PyObject* PyRetVal0 = PyLong_FromUnsignedLong((uint8)OutResult);
	PyObject* PyRetVal1 = PyFloat_FromDouble(OutXY);

	PyObject* PyRetVals = PyTuple_New(2);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	return PyRetVals;
}
// region func body end

static PyObject* FNePyObject_DataTableFunctionLibrary_Class(PyObject* InSelf) {
	UClass* Class = UDataTableFunctionLibrary::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_DataTableFunctionLibrary_methods[] = {
	{"GetDataTableColumnAsString", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_GetDataTableColumnAsString), METH_VARARGS | METH_STATIC, ""},
	{"GetDataTableColumnNameFromExportName", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_GetDataTableColumnNameFromExportName), METH_VARARGS | METH_STATIC, ""},
	{"GetDataTableColumnExportNames", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_GetDataTableColumnExportNames), METH_O | METH_STATIC, ""},
	{"GetDataTableColumnNames", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_GetDataTableColumnNames), METH_O | METH_STATIC, ""},
	{"GetDataTableRowNames", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_GetDataTableRowNames), METH_O | METH_STATIC, ""},
	{"DoesDataTableRowExist", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_DoesDataTableRowExist), METH_VARARGS | METH_STATIC, ""},
	// unsupported {"GetDataTableRowStruct", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_GetDataTableRowStruct), METH_O | METH_STATIC, ""}, [return value: class type "ScriptStruct" not exported]
	{"EvaluateCurveTableRow", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_EvaluateCurveTableRow), METH_VARARGS | METH_STATIC, ""},
	NePyManualExportFuncs
	{"Class", NePyCFunctionCast(&FNePyObject_DataTableFunctionLibrary_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_DataTableFunctionLibrary* NePyObjectNew_DataTableFunctionLibrary(UDataTableFunctionLibrary* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_DataTableFunctionLibrary));
	FNePyObject_DataTableFunctionLibrary* RetValue = (FNePyObject_DataTableFunctionLibrary*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_DataTableFunctionLibrary* NePyObjectCheck_DataTableFunctionLibrary(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_DataTableFunctionLibrary))
	{
		return (FNePyObject_DataTableFunctionLibrary*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_DataTableFunctionLibrary()
{
	return &FNePyObjectType_DataTableFunctionLibrary;
}

PyTypeObject* NePyNePyWrappedClassInit_DataTableFunctionLibrary(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_DataTableFunctionLibrary;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_DataTableFunctionLibrary_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_DataTableFunctionLibrary,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_DataTableFunctionLibrary(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UDataTableFunctionLibrary::StaticClass(), NePyNePyWrappedClassInit_DataTableFunctionLibrary);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UDataTableFunctionLibrary*& OutVal)
	{
		if (FNePyObject_DataTableFunctionLibrary* PyObj = NePyObjectCheck_DataTableFunctionLibrary(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif