#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Sound/SoundModulationDestination.h"
// region include end

struct FNePyStruct_SoundModulationDestinationSettings : public TNePyStructBase<FSoundModulationDestinationSettings>
{
};

void NePyInitStruct_SoundModulationDestinationSettings(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_SoundModulationDestinationSettings* NePyStructNew_SoundModulationDestinationSettings(const FSoundModulationDestinationSettings& InValue);

NEPYTHONBINDING_API FNePyStruct_SoundModulationDestinationSettings* NePyStructCheck_SoundModulationDestinationSettings(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_SoundModulationDestinationSettings();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FSoundModulationDestinationSettings& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FSoundModulationDestinationSettings& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif