#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "GameFramework/GameMode.h"
// region include end

class FNePyObject_GameMode : public FNePyObjectBase
{
public:
	inline AGameMode* GetValue()
	{
		return (AGameMode*)Value;
	}
};

void NePyInitObject_GameMode(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_GameMode* NePyObjectCheck_GameMode(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_GameMode();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, AGameMode*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif