// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_RuntimeCurveLinearColor.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePyFixedArrayWrapper.h"
#include "NePy/Auto/engine/NePyObject_CurveLinearColor.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_RuntimeCurveLinearColor = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"RuntimeCurveLinearColor", /* tp_name */
	sizeof(FNePyStruct_RuntimeCurveLinearColor), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_RuntimeCurveLinearColor_GetColorCurves(FNePyStruct_RuntimeCurveLinearColor* InSelf, void* InClosure)
{
	PyObject* RetValue = FNePyStructFixedArrayWrapper::New(InSelf, TBaseStructure<FRuntimeCurveLinearColor>::Get(), InSelf->Value, &((FRuntimeCurveLinearColor*)InSelf->Value)->ColorCurves, "ColorCurves");
	return RetValue;
}

int FNePyStruct_RuntimeCurveLinearColor_SetColorCurves(FNePyStruct_RuntimeCurveLinearColor* InSelf, PyObject* InValue, void* InClosure)
{
	if (!FNePyFixedArrayWrapper::Assign(InValue, TBaseStructure<FRuntimeCurveLinearColor>::Get(), InSelf->Value, &((FRuntimeCurveLinearColor*)InSelf->Value)->ColorCurves, "ColorCurves"))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'RichCurve[4]'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_RuntimeCurveLinearColor_GetExternalCurve(FNePyStruct_RuntimeCurveLinearColor* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyBase::ToPy(((FRuntimeCurveLinearColor*)InSelf->Value)->ExternalCurve);
	return RetValue;
}

int FNePyStruct_RuntimeCurveLinearColor_SetExternalCurve(FNePyStruct_RuntimeCurveLinearColor* InSelf, PyObject* InValue, void* InClosure)
{
	if (InValue == Py_None)
	{
		((FRuntimeCurveLinearColor*)InSelf->Value)->ExternalCurve = nullptr;
	}
	else if (FNePyObject_CurveLinearColor* PyExternalCurve = NePyObjectCheck_CurveLinearColor(InValue))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyExternalCurve))
		{
			((FRuntimeCurveLinearColor*)InSelf->Value)->ExternalCurve = PyExternalCurve->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "Value underlying UObject is invalid");
			return -1;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'CurveLinearColor'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_RuntimeCurveLinearColor_getset[] = {
	{ (char*)"ColorCurves", (getter)FNePyStruct_RuntimeCurveLinearColor_GetColorCurves, (setter)FNePyStruct_RuntimeCurveLinearColor_SetColorCurves, nullptr, nullptr },
	{ (char*)"ExternalCurve", (getter)FNePyStruct_RuntimeCurveLinearColor_GetExternalCurve, (setter)FNePyStruct_RuntimeCurveLinearColor_SetExternalCurve, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_RuntimeCurveLinearColor(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_RuntimeCurveLinearColor* PyObj = NePyStructCheck_RuntimeCurveLinearColor(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_RuntimeCurveLinearColor(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_RuntimeCurveLinearColor;
	FNePyStruct_RuntimeCurveLinearColor* PyObj = (FNePyStruct_RuntimeCurveLinearColor*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FRuntimeCurveLinearColor*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FRuntimeCurveLinearColor*)FMemory::Malloc(sizeof(FRuntimeCurveLinearColor), alignof(FRuntimeCurveLinearColor));
	NePyBase::EnsureCopyToStructSafely<FRuntimeCurveLinearColor>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_RuntimeCurveLinearColor(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_RuntimeCurveLinearColor;
	TNePyStructBase<FRuntimeCurveLinearColor>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_RuntimeCurveLinearColor_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_RuntimeCurveLinearColor,
			(NePyStructPropGet)NePyStructPropGet_RuntimeCurveLinearColor,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_RuntimeCurveLinearColor(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FRuntimeCurveLinearColor>::Get(), NePyNePyWrappedStructInit_RuntimeCurveLinearColor);
}

FNePyStruct_RuntimeCurveLinearColor* NePyStructNew_RuntimeCurveLinearColor(const FRuntimeCurveLinearColor& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_RuntimeCurveLinearColor;
	FNePyStruct_RuntimeCurveLinearColor* RetValue = (FNePyStruct_RuntimeCurveLinearColor*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_RuntimeCurveLinearColor::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FRuntimeCurveLinearColor(InValue);
	return RetValue;
}

FNePyStruct_RuntimeCurveLinearColor* NePyStructCheck_RuntimeCurveLinearColor(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_RuntimeCurveLinearColor))
	{
		return (FNePyStruct_RuntimeCurveLinearColor*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_RuntimeCurveLinearColor()
{
	return &FNePyStructType_RuntimeCurveLinearColor;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FRuntimeCurveLinearColor& OutVal)
	{
		if (FNePyStruct_RuntimeCurveLinearColor* PyObj = NePyStructCheck_RuntimeCurveLinearColor(InPyObj))
		{
			OutVal = *(FRuntimeCurveLinearColor*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FRuntimeCurveLinearColor& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_RuntimeCurveLinearColor(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif