// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_PawnNoiseEmitterComponent.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/core/NePyStruct_Vector.h"
#include "NePy/Auto/engine/NePyObject_Actor.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_PawnNoiseEmitterComponent = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"PawnNoiseEmitterComponent", /* tp_name */
	sizeof(FNePyObject_PawnNoiseEmitterComponent), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyObject_PawnNoiseEmitterComponent_Prop_GetLastRemoteNoisePosition(FNePyObject_PawnNoiseEmitterComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'LastRemoteNoisePosition'"))
	{
		return nullptr;
	}

	PyObject* RetValue = NePyStructNew_Vector(InSelf->GetValue()->LastRemoteNoisePosition);
	return RetValue;
}

int FNePyObject_PawnNoiseEmitterComponent_Prop_SetLastRemoteNoisePosition(FNePyObject_PawnNoiseEmitterComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'LastRemoteNoisePosition'"))
	{
		return -1;
	}

	if (FNePyStruct_Vector* PyLastRemoteNoisePosition = NePyStructCheck_Vector(InValue))
	{
		InSelf->GetValue()->LastRemoteNoisePosition = *((FVector*)PyLastRemoteNoisePosition->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector'");
		return -1;
	}
	return 0;
}

PyObject* FNePyObject_PawnNoiseEmitterComponent_Prop_GetNoiseLifetime(FNePyObject_PawnNoiseEmitterComponent* InSelf, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'NoiseLifetime'"))
	{
		return nullptr;
	}

	PyObject* RetValue = PyFloat_FromDouble(InSelf->GetValue()->NoiseLifetime);
	return RetValue;
}

int FNePyObject_PawnNoiseEmitterComponent_Prop_SetNoiseLifetime(FNePyObject_PawnNoiseEmitterComponent* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "attribute 'NoiseLifetime'"))
	{
		return -1;
	}

	if (!NePyBase::ToCpp(InValue, InSelf->GetValue()->NoiseLifetime))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyObjectType_PawnNoiseEmitterComponent_getset[] = {
	{ (char*)"LastRemoteNoisePosition", (getter)FNePyObject_PawnNoiseEmitterComponent_Prop_GetLastRemoteNoisePosition, (setter)FNePyObject_PawnNoiseEmitterComponent_Prop_SetLastRemoteNoisePosition, nullptr, nullptr },
	{ (char*)"NoiseLifetime", (getter)FNePyObject_PawnNoiseEmitterComponent_Prop_GetNoiseLifetime, (setter)FNePyObject_PawnNoiseEmitterComponent_Prop_SetNoiseLifetime, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyObject_PawnNoiseEmitterComponent_MakeNoise(FNePyObject_PawnNoiseEmitterComponent* InSelf, PyObject* InArgs)
{
	if (!NePyBase::CheckValidAndSetPyErr(InSelf, "method 'MakeNoise'"))
	{
		return nullptr;
	}

	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:MakeNoise", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	AActor* NoiseMaker;
	if (PyArgs[0] == Py_None)
	{
		NoiseMaker = nullptr;
	}
	else if (FNePyObject_Actor* PyNoiseMaker = NePyObjectCheck_Actor(PyArgs[0]))
	{
		if (FNePyHouseKeeper::Get().IsValid(PyNoiseMaker))
		{
			NoiseMaker = PyNoiseMaker->GetValue();
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'NoiseMaker' underlying UObject is invalid");
			return nullptr;
		}
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'NoiseMaker' must have type 'Actor'");
		return nullptr;
	}

	float Loudness;
	if (!NePyBase::ToCpp(PyArgs[1], Loudness))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Loudness' must have type 'float'");
		return nullptr;
	}

	FVector* NoiseLocation;
	if (FNePyStruct_Vector* PyNoiseLocation = NePyStructCheck_Vector(PyArgs[2]))
	{
		NoiseLocation = (FVector*)PyNoiseLocation->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'NoiseLocation' must have type 'Vector'");
		return nullptr;
	}

	InSelf->GetValue()->MakeNoise(NoiseMaker, Loudness, *NoiseLocation);
	Py_RETURN_NONE;
}
// region func body end

static PyObject* FNePyObject_PawnNoiseEmitterComponent_Class(PyObject* InSelf) {
	UClass* Class = UPawnNoiseEmitterComponent::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_PawnNoiseEmitterComponent_methods[] = {
	{"MakeNoise", NePyCFunctionCast(&FNePyObject_PawnNoiseEmitterComponent_MakeNoise), METH_VARARGS, ""},
	{"Class", NePyCFunctionCast(&FNePyObject_PawnNoiseEmitterComponent_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_PawnNoiseEmitterComponent* NePyObjectNew_PawnNoiseEmitterComponent(UPawnNoiseEmitterComponent* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_PawnNoiseEmitterComponent));
	FNePyObject_PawnNoiseEmitterComponent* RetValue = (FNePyObject_PawnNoiseEmitterComponent*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_PawnNoiseEmitterComponent* NePyObjectCheck_PawnNoiseEmitterComponent(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_PawnNoiseEmitterComponent))
	{
		return (FNePyObject_PawnNoiseEmitterComponent*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_PawnNoiseEmitterComponent()
{
	return &FNePyObjectType_PawnNoiseEmitterComponent;
}

PyTypeObject* NePyNePyWrappedClassInit_PawnNoiseEmitterComponent(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_PawnNoiseEmitterComponent;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_getset = FNePyObjectType_PawnNoiseEmitterComponent_getset;
	NePyObjectType->tp_methods = FNePyObjectType_PawnNoiseEmitterComponent_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_PawnNoiseEmitterComponent,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_PawnNoiseEmitterComponent(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UPawnNoiseEmitterComponent::StaticClass(), NePyNePyWrappedClassInit_PawnNoiseEmitterComponent);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UPawnNoiseEmitterComponent*& OutVal)
	{
		if (FNePyObject_PawnNoiseEmitterComponent* PyObj = NePyObjectCheck_PawnNoiseEmitterComponent(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif