#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "SkeletalMeshMerge.h"
// region include end

struct FNePyStruct_SkelMeshMergeUVTransformMapping : public TNePyStructBase<FSkelMeshMergeUVTransformMapping>
{
};

void NePyInitStruct_SkelMeshMergeUVTransformMapping(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_SkelMeshMergeUVTransformMapping* NePyStructNew_SkelMeshMergeUVTransformMapping(const FSkelMeshMergeUVTransformMapping& InValue);

NEPYTHONBINDING_API FNePyStruct_SkelMeshMergeUVTransformMapping* NePyStructCheck_SkelMeshMergeUVTransformMapping(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_SkelMeshMergeUVTransformMapping();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FSkelMeshMergeUVTransformMapping& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FSkelMeshMergeUVTransformMapping& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif