#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Engine/EngineTypes.h"
// region include end

struct FNePyStruct_DisplacementFadeRange : public TNePyStructBase<FDisplacementFadeRange>
{
};

void NePyInitStruct_DisplacementFadeRange(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_DisplacementFadeRange* NePyStructNew_DisplacementFadeRange(const FDisplacementFadeRange& InValue);

NEPYTHONBINDING_API FNePyStruct_DisplacementFadeRange* NePyStructCheck_DisplacementFadeRange(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_DisplacementFadeRange();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FDisplacementFadeRange& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FDisplacementFadeRange& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif