// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_PlateCropSettings.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_PlateCropSettings = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"PlateCropSettings", /* tp_name */
	sizeof(FNePyStruct_PlateCropSettings), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_PlateCropSettings_GetAspectRatio(FNePyStruct_PlateCropSettings* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FPlateCropSettings*)InSelf->Value)->AspectRatio);
	return RetValue;
}

int FNePyStruct_PlateCropSettings_SetAspectRatio(FNePyStruct_PlateCropSettings* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FPlateCropSettings*)InSelf->Value)->AspectRatio))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_PlateCropSettings_getset[] = {
	{ (char*)"AspectRatio", (getter)FNePyStruct_PlateCropSettings_GetAspectRatio, (setter)FNePyStruct_PlateCropSettings_SetAspectRatio, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_PlateCropSettings(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_PlateCropSettings* PyObj = NePyStructCheck_PlateCropSettings(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_PlateCropSettings(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_PlateCropSettings;
	FNePyStruct_PlateCropSettings* PyObj = (FNePyStruct_PlateCropSettings*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FPlateCropSettings*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FPlateCropSettings*)FMemory::Malloc(sizeof(FPlateCropSettings), alignof(FPlateCropSettings));
	NePyBase::EnsureCopyToStructSafely<FPlateCropSettings>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_PlateCropSettings(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_PlateCropSettings;
	TNePyStructBase<FPlateCropSettings>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_PlateCropSettings_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_PlateCropSettings,
			(NePyStructPropGet)NePyStructPropGet_PlateCropSettings,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_PlateCropSettings(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FPlateCropSettings>::Get(), NePyNePyWrappedStructInit_PlateCropSettings);
}

FNePyStruct_PlateCropSettings* NePyStructNew_PlateCropSettings(const FPlateCropSettings& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_PlateCropSettings;
	FNePyStruct_PlateCropSettings* RetValue = (FNePyStruct_PlateCropSettings*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_PlateCropSettings::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FPlateCropSettings(InValue);
	return RetValue;
}

FNePyStruct_PlateCropSettings* NePyStructCheck_PlateCropSettings(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_PlateCropSettings))
	{
		return (FNePyStruct_PlateCropSettings*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_PlateCropSettings()
{
	return &FNePyStructType_PlateCropSettings;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FPlateCropSettings& OutVal)
	{
		if (FNePyStruct_PlateCropSettings* PyObj = NePyStructCheck_PlateCropSettings(InPyObj))
		{
			OutVal = *(FPlateCropSettings*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FPlateCropSettings& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_PlateCropSettings(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif