#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyObjectBase.h"
// region include begin
#include "Sections/MovieSceneFadeSection.h"
// region include end

class FNePyObject_MovieSceneFadeSection : public FNePyObjectBase
{
public:
	inline UMovieSceneFadeSection* GetValue()
	{
		return (UMovieSceneFadeSection*)Value;
	}
};

void NePyInitObject_MovieSceneFadeSection(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyObject_MovieSceneFadeSection* NePyObjectCheck_MovieSceneFadeSection(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyObjectGetType_MovieSceneFadeSection();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, UMovieSceneFadeSection*& OutVal);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif