#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "MovieSceneDynamicBinding.h"
// region include end

struct FNePyStruct_MovieSceneDynamicBindingResolveParams : public TNePyStructBase<FMovieSceneDynamicBindingResolveParams>
{
};

void NePyInitStruct_MovieSceneDynamicBindingResolveParams(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_MovieSceneDynamicBindingResolveParams* NePyStructNew_MovieSceneDynamicBindingResolveParams(const FMovieSceneDynamicBindingResolveParams& InValue);

NEPYTHONBINDING_API FNePyStruct_MovieSceneDynamicBindingResolveParams* NePyStructCheck_MovieSceneDynamicBindingResolveParams(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_MovieSceneDynamicBindingResolveParams();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FMovieSceneDynamicBindingResolveParams& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FMovieSceneDynamicBindingResolveParams& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif