// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_MovieSceneStringSection.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_MovieSceneStringSection = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"MovieSceneStringSection", /* tp_name */
	sizeof(FNePyObject_MovieSceneStringSection), /* tp_basicsize */
};

static PyObject* FNePyObject_MovieSceneStringSection_Class(PyObject* InSelf) {
	UClass* Class = UMovieSceneStringSection::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_MovieSceneStringSection_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_MovieSceneStringSection_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_MovieSceneStringSection* NePyObjectNew_MovieSceneStringSection(UMovieSceneStringSection* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_MovieSceneStringSection));
	FNePyObject_MovieSceneStringSection* RetValue = (FNePyObject_MovieSceneStringSection*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_MovieSceneStringSection* NePyObjectCheck_MovieSceneStringSection(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_MovieSceneStringSection))
	{
		return (FNePyObject_MovieSceneStringSection*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_MovieSceneStringSection()
{
	return &FNePyObjectType_MovieSceneStringSection;
}

PyTypeObject* NePyNePyWrappedClassInit_MovieSceneStringSection(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_MovieSceneStringSection;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_MovieSceneStringSection_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_MovieSceneStringSection,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_MovieSceneStringSection(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UMovieSceneStringSection::StaticClass(), NePyNePyWrappedClassInit_MovieSceneStringSection);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UMovieSceneStringSection*& OutVal)
	{
		if (FNePyObject_MovieSceneStringSection* PyObj = NePyObjectCheck_MovieSceneStringSection(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif