#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "MovieSceneSequenceTickInterval.h"
// region include end

struct FNePyStruct_MovieSceneSequenceTickInterval : public TNePyStructBase<FMovieSceneSequenceTickInterval>
{
};

void NePyInitStruct_MovieSceneSequenceTickInterval(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_MovieSceneSequenceTickInterval* NePyStructNew_MovieSceneSequenceTickInterval(const FMovieSceneSequenceTickInterval& InValue);

NEPYTHONBINDING_API FNePyStruct_MovieSceneSequenceTickInterval* NePyStructCheck_MovieSceneSequenceTickInterval(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_MovieSceneSequenceTickInterval();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FMovieSceneSequenceTickInterval& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FMovieSceneSequenceTickInterval& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif