// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyObject_MovieScene3DTransformTrack.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin

// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyObjectType_MovieScene3DTransformTrack = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"MovieScene3DTransformTrack", /* tp_name */
	sizeof(FNePyObject_MovieScene3DTransformTrack), /* tp_basicsize */
};

static PyObject* FNePyObject_MovieScene3DTransformTrack_Class(PyObject* InSelf) {
	UClass* Class = UMovieScene3DTransformTrack::StaticClass();
	return NePyBase::ToPy(Class);
}

static PyMethodDef FNePyObjectType_MovieScene3DTransformTrack_methods[] = {
	{"Class", NePyCFunctionCast(&FNePyObject_MovieScene3DTransformTrack_Class), METH_NOARGS | METH_STATIC, ""},
	{ NULL } /* Sentinel */
};

FNePyObject_MovieScene3DTransformTrack* NePyObjectNew_MovieScene3DTransformTrack(UMovieScene3DTransformTrack* InValue, PyTypeObject* InPyType)
{
	check(PyType_IsSubtype(InPyType, &FNePyObjectType_MovieScene3DTransformTrack));
	FNePyObject_MovieScene3DTransformTrack* RetValue = (FNePyObject_MovieScene3DTransformTrack*)InPyType->tp_alloc(InPyType, 0);
	RetValue->Value = InValue;
	return RetValue;
}

FNePyObject_MovieScene3DTransformTrack* NePyObjectCheck_MovieScene3DTransformTrack(PyObject* InPyObj)
{
	if (InPyObj && PyObject_IsInstance(InPyObj, (PyObject*)&FNePyObjectType_MovieScene3DTransformTrack))
	{
		return (FNePyObject_MovieScene3DTransformTrack*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyObjectGetType_MovieScene3DTransformTrack()
{
	return &FNePyObjectType_MovieScene3DTransformTrack;
}

PyTypeObject* NePyNePyWrappedClassInit_MovieScene3DTransformTrack(const UClass* InClass, PyTypeObject* InPyBase, PyObject* InPyBases)
{
	PyTypeObject* NePyObjectType = &FNePyObjectType_MovieScene3DTransformTrack;
	NePyObjectType_InitCommon(NePyObjectType);
	NePyObjectType->tp_methods = FNePyObjectType_MovieScene3DTransformTrack_methods;
	NePyObjectType->tp_base = InPyBase;
	NePyObjectType->tp_bases = InPyBases;
	PyType_Ready(NePyObjectType);

	FNePyObjectTypeInfo TypeInfo = {
		NePyObjectType,
		ENePyTypeFlags::StaticPyType,
		(NePyObjectNewFunc)NePyObjectNew_MovieScene3DTransformTrack,
	};
	FNePyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, TypeInfo);

	return NePyObjectType;
}

void NePyInitObject_MovieScene3DTransformTrack(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedClassInitFunc(
		UMovieScene3DTransformTrack::StaticClass(), NePyNePyWrappedClassInit_MovieScene3DTransformTrack);
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, UMovieScene3DTransformTrack*& OutVal)
	{
		if (FNePyObject_MovieScene3DTransformTrack* PyObj = NePyObjectCheck_MovieScene3DTransformTrack(InPyObj))
		{
			if (FNePyHouseKeeper::Get().IsValid(PyObj))
			{
				OutVal = PyObj->GetValue();
				return true;
			}
		}
		return false;
	}
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif