#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Input/Events.h"
// region include end

struct FNePyStruct_CharacterEvent : public TNePyStructBase<FCharacterEvent>
{
};

void NePyInitStruct_CharacterEvent(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_CharacterEvent* NePyStructNew_CharacterEvent(const FCharacterEvent& InValue);

NEPYTHONBINDING_API FNePyStruct_CharacterEvent* NePyStructCheck_CharacterEvent(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_CharacterEvent();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FCharacterEvent& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FCharacterEvent& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif