#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Styling/ToolBarStyle.h"
// region include end

struct FNePyStruct_WrapButtonStyle : public TNePyStructBase<FWrapButtonStyle>
{
};

void NePyInitStruct_WrapButtonStyle(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_WrapButtonStyle* NePyStructNew_WrapButtonStyle(const FWrapButtonStyle& InValue);

NEPYTHONBINDING_API FNePyStruct_WrapButtonStyle* NePyStructCheck_WrapButtonStyle(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_WrapButtonStyle();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FWrapButtonStyle& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FWrapButtonStyle& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif