#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "LevelSequenceCameraSettings.h"
// region include end

struct FNePyStruct_LevelSequenceCameraSettings : public TNePyStructBase<FLevelSequenceCameraSettings>
{
};

void NePyInitStruct_LevelSequenceCameraSettings(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_LevelSequenceCameraSettings* NePyStructNew_LevelSequenceCameraSettings(const FLevelSequenceCameraSettings& InValue);

NEPYTHONBINDING_API FNePyStruct_LevelSequenceCameraSettings* NePyStructCheck_LevelSequenceCameraSettings(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_LevelSequenceCameraSettings();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FLevelSequenceCameraSettings& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FLevelSequenceCameraSettings& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif