#pragma once
// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#if defined(_MSC_VER)
#pragma warning(disable: 4456) // disable declaration hides previous local declaration
#pragma warning(disable: 4996) // disable deprecate warnings
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wshadow" // disable declaration hides previous local declaration
#endif
#include "NePyIncludePython.h"
#include "NePyStructBase.h"
// region include begin
#include "Math/Vector.h"
// region include end

struct FNePyStruct_Vector : public TNePyStructBase<FVector>
{
};

void NePyInitStruct_Vector(PyObject* PyOuterModule);

NEPYTHONBINDING_API FNePyStruct_Vector* NePyStructNew_Vector(const FVector& InValue);

NEPYTHONBINDING_API FNePyStruct_Vector* NePyStructCheck_Vector(PyObject* InPyObj);

NEPYTHONBINDING_API PyTypeObject* NePyStructGetType_Vector();

namespace NePyBase
{
	NEPYTHONBINDING_API bool ToCpp(PyObject* InPyObj, FVector& OutVal);
	NEPYTHONBINDING_API bool ToPy(const FVector& InVal, PyObject*& OutPyObj);
}

#ifdef _MSC_VER
#pragma warning(default:4996)
#endif