// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_InterpCurvePointVector2D.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/core/NePyStruct_Vector2D.h"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_InterpCurvePointVector2D = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"InterpCurvePointVector2D", /* tp_name */
	sizeof(FNePyStruct_InterpCurvePointVector2D), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_InterpCurvePointVector2D_GetInVal(FNePyStruct_InterpCurvePointVector2D* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FInterpCurvePointVector2D*)InSelf->Value)->InVal);
	return RetValue;
}

int FNePyStruct_InterpCurvePointVector2D_SetInVal(FNePyStruct_InterpCurvePointVector2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FInterpCurvePointVector2D*)InSelf->Value)->InVal))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_InterpCurvePointVector2D_GetOutVal(FNePyStruct_InterpCurvePointVector2D* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyStructNew_Vector2D(((FInterpCurvePointVector2D*)InSelf->Value)->OutVal);
	return RetValue;
}

int FNePyStruct_InterpCurvePointVector2D_SetOutVal(FNePyStruct_InterpCurvePointVector2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (FNePyStruct_Vector2D* PyOutVal = NePyStructCheck_Vector2D(InValue))
	{
		((FInterpCurvePointVector2D*)InSelf->Value)->OutVal = *((FVector2D*)PyOutVal->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector2D'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_InterpCurvePointVector2D_GetArriveTangent(FNePyStruct_InterpCurvePointVector2D* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyStructNew_Vector2D(((FInterpCurvePointVector2D*)InSelf->Value)->ArriveTangent);
	return RetValue;
}

int FNePyStruct_InterpCurvePointVector2D_SetArriveTangent(FNePyStruct_InterpCurvePointVector2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (FNePyStruct_Vector2D* PyArriveTangent = NePyStructCheck_Vector2D(InValue))
	{
		((FInterpCurvePointVector2D*)InSelf->Value)->ArriveTangent = *((FVector2D*)PyArriveTangent->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector2D'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_InterpCurvePointVector2D_GetLeaveTangent(FNePyStruct_InterpCurvePointVector2D* InSelf, void* InClosure)
{
	PyObject* RetValue = NePyStructNew_Vector2D(((FInterpCurvePointVector2D*)InSelf->Value)->LeaveTangent);
	return RetValue;
}

int FNePyStruct_InterpCurvePointVector2D_SetLeaveTangent(FNePyStruct_InterpCurvePointVector2D* InSelf, PyObject* InValue, void* InClosure)
{
	if (FNePyStruct_Vector2D* PyLeaveTangent = NePyStructCheck_Vector2D(InValue))
	{
		((FInterpCurvePointVector2D*)InSelf->Value)->LeaveTangent = *((FVector2D*)PyLeaveTangent->Value);
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'Vector2D'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_InterpCurvePointVector2D_GetInterpMode(FNePyStruct_InterpCurvePointVector2D* InSelf, void* InClosure)
{
	PyObject* RetValue = PyLong_FromUnsignedLong((uint8)((FInterpCurvePointVector2D*)InSelf->Value)->InterpMode);
	return RetValue;
}

int FNePyStruct_InterpCurvePointVector2D_SetInterpMode(FNePyStruct_InterpCurvePointVector2D* InSelf, PyObject* InValue, void* InClosure)
{
	uint8 InterpModeTemp;
	if (!NePyBase::ToCpp(InValue, InterpModeTemp))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'int'(EInterpCurveMode)");
		return -1;
	}
	((FInterpCurvePointVector2D*)InSelf->Value)->InterpMode = (EInterpCurveMode)InterpModeTemp;
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_InterpCurvePointVector2D_getset[] = {
	{ (char*)"InVal", (getter)FNePyStruct_InterpCurvePointVector2D_GetInVal, (setter)FNePyStruct_InterpCurvePointVector2D_SetInVal, nullptr, nullptr },
	{ (char*)"OutVal", (getter)FNePyStruct_InterpCurvePointVector2D_GetOutVal, (setter)FNePyStruct_InterpCurvePointVector2D_SetOutVal, nullptr, nullptr },
	{ (char*)"ArriveTangent", (getter)FNePyStruct_InterpCurvePointVector2D_GetArriveTangent, (setter)FNePyStruct_InterpCurvePointVector2D_SetArriveTangent, nullptr, nullptr },
	{ (char*)"LeaveTangent", (getter)FNePyStruct_InterpCurvePointVector2D_GetLeaveTangent, (setter)FNePyStruct_InterpCurvePointVector2D_SetLeaveTangent, nullptr, nullptr },
	{ (char*)"InterpMode", (getter)FNePyStruct_InterpCurvePointVector2D_GetInterpMode, (setter)FNePyStruct_InterpCurvePointVector2D_SetInterpMode, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

bool NePyStructPropSet_InterpCurvePointVector2D(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_InterpCurvePointVector2D* PyObj = NePyStructCheck_InterpCurvePointVector2D(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_InterpCurvePointVector2D(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_InterpCurvePointVector2D;
	FNePyStruct_InterpCurvePointVector2D* PyObj = (FNePyStruct_InterpCurvePointVector2D*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FInterpCurvePointVector2D*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FInterpCurvePointVector2D*)FMemory::Malloc(sizeof(FInterpCurvePointVector2D), alignof(FInterpCurvePointVector2D));
	NePyBase::EnsureCopyToStructSafely<FInterpCurvePointVector2D>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_InterpCurvePointVector2D(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_InterpCurvePointVector2D;
	TNePyStructBase<FInterpCurvePointVector2D>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_getset = FNePyStructType_InterpCurvePointVector2D_getset;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_InterpCurvePointVector2D,
			(NePyStructPropGet)NePyStructPropGet_InterpCurvePointVector2D,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_InterpCurvePointVector2D(PyObject* PyOuterModule)
{
	const UScriptStruct* ScriptStruct = FNePyStructBase::SearchScriptStruct(TEXT("/Script/CoreUObject"), TEXT("InterpCurvePointVector2D"));
	if (ScriptStruct)
	{
		FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
			ScriptStruct, NePyNePyWrappedStructInit_InterpCurvePointVector2D);
	}
	else
	{
		PyTypeObject* NePyStructType = NePyNePyWrappedStructInit_InterpCurvePointVector2D(nullptr, NePyStructBaseGetType());
		Py_INCREF(NePyStructType);
		PyModule_AddObject(PyOuterModule, "InterpCurvePointVector2D", (PyObject*)NePyStructType);
	}
}

FNePyStruct_InterpCurvePointVector2D* NePyStructNew_InterpCurvePointVector2D(const FInterpCurvePointVector2D& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_InterpCurvePointVector2D;
	FNePyStruct_InterpCurvePointVector2D* RetValue = (FNePyStruct_InterpCurvePointVector2D*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_InterpCurvePointVector2D::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FInterpCurvePointVector2D(InValue);
	return RetValue;
}

FNePyStruct_InterpCurvePointVector2D* NePyStructCheck_InterpCurvePointVector2D(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_InterpCurvePointVector2D))
	{
		return (FNePyStruct_InterpCurvePointVector2D*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_InterpCurvePointVector2D()
{
	return &FNePyStructType_InterpCurvePointVector2D;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FInterpCurvePointVector2D& OutVal)
	{
		if (FNePyStruct_InterpCurvePointVector2D* PyObj = NePyStructCheck_InterpCurvePointVector2D(InPyObj))
		{
			OutVal = *(FInterpCurvePointVector2D*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FInterpCurvePointVector2D& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_InterpCurvePointVector2D(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif