// This file is generated by NewEdenPythonBinding Tool
// DONT modify it manually!
#include "NePyStruct_Vector.h"
#include "Misc/AssertionMacros.h"
#include "NePyHouseKeeper.h"
#include "NePyWrapperTypeRegistry.h"
#include "NePyWrapperInitializer.h"
// region include begin
#include "NePy/Auto/core/NePyStruct_Vector.h"
#include "NePy/Auto/core/NePyStruct_Plane.h"
#include "NePy/Auto/core/NePyStruct_Rotator.h"
#include "NePy/Auto/core/NePyStruct_Quat.h"
#include "NePy/Auto/core/NePyStruct_Vector2D.h"
#include "Kismet/KismetMathLibrary.h"
#include "NePy/Manual/NePyStruct_Vector.inl"
// region include end

#ifdef _MSC_VER
#pragma warning(disable:4996) // disable deprecate warnings
#endif

static PyTypeObject FNePyStructType_Vector = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"Vector", /* tp_name */
	sizeof(FNePyStruct_Vector), /* tp_basicsize */
};

// region prop getset body begin
PyObject* FNePyStruct_Vector_GetX(FNePyStruct_Vector* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FVector*)InSelf->Value)->X);
	return RetValue;
}

int FNePyStruct_Vector_SetX(FNePyStruct_Vector* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FVector*)InSelf->Value)->X))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_Vector_GetY(FNePyStruct_Vector* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FVector*)InSelf->Value)->Y);
	return RetValue;
}

int FNePyStruct_Vector_SetY(FNePyStruct_Vector* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FVector*)InSelf->Value)->Y))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}

PyObject* FNePyStruct_Vector_GetZ(FNePyStruct_Vector* InSelf, void* InClosure)
{
	PyObject* RetValue = PyFloat_FromDouble(((FVector*)InSelf->Value)->Z);
	return RetValue;
}

int FNePyStruct_Vector_SetZ(FNePyStruct_Vector* InSelf, PyObject* InValue, void* InClosure)
{
	if (!NePyBase::ToCpp(InValue, ((FVector*)InSelf->Value)->Z))
	{
		PyErr_SetString(PyExc_TypeError, "argument type must be 'float'");
		return -1;
	}
	return 0;
}
// region prop getset body end

static PyGetSetDef FNePyStructType_Vector_getset[] = {
	{ (char*)"X", (getter)FNePyStruct_Vector_GetX, (setter)FNePyStruct_Vector_SetX, nullptr, nullptr },
	{ (char*)"Y", (getter)FNePyStruct_Vector_GetY, (setter)FNePyStruct_Vector_SetY, nullptr, nullptr },
	{ (char*)"Z", (getter)FNePyStruct_Vector_GetZ, (setter)FNePyStruct_Vector_SetZ, nullptr, nullptr },
	{ nullptr } /* Sentinel */
};

// region func body begin
PyObject* FNePyStruct_Vector_Zero(FNePyStruct_Vector* InSelf)
{
	auto RetVal = FVector::Zero();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_One(FNePyStruct_Vector* InSelf)
{
	auto RetVal = FVector::One();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_UnitX(FNePyStruct_Vector* InSelf)
{
	auto RetVal = FVector::UnitX();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_UnitY(FNePyStruct_Vector* InSelf)
{
	auto RetVal = FVector::UnitY();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_UnitZ(FNePyStruct_Vector* InSelf)
{
	auto RetVal = FVector::UnitZ();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

int FNePyStruct_Vector_FVector_Overload1(FNePyStruct_Vector* InSelf, PyObject* InArgs, PyObject* InKwds)
{
	new (InSelf->Value) FVector();
	return 0;
}

int FNePyStruct_Vector_FVector_Overload2(FNePyStruct_Vector* InSelf, PyObject* InArgs, PyObject* InKwds)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "O:FVector_Overload2", &PyArgs[0]))
	{
		return -1;
	}

	double InF;
	if (!NePyBase::ToCpp(PyArgs[0], InF))
	{
		return -1;
	}

	new (InSelf->Value) FVector(InF);
	return 0;
}

int FNePyStruct_Vector_FVector_Overload4(FNePyStruct_Vector* InSelf, PyObject* InArgs, PyObject* InKwds)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "O:FVector_Overload4", &PyArgs[0]))
	{
		return -1;
	}

	int32 InVector;
	if (!NePyBase::ToCpp(PyArgs[0], InVector))
	{
		return -1;
	}

	new (InSelf->Value) FVector(InVector);
	return 0;
}

int FNePyStruct_Vector_FVector_Overload5(FNePyStruct_Vector* InSelf, PyObject* InArgs, PyObject* InKwds)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "O:FVector_Overload5", &PyArgs[0]))
	{
		return -1;
	}

	int32 A;
	if (!NePyBase::ToCpp(PyArgs[0], A))
	{
		return -1;
	}

	new (InSelf->Value) FVector(A);
	return 0;
}

int FNePyStruct_Vector_FVector_Overload3(FNePyStruct_Vector* InSelf, PyObject* InArgs, PyObject* InKwds)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:FVector_Overload3", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return -1;
	}

	double InX;
	if (!NePyBase::ToCpp(PyArgs[0], InX))
	{
		return -1;
	}

	double InY;
	if (!NePyBase::ToCpp(PyArgs[1], InY))
	{
		return -1;
	}

	double InZ;
	if (!NePyBase::ToCpp(PyArgs[2], InZ))
	{
		return -1;
	}

	new (InSelf->Value) FVector(InX, InY, InZ);
	return 0;
}

int FNePyStruct_Vector_FVector(FNePyStruct_Vector* InSelf, PyObject* InArgs, PyObject* InKwds)
{
	if (FNePyStruct_Vector::Init(InSelf, nullptr, nullptr) < 0)
	{
		PyErr_SetString(PyExc_RuntimeError, "can't construct memory for struct 'FVector'");
		return -1;
	}

	int32 ArgCount = (int32)PyTuple_Size(InArgs);

	if (ArgCount == 0)
	{
		if (FNePyStruct_Vector_FVector_Overload1(InSelf, InArgs, InKwds) == 0)
		{
			return 0;
		}
		PyErr_Clear();
	}

	if (ArgCount == 1)
	{
		if (FNePyStruct_Vector_FVector_Overload2(InSelf, InArgs, InKwds) == 0)
		{
			return 0;
		}
		PyErr_Clear();

		if (FNePyStruct_Vector_FVector_Overload4(InSelf, InArgs, InKwds) == 0)
		{
			return 0;
		}
		PyErr_Clear();

		if (FNePyStruct_Vector_FVector_Overload5(InSelf, InArgs, InKwds) == 0)
		{
			return 0;
		}
		PyErr_Clear();
	}

	if (ArgCount == 3)
	{
		if (FNePyStruct_Vector_FVector_Overload3(InSelf, InArgs, InKwds) == 0)
		{
			return 0;
		}
		PyErr_Clear();
	}

	PyErr_SetString(PyExc_RuntimeError, "can't resolve overload constructor 'FVector'");
	return -1;
}

PyObject* FNePyStruct_Vector_Cross(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->Cross(*V2);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_CrossProduct(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:CrossProduct", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[1]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'B' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::CrossProduct(*A, *B);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Dot(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->Dot(*V);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_DotProduct(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:DotProduct", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[1]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'B' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::DotProduct(*A, *B);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___add___Overload1(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator+(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___add___Overload2(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Bias;
	if (!NePyBase::ToCpp(PyArgs[0], Bias))
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator+(Bias);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___add__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyRetVal = nullptr;

	if (!NePyStructCheck_Vector(InSelf))
	{
		NePyBase::SetBinopTypeError(InSelf, InArg, "+");
		return nullptr;
	}

	PyRetVal = FNePyStruct_Vector___add___Overload1(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyRetVal = FNePyStruct_Vector___add___Overload2(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	NePyBase::SetBinopTypeError(InSelf, InArg, "+");
	return nullptr;
}

PyObject* FNePyStruct_Vector___sub___Overload1(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator-(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___sub___Overload2(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Bias;
	if (!NePyBase::ToCpp(PyArgs[0], Bias))
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator-(Bias);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___sub__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyRetVal = nullptr;

	if (!NePyStructCheck_Vector(InSelf))
	{
		NePyBase::SetBinopTypeError(InSelf, InArg, "-");
		return nullptr;
	}

	PyRetVal = FNePyStruct_Vector___sub___Overload1(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyRetVal = FNePyStruct_Vector___sub___Overload2(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	NePyBase::SetBinopTypeError(InSelf, InArg, "-");
	return nullptr;
}

PyObject* FNePyStruct_Vector___mul___Overload1(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Scale;
	if (!NePyBase::ToCpp(PyArgs[0], Scale))
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator*(Scale);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___mul___Overload2(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator*(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___mul__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyRetVal = nullptr;

	if (!NePyStructCheck_Vector(InSelf))
	{
		NePyBase::SetBinopTypeError(InSelf, InArg, "*");
		return nullptr;
	}

	PyRetVal = FNePyStruct_Vector___mul___Overload1(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyRetVal = FNePyStruct_Vector___mul___Overload2(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	NePyBase::SetBinopTypeError(InSelf, InArg, "*");
	return nullptr;
}

PyObject* FNePyStruct_Vector___div___Overload1(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Scale;
	if (!NePyBase::ToCpp(PyArgs[0], Scale))
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator/(Scale);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___div___Overload2(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator/(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___div__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyRetVal = nullptr;

	if (!NePyStructCheck_Vector(InSelf))
	{
		NePyBase::SetBinopTypeError(InSelf, InArg, "/");
		return nullptr;
	}

	PyRetVal = FNePyStruct_Vector___div___Overload1(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyRetVal = FNePyStruct_Vector___div___Overload2(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	NePyBase::SetBinopTypeError(InSelf, InArg, "/");
	return nullptr;
}

PyObject* FNePyStruct_Vector___eq__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		Py_RETURN_FALSE;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator==(*V);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___ne__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		Py_RETURN_TRUE;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator!=(*V);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Equals(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "O|O:Equals", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V' must have type 'Vector'");
		return nullptr;
	}

	double Tolerance = UE_KINDA_SMALL_NUMBER;
	if (PyArgs[1])
	{
		if (!NePyBase::ToCpp(PyArgs[1], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg2 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->Equals(*V, Tolerance);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_AllComponentsEqual(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "|O:AllComponentsEqual", &PyArgs[0]))
	{
		return nullptr;
	}

	double Tolerance = UE_KINDA_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->AllComponentsEqual(Tolerance);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___iadd__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator+=(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___isub__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator-=(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___imul___Overload1(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Scale;
	if (!NePyBase::ToCpp(PyArgs[0], Scale))
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator*=(Scale);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___imul___Overload2(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator*=(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___imul__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyRetVal = nullptr;

	PyRetVal = FNePyStruct_Vector___imul___Overload1(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyRetVal = FNePyStruct_Vector___imul___Overload2(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyErr_SetString(PyExc_RuntimeError, "can't resolve overload function '__imul__' on 'FVector'");
	return nullptr;
}

PyObject* FNePyStruct_Vector___idiv___Overload1(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Scale;
	if (!NePyBase::ToCpp(PyArgs[0], Scale))
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator/=(Scale);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___idiv___Overload2(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->operator/=(*V);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector___idiv__(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyRetVal = nullptr;

	PyRetVal = FNePyStruct_Vector___idiv___Overload1(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyRetVal = FNePyStruct_Vector___idiv___Overload2(InSelf, InArg);
	if (PyRetVal)
	{
		return PyRetVal;
	}
	PyErr_Clear();

	PyErr_SetString(PyExc_RuntimeError, "can't resolve overload function '__idiv__' on 'FVector'");
	return nullptr;
}

PyObject* FNePyStruct_Vector_Component(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	int32 Index;
	if (!NePyBase::ToCpp(PyArgs[0], Index))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Index' must have type 'int'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->Component(Index);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Set(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:Set", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	double InX;
	if (!NePyBase::ToCpp(PyArgs[0], InX))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'InX' must have type 'float'");
		return nullptr;
	}

	double InY;
	if (!NePyBase::ToCpp(PyArgs[1], InY))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'InY' must have type 'float'");
		return nullptr;
	}

	double InZ;
	if (!NePyBase::ToCpp(PyArgs[2], InZ))
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'InZ' must have type 'float'");
		return nullptr;
	}

	((FVector*)InSelf->Value)->Set(InX, InY, InZ);
	Py_RETURN_NONE;
}

PyObject* FNePyStruct_Vector_GetMax(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetMax();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetAbsMax(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetAbsMax();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetMin(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetMin();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetAbsMin(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetAbsMin();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ComponentMin(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* Other;
	if (FNePyStruct_Vector* PyOther = NePyStructCheck_Vector(PyArgs[0]))
	{
		Other = (FVector*)PyOther->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Other' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->ComponentMin(*Other);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ComponentMax(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* Other;
	if (FNePyStruct_Vector* PyOther = NePyStructCheck_Vector(PyArgs[0]))
	{
		Other = (FVector*)PyOther->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Other' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->ComponentMax(*Other);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetAbs(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetAbs();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Size(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->Size();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Length(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->Length();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_SizeSquared(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->SizeSquared();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_SquaredLength(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->SquaredLength();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Size2D(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->Size2D();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_SizeSquared2D(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->SizeSquared2D();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_IsNearlyZero(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "|O:IsNearlyZero", &PyArgs[0]))
	{
		return nullptr;
	}

	double Tolerance = UE_KINDA_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->IsNearlyZero(Tolerance);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_IsZero(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->IsZero();

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_IsUnit(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "|O:IsUnit", &PyArgs[0]))
	{
		return nullptr;
	}

	double LengthSquaredTolerance = UE_KINDA_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], LengthSquaredTolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'LengthSquaredTolerance' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->IsUnit(LengthSquaredTolerance);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_IsNormalized(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->IsNormalized();

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Normalize(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "|O:Normalize", &PyArgs[0]))
	{
		return nullptr;
	}

	double Tolerance = UE_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->Normalize(Tolerance);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetUnsafeNormal(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetUnsafeNormal();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetSafeNormal(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "|OO:GetSafeNormal", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	double Tolerance = UE_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	FVector ResultIfZero = FVector::ZeroVector;
	if (PyArgs[1])
	{
		if (FNePyStruct_Vector* PyResultIfZero = NePyStructCheck_Vector(PyArgs[1]))
		{
			ResultIfZero = *((FVector*)PyResultIfZero->Value);
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg2 'ResultIfZero' must have type 'Vector'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->GetSafeNormal(Tolerance, ResultIfZero);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetSafeNormal2D(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "|OO:GetSafeNormal2D", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	double Tolerance = UE_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	FVector ResultIfZero = FVector::ZeroVector;
	if (PyArgs[1])
	{
		if (FNePyStruct_Vector* PyResultIfZero = NePyStructCheck_Vector(PyArgs[1]))
		{
			ResultIfZero = *((FVector*)PyResultIfZero->Value);
		}
		else
		{
			PyErr_SetString(PyExc_TypeError, "arg2 'ResultIfZero' must have type 'Vector'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->GetSafeNormal2D(Tolerance, ResultIfZero);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetSignVector(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetSignVector();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Projection(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->Projection();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetUnsafeNormal2D(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->GetUnsafeNormal2D();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_BoundToCube(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double Radius;
	if (!NePyBase::ToCpp(PyArgs[0], Radius))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Radius' must have type 'float'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->BoundToCube(Radius);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_BoundToBox(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:BoundToBox", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* Min;
	if (FNePyStruct_Vector* PyMin = NePyStructCheck_Vector(PyArgs[0]))
	{
		Min = (FVector*)PyMin->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Min' must have type 'Vector'");
		return nullptr;
	}

	FVector* Max;
	if (FNePyStruct_Vector* PyMax = NePyStructCheck_Vector(PyArgs[1]))
	{
		Max = (FVector*)PyMax->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Max' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->BoundToBox(*Min, *Max);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetClampedToSize(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:GetClampedToSize", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	double Min;
	if (!NePyBase::ToCpp(PyArgs[0], Min))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Min' must have type 'float'");
		return nullptr;
	}

	double Max;
	if (!NePyBase::ToCpp(PyArgs[1], Max))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Max' must have type 'float'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->GetClampedToSize(Min, Max);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetClampedToSize2D(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:GetClampedToSize2D", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	double Min;
	if (!NePyBase::ToCpp(PyArgs[0], Min))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Min' must have type 'float'");
		return nullptr;
	}

	double Max;
	if (!NePyBase::ToCpp(PyArgs[1], Max))
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Max' must have type 'float'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->GetClampedToSize2D(Min, Max);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetClampedToMaxSize(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double MaxSize;
	if (!NePyBase::ToCpp(PyArgs[0], MaxSize))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'MaxSize' must have type 'float'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->GetClampedToMaxSize(MaxSize);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_GetClampedToMaxSize2D(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	double MaxSize;
	if (!NePyBase::ToCpp(PyArgs[0], MaxSize))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'MaxSize' must have type 'float'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->GetClampedToMaxSize2D(MaxSize);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_AddBounded(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "O|O:AddBounded", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V' must have type 'Vector'");
		return nullptr;
	}

	double Radius = MAX_int16;
	if (PyArgs[1])
	{
		if (!NePyBase::ToCpp(PyArgs[1], Radius))
		{
			PyErr_SetString(PyExc_TypeError, "arg2 'Radius' must have type 'float'");
			return nullptr;
		}
	}

	((FVector*)InSelf->Value)->AddBounded(*V, Radius);
	Py_RETURN_NONE;
}

PyObject* FNePyStruct_Vector_Reciprocal(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->Reciprocal();

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_IsUniform(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[1] = {nullptr};
	if (!PyArg_ParseTuple(InArgs, "|O:IsUniform", &PyArgs[0]))
	{
		return nullptr;
	}

	double Tolerance = UE_KINDA_SMALL_NUMBER;
	if (PyArgs[0])
	{
		if (!NePyBase::ToCpp(PyArgs[0], Tolerance))
		{
			PyErr_SetString(PyExc_TypeError, "arg1 'Tolerance' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = ((FVector*)InSelf->Value)->IsUniform(Tolerance);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_MirrorByVector(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* MirrorNormal;
	if (FNePyStruct_Vector* PyMirrorNormal = NePyStructCheck_Vector(PyArgs[0]))
	{
		MirrorNormal = (FVector*)PyMirrorNormal->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'MirrorNormal' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->MirrorByVector(*MirrorNormal);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_MirrorByPlane(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FPlane* Plane;
	if (FNePyStruct_Plane* PyPlane = NePyStructCheck_Plane(PyArgs[0]))
	{
		Plane = (FPlane*)PyPlane->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Plane' must have type 'Plane'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->MirrorByPlane(*Plane);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_RotateAngleAxis(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:RotateAngleAxis", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	double AngleDeg;
	if (!NePyBase::ToCpp(PyArgs[0], AngleDeg))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'AngleDeg' must have type 'float'");
		return nullptr;
	}

	FVector* Axis;
	if (FNePyStruct_Vector* PyAxis = NePyStructCheck_Vector(PyArgs[1]))
	{
		Axis = (FVector*)PyAxis->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Axis' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->RotateAngleAxis(AngleDeg, *Axis);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_RotateAngleAxisRad(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:RotateAngleAxisRad", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	double AngleRad;
	if (!NePyBase::ToCpp(PyArgs[0], AngleRad))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'AngleRad' must have type 'float'");
		return nullptr;
	}

	FVector* Axis;
	if (FNePyStruct_Vector* PyAxis = NePyStructCheck_Vector(PyArgs[1]))
	{
		Axis = (FVector*)PyAxis->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Axis' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->RotateAngleAxisRad(AngleRad, *Axis);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_CosineAngle2D(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[0]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'B' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->CosineAngle2D(*B);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ProjectOnTo(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->ProjectOnTo(*A);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ProjectOnToNormal(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* Normal;
	if (FNePyStruct_Vector* PyNormal = NePyStructCheck_Vector(PyArgs[0]))
	{
		Normal = (FVector*)PyNormal->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Normal' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = ((FVector*)InSelf->Value)->ProjectOnToNormal(*Normal);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ToOrientationRotator(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->ToOrientationRotator();

	PyObject* PyRetVal0 = NePyStructNew_Rotator(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ToOrientationQuat(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->ToOrientationQuat();

	PyObject* PyRetVal0 = NePyStructNew_Quat(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Rotation(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->Rotation();

	PyObject* PyRetVal0 = NePyStructNew_Rotator(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_FindBestAxisVectors(FNePyStruct_Vector* InSelf)
{
	FVector Axis1;

	FVector Axis2;

	((FVector*)InSelf->Value)->FindBestAxisVectors(Axis1, Axis2);

	PyObject* PyRetVal0 = NePyStructNew_Vector(Axis1);
	PyObject* PyRetVal1 = NePyStructNew_Vector(Axis2);

	PyObject* PyRetVals = PyTuple_New(2);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	return PyRetVals;
}

PyObject* FNePyStruct_Vector_UnwindEuler(FNePyStruct_Vector* InSelf)
{
	((FVector*)InSelf->Value)->UnwindEuler();
	Py_RETURN_NONE;
}

PyObject* FNePyStruct_Vector_ContainsNaN(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->ContainsNaN();

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_ToString(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->ToString();

	PyObject* PyRetVal0;
	if (!NePyBase::ToPy(RetVal, PyRetVal0))
	{
		PyErr_SetString(PyExc_TypeError, "PyRetVal0 'RetVal' with type 'str' convert to PyObject failed!");
		return nullptr;
	}
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_UnitCartesianToSpherical(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->UnitCartesianToSpherical();

	PyObject* PyRetVal0 = NePyStructNew_Vector2D(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_HeadingAngle(FNePyStruct_Vector* InSelf)
{
	auto RetVal = ((FVector*)InSelf->Value)->HeadingAngle();

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_SlerpVectorToDirection(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector V;

	FVector Direction;

	double Alpha;
	if (!NePyBase::ToCpp(PyArgs[0], Alpha))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Alpha' must have type 'float'");
		return nullptr;
	}

	auto RetVal = FVector::SlerpVectorToDirection(V, Direction, Alpha);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	PyObject* PyRetVal1 = NePyStructNew_Vector(V);
	PyObject* PyRetVal2 = NePyStructNew_Vector(Direction);

	PyObject* PyRetVals = PyTuple_New(3);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	PyTuple_SetItem(PyRetVals, 2, PyRetVal2);
	return PyRetVals;
}

PyObject* FNePyStruct_Vector_SlerpNormals(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector NormalA;

	FVector NormalB;

	double Alpha;
	if (!NePyBase::ToCpp(PyArgs[0], Alpha))
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Alpha' must have type 'float'");
		return nullptr;
	}

	auto RetVal = FVector::SlerpNormals(NormalA, NormalB, Alpha);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	PyObject* PyRetVal1 = NePyStructNew_Vector(NormalA);
	PyObject* PyRetVal2 = NePyStructNew_Vector(NormalB);

	PyObject* PyRetVals = PyTuple_New(3);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	PyTuple_SetItem(PyRetVals, 2, PyRetVal2);
	return PyRetVals;
}

PyObject* FNePyStruct_Vector_CreateOrthonormalBasis(FNePyStruct_Vector* InSelf)
{
	FVector XAxis;

	FVector YAxis;

	FVector ZAxis;

	FVector::CreateOrthonormalBasis(XAxis, YAxis, ZAxis);

	PyObject* PyRetVal0 = NePyStructNew_Vector(XAxis);
	PyObject* PyRetVal1 = NePyStructNew_Vector(YAxis);
	PyObject* PyRetVal2 = NePyStructNew_Vector(ZAxis);

	PyObject* PyRetVals = PyTuple_New(3);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	PyTuple_SetItem(PyRetVals, 2, PyRetVal2);
	return PyRetVals;
}

PyObject* FNePyStruct_Vector_PointsAreSame(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:PointsAreSame", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* P;
	if (FNePyStruct_Vector* PyP = NePyStructCheck_Vector(PyArgs[0]))
	{
		P = (FVector*)PyP->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'P' must have type 'Vector'");
		return nullptr;
	}

	FVector* Q;
	if (FNePyStruct_Vector* PyQ = NePyStructCheck_Vector(PyArgs[1]))
	{
		Q = (FVector*)PyQ->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Q' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::PointsAreSame(*P, *Q);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_PointsAreNear(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:PointsAreNear", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* Point1;
	if (FNePyStruct_Vector* PyPoint1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		Point1 = (FVector*)PyPoint1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Point1' must have type 'Vector'");
		return nullptr;
	}

	FVector* Point2;
	if (FNePyStruct_Vector* PyPoint2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		Point2 = (FVector*)PyPoint2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Point2' must have type 'Vector'");
		return nullptr;
	}

	double Dist;
	if (!NePyBase::ToCpp(PyArgs[2], Dist))
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'Dist' must have type 'float'");
		return nullptr;
	}

	auto RetVal = FVector::PointsAreNear(*Point1, *Point2, Dist);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_PointPlaneDist(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:PointPlaneDist", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* Point;
	if (FNePyStruct_Vector* PyPoint = NePyStructCheck_Vector(PyArgs[0]))
	{
		Point = (FVector*)PyPoint->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Point' must have type 'Vector'");
		return nullptr;
	}

	FVector* PlaneBase;
	if (FNePyStruct_Vector* PyPlaneBase = NePyStructCheck_Vector(PyArgs[1]))
	{
		PlaneBase = (FVector*)PyPlaneBase->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'PlaneBase' must have type 'Vector'");
		return nullptr;
	}

	FVector* PlaneNormal;
	if (FNePyStruct_Vector* PyPlaneNormal = NePyStructCheck_Vector(PyArgs[2]))
	{
		PlaneNormal = (FVector*)PyPlaneNormal->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'PlaneNormal' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::PointPlaneDist(*Point, *PlaneBase, *PlaneNormal);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_PointPlaneProject_Overload1(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:PointPlaneProject_Overload1", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* Point;
	if (FNePyStruct_Vector* PyPoint = NePyStructCheck_Vector(PyArgs[0]))
	{
		Point = (FVector*)PyPoint->Value;
	}
	else
	{
		return nullptr;
	}

	FPlane* Plane;
	if (FNePyStruct_Plane* PyPlane = NePyStructCheck_Plane(PyArgs[1]))
	{
		Plane = (FPlane*)PyPlane->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = FVector::PointPlaneProject(*Point, *Plane);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_PointPlaneProject_Overload3(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:PointPlaneProject_Overload3", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* Point;
	if (FNePyStruct_Vector* PyPoint = NePyStructCheck_Vector(PyArgs[0]))
	{
		Point = (FVector*)PyPoint->Value;
	}
	else
	{
		return nullptr;
	}

	FVector* PlaneBase;
	if (FNePyStruct_Vector* PyPlaneBase = NePyStructCheck_Vector(PyArgs[1]))
	{
		PlaneBase = (FVector*)PyPlaneBase->Value;
	}
	else
	{
		return nullptr;
	}

	FVector* PlaneNormal;
	if (FNePyStruct_Vector* PyPlaneNormal = NePyStructCheck_Vector(PyArgs[2]))
	{
		PlaneNormal = (FVector*)PyPlaneNormal->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = FVector::PointPlaneProject(*Point, *PlaneBase, *PlaneNormal);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_PointPlaneProject_Overload2(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[4] = {nullptr, nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOOO:PointPlaneProject_Overload2", &PyArgs[0], &PyArgs[1], &PyArgs[2], &PyArgs[3]))
	{
		return nullptr;
	}

	FVector* Point;
	if (FNePyStruct_Vector* PyPoint = NePyStructCheck_Vector(PyArgs[0]))
	{
		Point = (FVector*)PyPoint->Value;
	}
	else
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[1]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[2]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		return nullptr;
	}

	FVector* C;
	if (FNePyStruct_Vector* PyC = NePyStructCheck_Vector(PyArgs[3]))
	{
		C = (FVector*)PyC->Value;
	}
	else
	{
		return nullptr;
	}

	auto RetVal = FVector::PointPlaneProject(*Point, *A, *B, *C);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_PointPlaneProject(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	int32 ArgCount = (int32)PyTuple_Size(InArgs);
	PyObject* PyRetVal = nullptr;

	if (ArgCount == 2)
	{
		PyRetVal = FNePyStruct_Vector_PointPlaneProject_Overload1(InSelf, InArgs);
		if (PyRetVal)
		{
			return PyRetVal;
		}
		PyErr_Clear();
	}

	if (ArgCount == 3)
	{
		PyRetVal = FNePyStruct_Vector_PointPlaneProject_Overload3(InSelf, InArgs);
		if (PyRetVal)
		{
			return PyRetVal;
		}
		PyErr_Clear();
	}

	if (ArgCount == 4)
	{
		PyRetVal = FNePyStruct_Vector_PointPlaneProject_Overload2(InSelf, InArgs);
		if (PyRetVal)
		{
			return PyRetVal;
		}
		PyErr_Clear();
	}

	PyErr_SetString(PyExc_RuntimeError, "can't resolve overload function 'PointPlaneProject' on 'FVector'");
	return nullptr;
}

PyObject* FNePyStruct_Vector_VectorPlaneProject(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:VectorPlaneProject", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V;
	if (FNePyStruct_Vector* PyV = NePyStructCheck_Vector(PyArgs[0]))
	{
		V = (FVector*)PyV->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V' must have type 'Vector'");
		return nullptr;
	}

	FVector* PlaneNormal;
	if (FNePyStruct_Vector* PyPlaneNormal = NePyStructCheck_Vector(PyArgs[1]))
	{
		PlaneNormal = (FVector*)PyPlaneNormal->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'PlaneNormal' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::VectorPlaneProject(*V, *PlaneNormal);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Dist(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:Dist", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Dist(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Distance(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:Distance", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Distance(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_DistXY(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:DistXY", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::DistXY(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Dist2D(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:Dist2D", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Dist2D(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_DistSquared(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:DistSquared", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::DistSquared(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_DistSquaredXY(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:DistSquaredXY", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::DistSquaredXY(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_DistSquared2D(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:DistSquared2D", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* V1;
	if (FNePyStruct_Vector* PyV1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		V1 = (FVector*)PyV1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'V1' must have type 'Vector'");
		return nullptr;
	}

	FVector* V2;
	if (FNePyStruct_Vector* PyV2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		V2 = (FVector*)PyV2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'V2' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::DistSquared2D(*V1, *V2);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_BoxPushOut(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:BoxPushOut", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* Normal;
	if (FNePyStruct_Vector* PyNormal = NePyStructCheck_Vector(PyArgs[0]))
	{
		Normal = (FVector*)PyNormal->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Normal' must have type 'Vector'");
		return nullptr;
	}

	FVector* Size;
	if (FNePyStruct_Vector* PySize = NePyStructCheck_Vector(PyArgs[1]))
	{
		Size = (FVector*)PySize->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Size' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::BoxPushOut(*Normal, *Size);

	PyObject* PyRetVal0 = PyFloat_FromDouble(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Min(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:Min", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[1]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'B' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Min(*A, *B);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Max(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[2] = {nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO:Max", &PyArgs[0], &PyArgs[1]))
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[1]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'B' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Max(*A, *B);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Min3(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:Min3", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[1]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'B' must have type 'Vector'");
		return nullptr;
	}

	FVector* C;
	if (FNePyStruct_Vector* PyC = NePyStructCheck_Vector(PyArgs[2]))
	{
		C = (FVector*)PyC->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'C' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Min3(*A, *B, *C);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Max3(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOO:Max3", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* A;
	if (FNePyStruct_Vector* PyA = NePyStructCheck_Vector(PyArgs[0]))
	{
		A = (FVector*)PyA->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'A' must have type 'Vector'");
		return nullptr;
	}

	FVector* B;
	if (FNePyStruct_Vector* PyB = NePyStructCheck_Vector(PyArgs[1]))
	{
		B = (FVector*)PyB->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'B' must have type 'Vector'");
		return nullptr;
	}

	FVector* C;
	if (FNePyStruct_Vector* PyC = NePyStructCheck_Vector(PyArgs[2]))
	{
		C = (FVector*)PyC->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'C' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::Max3(*A, *B, *C);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Parallel(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO|O:Parallel", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* Normal1;
	if (FNePyStruct_Vector* PyNormal1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		Normal1 = (FVector*)PyNormal1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Normal1' must have type 'Vector'");
		return nullptr;
	}

	FVector* Normal2;
	if (FNePyStruct_Vector* PyNormal2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		Normal2 = (FVector*)PyNormal2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Normal2' must have type 'Vector'");
		return nullptr;
	}

	double ParallelCosineThreshold = UE_THRESH_NORMALS_ARE_PARALLEL;
	if (PyArgs[2])
	{
		if (!NePyBase::ToCpp(PyArgs[2], ParallelCosineThreshold))
		{
			PyErr_SetString(PyExc_TypeError, "arg3 'ParallelCosineThreshold' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = FVector::Parallel(*Normal1, *Normal2, ParallelCosineThreshold);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Coincident(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO|O:Coincident", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* Normal1;
	if (FNePyStruct_Vector* PyNormal1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		Normal1 = (FVector*)PyNormal1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Normal1' must have type 'Vector'");
		return nullptr;
	}

	FVector* Normal2;
	if (FNePyStruct_Vector* PyNormal2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		Normal2 = (FVector*)PyNormal2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Normal2' must have type 'Vector'");
		return nullptr;
	}

	double ParallelCosineThreshold = UE_THRESH_NORMALS_ARE_PARALLEL;
	if (PyArgs[2])
	{
		if (!NePyBase::ToCpp(PyArgs[2], ParallelCosineThreshold))
		{
			PyErr_SetString(PyExc_TypeError, "arg3 'ParallelCosineThreshold' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = FVector::Coincident(*Normal1, *Normal2, ParallelCosineThreshold);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Orthogonal(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[3] = {nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OO|O:Orthogonal", &PyArgs[0], &PyArgs[1], &PyArgs[2]))
	{
		return nullptr;
	}

	FVector* Normal1;
	if (FNePyStruct_Vector* PyNormal1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		Normal1 = (FVector*)PyNormal1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Normal1' must have type 'Vector'");
		return nullptr;
	}

	FVector* Normal2;
	if (FNePyStruct_Vector* PyNormal2 = NePyStructCheck_Vector(PyArgs[1]))
	{
		Normal2 = (FVector*)PyNormal2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Normal2' must have type 'Vector'");
		return nullptr;
	}

	double OrthogonalCosineThreshold = UE_THRESH_NORMALS_ARE_ORTHOGONAL;
	if (PyArgs[2])
	{
		if (!NePyBase::ToCpp(PyArgs[2], OrthogonalCosineThreshold))
		{
			PyErr_SetString(PyExc_TypeError, "arg3 'OrthogonalCosineThreshold' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = FVector::Orthogonal(*Normal1, *Normal2, OrthogonalCosineThreshold);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_Coplanar(FNePyStruct_Vector* InSelf, PyObject* InArgs)
{
	PyObject* PyArgs[5] = {nullptr, nullptr, nullptr, nullptr, nullptr};
	if (!PyArg_ParseTuple(InArgs, "OOOO|O:Coplanar", &PyArgs[0], &PyArgs[1], &PyArgs[2], &PyArgs[3], &PyArgs[4]))
	{
		return nullptr;
	}

	FVector* Base1;
	if (FNePyStruct_Vector* PyBase1 = NePyStructCheck_Vector(PyArgs[0]))
	{
		Base1 = (FVector*)PyBase1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'Base1' must have type 'Vector'");
		return nullptr;
	}

	FVector* Normal1;
	if (FNePyStruct_Vector* PyNormal1 = NePyStructCheck_Vector(PyArgs[1]))
	{
		Normal1 = (FVector*)PyNormal1->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg2 'Normal1' must have type 'Vector'");
		return nullptr;
	}

	FVector* Base2;
	if (FNePyStruct_Vector* PyBase2 = NePyStructCheck_Vector(PyArgs[2]))
	{
		Base2 = (FVector*)PyBase2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg3 'Base2' must have type 'Vector'");
		return nullptr;
	}

	FVector* Normal2;
	if (FNePyStruct_Vector* PyNormal2 = NePyStructCheck_Vector(PyArgs[3]))
	{
		Normal2 = (FVector*)PyNormal2->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg4 'Normal2' must have type 'Vector'");
		return nullptr;
	}

	double ParallelCosineThreshold = UE_THRESH_NORMALS_ARE_PARALLEL;
	if (PyArgs[4])
	{
		if (!NePyBase::ToCpp(PyArgs[4], ParallelCosineThreshold))
		{
			PyErr_SetString(PyExc_TypeError, "arg5 'ParallelCosineThreshold' must have type 'float'");
			return nullptr;
		}
	}

	auto RetVal = FVector::Coplanar(*Base1, *Normal1, *Base2, *Normal2, ParallelCosineThreshold);

	PyObject* PyRetVal0 = PyBool_FromLong(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_RadiansToDegrees(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* RadVector;
	if (FNePyStruct_Vector* PyRadVector = NePyStructCheck_Vector(PyArgs[0]))
	{
		RadVector = (FVector*)PyRadVector->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'RadVector' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::RadiansToDegrees(*RadVector);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_DegreesToRadians(FNePyStruct_Vector* InSelf, PyObject* InArg)
{
	PyObject* PyArgs[1] = {InArg};

	FVector* DegVector;
	if (FNePyStruct_Vector* PyDegVector = NePyStructCheck_Vector(PyArgs[0]))
	{
		DegVector = (FVector*)PyDegVector->Value;
	}
	else
	{
		PyErr_SetString(PyExc_TypeError, "arg1 'DegVector' must have type 'Vector'");
		return nullptr;
	}

	auto RetVal = FVector::DegreesToRadians(*DegVector);

	PyObject* PyRetVal0 = NePyStructNew_Vector(RetVal);
	return PyRetVal0;
}

PyObject* FNePyStruct_Vector_AsTuple(FNePyStruct_Vector* InSelf)
{
	double X;

	double Y;

	double Z;

	UKismetMathLibrary::BreakVector(*((FVector*)InSelf->Value), X, Y, Z);

	PyObject* PyRetVal0 = PyFloat_FromDouble(X);
	PyObject* PyRetVal1 = PyFloat_FromDouble(Y);
	PyObject* PyRetVal2 = PyFloat_FromDouble(Z);

	PyObject* PyRetVals = PyTuple_New(3);
	PyTuple_SetItem(PyRetVals, 0, PyRetVal0);
	PyTuple_SetItem(PyRetVals, 1, PyRetVal1);
	PyTuple_SetItem(PyRetVals, 2, PyRetVal2);
	return PyRetVals;
}
// region func body end

static PyMethodDef FNePyStructType_Vector_methods[] = {
	{"Zero", NePyCFunctionCast(&FNePyStruct_Vector_Zero), METH_NOARGS | METH_STATIC, ""},
	{"One", NePyCFunctionCast(&FNePyStruct_Vector_One), METH_NOARGS | METH_STATIC, ""},
	{"UnitX", NePyCFunctionCast(&FNePyStruct_Vector_UnitX), METH_NOARGS | METH_STATIC, ""},
	{"UnitY", NePyCFunctionCast(&FNePyStruct_Vector_UnitY), METH_NOARGS | METH_STATIC, ""},
	{"UnitZ", NePyCFunctionCast(&FNePyStruct_Vector_UnitZ), METH_NOARGS | METH_STATIC, ""},
	{"Cross", NePyCFunctionCast(&FNePyStruct_Vector_Cross), METH_O, ""},
	{"CrossProduct", NePyCFunctionCast(&FNePyStruct_Vector_CrossProduct), METH_VARARGS | METH_STATIC, ""},
	{"Dot", NePyCFunctionCast(&FNePyStruct_Vector_Dot), METH_O, ""},
	{"DotProduct", NePyCFunctionCast(&FNePyStruct_Vector_DotProduct), METH_VARARGS | METH_STATIC, ""},
	{"Equals", NePyCFunctionCast(&FNePyStruct_Vector_Equals), METH_VARARGS, ""},
	{"AllComponentsEqual", NePyCFunctionCast(&FNePyStruct_Vector_AllComponentsEqual), METH_VARARGS, ""},
	{"Component", NePyCFunctionCast(&FNePyStruct_Vector_Component), METH_O, ""},
	{"Set", NePyCFunctionCast(&FNePyStruct_Vector_Set), METH_VARARGS, ""},
	{"GetMax", NePyCFunctionCast(&FNePyStruct_Vector_GetMax), METH_NOARGS, ""},
	{"GetAbsMax", NePyCFunctionCast(&FNePyStruct_Vector_GetAbsMax), METH_NOARGS, ""},
	{"GetMin", NePyCFunctionCast(&FNePyStruct_Vector_GetMin), METH_NOARGS, ""},
	{"GetAbsMin", NePyCFunctionCast(&FNePyStruct_Vector_GetAbsMin), METH_NOARGS, ""},
	{"ComponentMin", NePyCFunctionCast(&FNePyStruct_Vector_ComponentMin), METH_O, ""},
	{"ComponentMax", NePyCFunctionCast(&FNePyStruct_Vector_ComponentMax), METH_O, ""},
	{"GetAbs", NePyCFunctionCast(&FNePyStruct_Vector_GetAbs), METH_NOARGS, ""},
	{"Size", NePyCFunctionCast(&FNePyStruct_Vector_Size), METH_NOARGS, ""},
	{"Length", NePyCFunctionCast(&FNePyStruct_Vector_Length), METH_NOARGS, ""},
	{"SizeSquared", NePyCFunctionCast(&FNePyStruct_Vector_SizeSquared), METH_NOARGS, ""},
	{"SquaredLength", NePyCFunctionCast(&FNePyStruct_Vector_SquaredLength), METH_NOARGS, ""},
	{"Size2D", NePyCFunctionCast(&FNePyStruct_Vector_Size2D), METH_NOARGS, ""},
	{"SizeSquared2D", NePyCFunctionCast(&FNePyStruct_Vector_SizeSquared2D), METH_NOARGS, ""},
	{"IsNearlyZero", NePyCFunctionCast(&FNePyStruct_Vector_IsNearlyZero), METH_VARARGS, ""},
	{"IsZero", NePyCFunctionCast(&FNePyStruct_Vector_IsZero), METH_NOARGS, ""},
	{"IsUnit", NePyCFunctionCast(&FNePyStruct_Vector_IsUnit), METH_VARARGS, ""},
	{"IsNormalized", NePyCFunctionCast(&FNePyStruct_Vector_IsNormalized), METH_NOARGS, ""},
	{"Normalize", NePyCFunctionCast(&FNePyStruct_Vector_Normalize), METH_VARARGS, ""},
	{"GetUnsafeNormal", NePyCFunctionCast(&FNePyStruct_Vector_GetUnsafeNormal), METH_NOARGS, ""},
	{"GetSafeNormal", NePyCFunctionCast(&FNePyStruct_Vector_GetSafeNormal), METH_VARARGS, ""},
	{"GetSafeNormal2D", NePyCFunctionCast(&FNePyStruct_Vector_GetSafeNormal2D), METH_VARARGS, ""},
	{"GetSignVector", NePyCFunctionCast(&FNePyStruct_Vector_GetSignVector), METH_NOARGS, ""},
	{"Projection", NePyCFunctionCast(&FNePyStruct_Vector_Projection), METH_NOARGS, ""},
	{"GetUnsafeNormal2D", NePyCFunctionCast(&FNePyStruct_Vector_GetUnsafeNormal2D), METH_NOARGS, ""},
	{"BoundToCube", NePyCFunctionCast(&FNePyStruct_Vector_BoundToCube), METH_O, ""},
	{"BoundToBox", NePyCFunctionCast(&FNePyStruct_Vector_BoundToBox), METH_VARARGS, ""},
	{"GetClampedToSize", NePyCFunctionCast(&FNePyStruct_Vector_GetClampedToSize), METH_VARARGS, ""},
	{"GetClampedToSize2D", NePyCFunctionCast(&FNePyStruct_Vector_GetClampedToSize2D), METH_VARARGS, ""},
	{"GetClampedToMaxSize", NePyCFunctionCast(&FNePyStruct_Vector_GetClampedToMaxSize), METH_O, ""},
	{"GetClampedToMaxSize2D", NePyCFunctionCast(&FNePyStruct_Vector_GetClampedToMaxSize2D), METH_O, ""},
	{"AddBounded", NePyCFunctionCast(&FNePyStruct_Vector_AddBounded), METH_VARARGS, ""},
	{"Reciprocal", NePyCFunctionCast(&FNePyStruct_Vector_Reciprocal), METH_NOARGS, ""},
	{"IsUniform", NePyCFunctionCast(&FNePyStruct_Vector_IsUniform), METH_VARARGS, ""},
	{"MirrorByVector", NePyCFunctionCast(&FNePyStruct_Vector_MirrorByVector), METH_O, ""},
	{"MirrorByPlane", NePyCFunctionCast(&FNePyStruct_Vector_MirrorByPlane), METH_O, ""},
	{"RotateAngleAxis", NePyCFunctionCast(&FNePyStruct_Vector_RotateAngleAxis), METH_VARARGS, ""},
	{"RotateAngleAxisRad", NePyCFunctionCast(&FNePyStruct_Vector_RotateAngleAxisRad), METH_VARARGS, ""},
	{"CosineAngle2D", NePyCFunctionCast(&FNePyStruct_Vector_CosineAngle2D), METH_O, ""},
	{"ProjectOnTo", NePyCFunctionCast(&FNePyStruct_Vector_ProjectOnTo), METH_O, ""},
	{"ProjectOnToNormal", NePyCFunctionCast(&FNePyStruct_Vector_ProjectOnToNormal), METH_O, ""},
	{"ToOrientationRotator", NePyCFunctionCast(&FNePyStruct_Vector_ToOrientationRotator), METH_NOARGS, ""},
	{"ToOrientationQuat", NePyCFunctionCast(&FNePyStruct_Vector_ToOrientationQuat), METH_NOARGS, ""},
	{"Rotation", NePyCFunctionCast(&FNePyStruct_Vector_Rotation), METH_NOARGS, ""},
	{"FindBestAxisVectors", NePyCFunctionCast(&FNePyStruct_Vector_FindBestAxisVectors), METH_NOARGS, ""},
	{"UnwindEuler", NePyCFunctionCast(&FNePyStruct_Vector_UnwindEuler), METH_NOARGS, ""},
	{"ContainsNaN", NePyCFunctionCast(&FNePyStruct_Vector_ContainsNaN), METH_NOARGS, ""},
	{"ToString", NePyCFunctionCast(&FNePyStruct_Vector_ToString), METH_NOARGS, ""},
	{"UnitCartesianToSpherical", NePyCFunctionCast(&FNePyStruct_Vector_UnitCartesianToSpherical), METH_NOARGS, ""},
	{"HeadingAngle", NePyCFunctionCast(&FNePyStruct_Vector_HeadingAngle), METH_NOARGS, ""},
	{"SlerpVectorToDirection", NePyCFunctionCast(&FNePyStruct_Vector_SlerpVectorToDirection), METH_O | METH_STATIC, ""},
	{"SlerpNormals", NePyCFunctionCast(&FNePyStruct_Vector_SlerpNormals), METH_O | METH_STATIC, ""},
	{"CreateOrthonormalBasis", NePyCFunctionCast(&FNePyStruct_Vector_CreateOrthonormalBasis), METH_NOARGS | METH_STATIC, ""},
	{"PointsAreSame", NePyCFunctionCast(&FNePyStruct_Vector_PointsAreSame), METH_VARARGS | METH_STATIC, ""},
	{"PointsAreNear", NePyCFunctionCast(&FNePyStruct_Vector_PointsAreNear), METH_VARARGS | METH_STATIC, ""},
	{"PointPlaneDist", NePyCFunctionCast(&FNePyStruct_Vector_PointPlaneDist), METH_VARARGS | METH_STATIC, ""},
	{"PointPlaneProject", NePyCFunctionCast(&FNePyStruct_Vector_PointPlaneProject), METH_VARARGS | METH_STATIC, ""},
	{"VectorPlaneProject", NePyCFunctionCast(&FNePyStruct_Vector_VectorPlaneProject), METH_VARARGS | METH_STATIC, ""},
	{"Dist", NePyCFunctionCast(&FNePyStruct_Vector_Dist), METH_VARARGS | METH_STATIC, ""},
	{"Distance", NePyCFunctionCast(&FNePyStruct_Vector_Distance), METH_VARARGS | METH_STATIC, ""},
	{"DistXY", NePyCFunctionCast(&FNePyStruct_Vector_DistXY), METH_VARARGS | METH_STATIC, ""},
	{"Dist2D", NePyCFunctionCast(&FNePyStruct_Vector_Dist2D), METH_VARARGS | METH_STATIC, ""},
	{"DistSquared", NePyCFunctionCast(&FNePyStruct_Vector_DistSquared), METH_VARARGS | METH_STATIC, ""},
	{"DistSquaredXY", NePyCFunctionCast(&FNePyStruct_Vector_DistSquaredXY), METH_VARARGS | METH_STATIC, ""},
	{"DistSquared2D", NePyCFunctionCast(&FNePyStruct_Vector_DistSquared2D), METH_VARARGS | METH_STATIC, ""},
	{"BoxPushOut", NePyCFunctionCast(&FNePyStruct_Vector_BoxPushOut), METH_VARARGS | METH_STATIC, ""},
	{"Min", NePyCFunctionCast(&FNePyStruct_Vector_Min), METH_VARARGS | METH_STATIC, ""},
	{"Max", NePyCFunctionCast(&FNePyStruct_Vector_Max), METH_VARARGS | METH_STATIC, ""},
	{"Min3", NePyCFunctionCast(&FNePyStruct_Vector_Min3), METH_VARARGS | METH_STATIC, ""},
	{"Max3", NePyCFunctionCast(&FNePyStruct_Vector_Max3), METH_VARARGS | METH_STATIC, ""},
	{"Parallel", NePyCFunctionCast(&FNePyStruct_Vector_Parallel), METH_VARARGS | METH_STATIC, ""},
	{"Coincident", NePyCFunctionCast(&FNePyStruct_Vector_Coincident), METH_VARARGS | METH_STATIC, ""},
	{"Orthogonal", NePyCFunctionCast(&FNePyStruct_Vector_Orthogonal), METH_VARARGS | METH_STATIC, ""},
	{"Coplanar", NePyCFunctionCast(&FNePyStruct_Vector_Coplanar), METH_VARARGS | METH_STATIC, ""},
	{"RadiansToDegrees", NePyCFunctionCast(&FNePyStruct_Vector_RadiansToDegrees), METH_O | METH_STATIC, ""},
	{"DegreesToRadians", NePyCFunctionCast(&FNePyStruct_Vector_DegreesToRadians), METH_O | METH_STATIC, ""},
	{"AsTuple", NePyCFunctionCast(&FNePyStruct_Vector_AsTuple), METH_NOARGS, ""},
	NePyManualExportFuncs
	{ NULL } /* Sentinel */
};

static PyObject* FNePyStruct_Vector_RichCmp(FNePyStruct_Vector* InSelf, PyObject* InOther, int InOp)
{
	switch (InOp)
	{
		case Py_EQ:
			return FNePyStruct_Vector___eq__(InSelf, InOther);
		case Py_NE:
			return FNePyStruct_Vector___ne__(InSelf, InOther);
		default:
			break;
	}

	return PyErr_Format(PyExc_NotImplementedError, "this kind of compare is not implemented by Vector");
}

bool NePyStructPropSet_Vector(const FStructProperty* InStructProp, FNePyStructBase* InSelf, void* InBuffer)
{
	if (FNePyStruct_Vector* PyObj = NePyStructCheck_Vector(InSelf))
	{
		InStructProp->Struct->CopyScriptStruct(InBuffer, PyObj->Value);
		return true;
	}
	return false;
}

FNePyStructBase* NePyStructPropGet_Vector(const FStructProperty* InStructProp, const void* InBuffer)
{
	PyTypeObject* PyType = &FNePyStructType_Vector;
	FNePyStruct_Vector* PyObj = (FNePyStruct_Vector*)PyType->tp_alloc(PyType, 0);
#if NEPY_ENABLE_STRUCT_DEEP_ACCESS
	PyObj->Value = (FVector*)InBuffer;
	PyObj->SelfCreatedValue = false;
#else
	PyObj->Value = (FVector*)FMemory::Malloc(sizeof(FVector), alignof(FVector));
	NePyBase::EnsureCopyToStructSafely<FVector>(InStructProp, PyObj->Value);
	InStructProp->Struct->CopyScriptStruct(PyObj->Value, InBuffer);
	PyObj->SelfCreatedValue = true;
#endif
	PyObj->PyOuter = nullptr;
	return PyObj;
}

PyTypeObject* NePyNePyWrappedStructInit_Vector(const UScriptStruct* InScriptStruct, PyTypeObject* InPyBase)
{
	PyTypeObject* NePyStructType = &FNePyStructType_Vector;
	TNePyStructBase<FVector>::InitTypeCommon(NePyStructType);
	NePyStructType->tp_init = (initproc)&FNePyStruct_Vector_FVector;
	NePyStructType->tp_getset = FNePyStructType_Vector_getset;
	NePyStructType->tp_methods = FNePyStructType_Vector_methods;
	static PyNumberMethods PyNumber;
	PyNumber.nb_add = (binaryfunc)&FNePyStruct_Vector___add__;
	PyNumber.nb_subtract = (binaryfunc)&FNePyStruct_Vector___sub__;
	PyNumber.nb_multiply = (binaryfunc)&FNePyStruct_Vector___mul__;
	#if PY_MAJOR_VERSION < 3
	PyNumber.nb_divide = (binaryfunc)&FNePyStruct_Vector___div__;
	#else
	PyNumber.nb_true_divide = (binaryfunc)&FNePyStruct_Vector___div__;
	#endif
	PyNumber.nb_inplace_add = (binaryfunc)&FNePyStruct_Vector___iadd__;
	PyNumber.nb_inplace_subtract = (binaryfunc)&FNePyStruct_Vector___isub__;
	PyNumber.nb_inplace_multiply = (binaryfunc)&FNePyStruct_Vector___imul__;
	#if PY_MAJOR_VERSION < 3
	PyNumber.nb_inplace_divide = (binaryfunc)&FNePyStruct_Vector___idiv__;
	#else
	PyNumber.nb_inplace_true_divide = (binaryfunc)&FNePyStruct_Vector___idiv__;
	#endif
	NePyStructType->tp_as_number = &PyNumber;
	NePyStructType->tp_richcompare = (richcmpfunc)&FNePyStruct_Vector_RichCmp;
	NePyStructType->tp_base = InPyBase;
	PyType_Ready(NePyStructType);

	if (InScriptStruct)
	{
		FNePyStructTypeInfo TypeInfo = {
			NePyStructType,
			ENePyTypeFlags::StaticPyType,
			(NePyStructPropSet)NePyStructPropSet_Vector,
			(NePyStructPropGet)NePyStructPropGet_Vector,
		};
		FNePyWrapperTypeRegistry::Get().RegisterWrappedStructType(InScriptStruct, TypeInfo);
	}

	return NePyStructType;
}

void NePyInitStruct_Vector(PyObject* PyOuterModule)
{
	FNePyWrapperInitializer::Get().RegisterWrappedStructInitFunc(
		TBaseStructure<FVector>::Get(), NePyNePyWrappedStructInit_Vector);
}

FNePyStruct_Vector* NePyStructNew_Vector(const FVector& InValue)
{
	PyTypeObject* PyType = &FNePyStructType_Vector;
	FNePyStruct_Vector* RetValue = (FNePyStruct_Vector*)PyType->tp_alloc(PyType, 0);
	if (FNePyStruct_Vector::Init(RetValue, nullptr, nullptr) < 0)
	{
		Py_DECREF(RetValue);
		return nullptr;
	}
	new(RetValue->Value) FVector(InValue);
	return RetValue;
}

FNePyStruct_Vector* NePyStructCheck_Vector(PyObject* InPyObj)
{
	if (InPyObj && PyObject_TypeCheck(InPyObj, &FNePyStructType_Vector))
	{
		return (FNePyStruct_Vector*)InPyObj;
	}
	return nullptr;
}

PyTypeObject* NePyStructGetType_Vector()
{
	return &FNePyStructType_Vector;
}

namespace NePyBase
{
	bool ToCpp(PyObject* InPyObj, FVector& OutVal)
	{
		if (FNePyStruct_Vector* PyObj = NePyStructCheck_Vector(InPyObj))
		{
			OutVal = *(FVector*)PyObj->Value;
			return true;
		}
		return false;
	}

	bool ToPy(const FVector& InVal, PyObject*& OutPyObj)
	{
		OutPyObj = NePyStructNew_Vector(InVal);
		return true;
	}
}
#ifdef _MSC_VER
#pragma warning(default:4996)
#endif